---
title: "RNA_DGE_Comp_Species_Ensemble"
output: html_document
date: "2026-01-27"
---

```{r setup, include=FALSE,warning=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{r Setting the Enviroment, include=FALSE,warning=FALSE}

#Loading Libraries
library("tidyverse")
library("readxl")
library("readr")
library("ggrepel")
library("ggfortify")
library("patchwork")
library("eulerr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("ggVennDiagram")
library("ggrastr")
library("edgeR")
library("limma")
library("ggsignif")
library("dplyr")
library("purrr")
library("ggplot2")
library("tidyr")

#Loading R Objects Other WorkflowR
Filt_RMG0_RNA_fc_NoD4 <- readRDS("data/QC/Filt_RMG0_RNA_fc_NoD4.RDS")
RNA_Metadata <- readRDS("data/Raw_Data/RNA_Metadata.RDS")
RNA_Metadata_NoD4_NoRep <- readRDS("data/DGE/RNA_Metadata_NoD4_NoRep.RDS")

#Loading R Objects Generated in this WorkflowR
dge <- readRDS("data/DGE/Species/RNA_dge_matrix.RDS")
fit2 <- readRDS("data/DGE/Species/fit2.RDS")
TopTable_RNA_All <- readRDS("data/DGE/Species/TopTable_RNA_all.RDS")
Comparisons_names <- readRDS("data/DGE/Species/Comparisons_names_Trajectory.RDS")
all_genes <- readRDS("data/DGE/Species/ExpressedGenes.RDS")
deg_genes <- readRDS("data/DGE/Species/DEG_AtLeastOne.RDS")
RNA_sets <- readRDS("data/DGE/Species/RNA_DEG_Non_DEG_sets_05.RDS")
RNA_sets_0.1 <- readRDS("data/DGE/Species/RNA_DEG_Non_DEG_sets_05.RDS")
all_intersections <- readRDS("data/DGE/Species/all_intersections.RDS")

```

```{r Volcano_Plot_Function,Result="Hide",warning=FALSE}
generate_volcano_plot <- function(toptable, title) {
  
  # #check for entrezid 
  # if(!"Entrez_ID" %in% colnames(toptable)) stop("Entrez_ID col not present")
  # 
  #make significance labels
  
  toptable <- toptable %>% 
    mutate(Significance = case_when(
      logFC > 0 & adj.P.Val < 0.05 ~ "Upregulated",
      logFC < 0 & adj.P.Val < 0.05 ~ "Downregulated",
      TRUE  ~ "Not Significant"
    ))
  
  #factor significance
  toptable$Significance <- factor(
    toptable$Significance, 
    levels = c("Upregulated", 
               "Not Significant", 
               "Downregulated")
  )
  
  #count genes in each category
  upgenes <- sum(toptable$Significance == "Upregulated")
  nsgenes <- sum(toptable$Significance == "Not Significant")
  downgenes <- sum(toptable$Significance == "Downregulated")
  
  
  #labels for legend
  legend_lab <- c(
    paste0("Upregulated: ", upgenes),
    paste0("Not Significant: ", nsgenes),
    paste0("Downregulated: ", downgenes)
  )
  
  #colors 
  color_map <- c("Upregulated" = "blue",
                 "Not Significant" = "grey30",
                 "Downregulated" = "red")
  
  #generate volcano plots
  p <- ggplot(toptable, aes(x = logFC, 
                            y = -log10(P.Value),
                            color = Significance)) +
    geom_point_rast(alpha = 0.8, size = 3) +
    scale_color_manual(values = color_map, 
                       labels = legend_lab,
                       breaks = c("Upregulated",
                                  "Not Significant", 
                                  "Downregulated"))  +
    xlim(-20,20) +
    labs(title = title, 
         x = expression("log"[2]*"FC"),
         y = expression("-log"[10]*"p-value")) +
    # theme_custom() +
    theme(legend.position = "right")
  
  return(p)
}


```

```{r FC_Plot_Function}
plot_cluster_fc <- function(gene_vector, cluster_name, top_table) {
  
  # Filter TopTable for the genes in this cluster
  df <- top_table %>% dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HC_D0","HC_D2","HC_D5","HC_D15","HC_D30","All_Genes","All_DEGs"
    )))
  
  # Optional: print dimensions and unique genes
  cat(cluster_name, ":", dim(df)[1], "rows,", length(unique(df$Gene)), "unique genes\n")
  
  # Create boxplot
  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    guides(fill = guide_legend(title = "Comparisons")) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(paste0(cluster_name, " RNA FC Comparisons")) +
    theme(
      plot.title = element_text(size = rel(1.5), hjust = 0.5),
      axis.title = element_text(size = 15, colour = "black"),
      strip.background = element_rect(fill = "#CAD899"),
      axis.text.x = element_text(size = 8, colour = "white", angle = 15),
      strip.text.x = element_text(size = 12, colour = "black", face = "bold")
    )
  
  return(p)
}
```

```{r FC_Plot_Function_sig}
plot_cluster_fc_sig <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HC_D0","HC_D2","HC_D5","HC_D15","HC_D30"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # Global test across comparisons
  kw <- kruskal.test(logFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}
```


```{r AbsFC_Plot_Function}
plot_cluster_absfc <- function(gene_vector, cluster_name, top_table) {
  
  # Filter TopTable for the genes in this cluster
  df <- top_table %>% dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HC_D0","HC_D2","HC_D5","HC_D15","HC_D30"
    )))
  
  # Optional: print dimensions and unique genes
  cat(cluster_name, ":", dim(df)[1], "rows,", length(unique(df$Gene)), "unique genes\n")
  
  # Create boxplot
  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    guides(fill = guide_legend(title = "Comparisons")) +
    theme_bw() +
    xlab(" ") +
    ylab("AbsFC") +
    ggtitle(paste0(cluster_name, " RNA AbsFC Comparisons")) +
    theme(
      plot.title = element_text(size = rel(1.5), hjust = 0.5),
      axis.title = element_text(size = 15, colour = "black"),
      strip.background = element_rect(fill = "#CAD899"),
      axis.text.x = element_text(size = 8, colour = "white", angle = 15),
      strip.text.x = element_text(size = 12, colour = "black", face = "bold")
    )
  
  return(p)
}
```

```{r AbsFC_Plot_Function_sig}
plot_cluster_absfc_sig <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HC_D0","HC_D2","HC_D5","HC_D15","HC_D30"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")
  
  # Global test across comparisons
  kw <- kruskal.test(AbsFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$AbsFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("AbslogFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA AbsFC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}
```

```{r RNASeq_DGE_Species_Data}

Filt_RMG0_RNA_fc_NoD4_NoRep <- Filt_RMG0_RNA_fc_NoD4 %>% 
  dplyr::select(-(contains("R")))

RNA_Metadata_NoD4_NoRep <- RNA_Metadata %>% 
  dplyr::filter(Timepoint != "Day4") %>% 
  dplyr::slice(-43:-46)
rownames(RNA_Metadata_NoD4_NoRep) <- colnames(Filt_RMG0_RNA_fc_NoD4_NoRep)
# saveRDS(RNA_Metadata_NoD4_NoRep,"data/DGE/Species/RNA_Metadata_NoD4_NoRep.RDS")

RNA_Metadata_NoD4_NoRep$dgelist <- c(rep(c("Human_Day0","Human_Day2","Human_Day5","Human_Day15","Human_Day30"),7),
                                     rep(c("Chimp_Day0","Chimp_Day2","Chimp_Day5","Chimp_Day15","Chimp_Day30"),7))
#create DGEList object
dge <- DGEList(counts = Filt_RMG0_RNA_fc_NoD4_NoRep)
dge$samples$group <- factor(RNA_Metadata_NoD4_NoRep$dgelist)
dge <- calcNormFactors(dge, method = "TMM")
dge$samples

#dim(dge)
# saveRDS(dge, "data/DGE/Species/RNA_dge_matrix.RDS")
#dge$samples


```


```{r RNASeq_DGE_Species_Data_Model}
design1 <- model.matrix(~ 0 + RNA_Metadata_NoD4_NoRep$dgelist)
colnames(design1) <- gsub("RNA_Metadata_NoD4_NoRep\\$dgelist", "", colnames(design1))
View(design1)

corfit <- duplicateCorrelation(object = dge$counts, design = design1, block = RNA_Metadata_NoD4_NoRep$Individual)
v <- voom(dge, design1, block = RNA_Metadata_NoD4_NoRep$Individual, correlation = corfit$consensus.correlation, plot = TRUE)
fit <- lmFit(v, design1, block = RNA_Metadata_NoD4_NoRep$Individual, correlation = corfit$consensus.correlation)

contrast_matrix <- makeContrasts(
  HC_D0 = Chimp_Day0 - Human_Day0,
  HC_D2 = Chimp_Day2 - Human_Day2,
  HC_D5 = Chimp_Day5 - Human_Day5,
  HC_D15 = Chimp_Day15 - Human_Day15,
  HC_D30 = Chimp_Day30 - Human_Day30,
  levels = design1)

fit2 <- contrasts.fit(fit,contrast_matrix)
fit2 <- eBayes(fit2)

plotSA(fit2, main = "RNA Model")

results_summary <- decideTests(fit2,
                               adjust.method = "BH",
                               p.value = 0.05)
summary(results_summary)
# saveRDS(fit2,"data/DGE/Species/fit2.RDS")
```

```{r RNASeq_DGE_Species_TopTable}
#Create Human TopTable. using listapply, then you can pull specific comp using the $
TopTables_RNA_names <- colnames(fit2$coefficients) 

# colnames(fit2$coefficients)

TopTable_RNA_All <- do.call(
  rbind,
  lapply(TopTables_RNA_names,function(ct) {
    
    tt <- topTable(
      fit2,
      coef = ct,
      number = Inf,
      sort.by = "p"
    )
    
    #add identifiers
    tt$Gene <- rownames(tt)
    tt$Comparisons <- ct
    
    tt
  })
)

# TopTable_RNA_All$Comparisons
# saveRDS(TopTable_RNA_All,"data/DGE/Species/TopTable_RNA_all.RDS")
head(TopTable_RNA_All)
```



```{r RNASeq_DGE_Species_TopTable_VolcancoPlots}
Comparisons_names <- unique(TopTable_RNA_All$Comparisons)
# saveRDS(Comparisons_names,"data/DGE/Species/Comparisons_names_Trajectory.RDS")
plot <- list()
for (n in Comparisons_names) {

plot[[n]] <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == paste0(n)) %>% 
  generate_volcano_plot(.,n)
}

for (n in Comparisons_names) {
  print(plot[[n]])
        }
```

```{r RNASeq_DGE_Species_TopTable_Subsetting_DEGs0.05}
days <- c("D0", "D2", "D5", "D15", "D30")

RNA_sets <- map(
  days,
  ~ {
    df <- TopTable_RNA_All %>%
      filter(Comparisons == paste0("HC_", .x))

    list(
      DEGs = df %>% filter(adj.P.Val < 0.05),
      NonDEGs = df %>% filter(adj.P.Val >= 0.05)
    )
  }
)

names(RNA_sets) <- paste0("Day", sub("D", "", days), "_HC")

# saveRDS(RNA_sets,"data/DGE/Species/RNA_DEG_Non_DEG_sets_05.RDS")
```


```{r RNASeq_DGE_Species_TopTable_Subsetting_DEGs0.05}
all_genes <- unique(TopTable_RNA_All$Gene)
  
DEG_Lists <- list(
  Day0_DEGs_HC = RNA_sets$Day0_HC$DEGs,       # TopTable data.frame
  Day2_DEGs_HC = RNA_sets$Day2_HC$DEGs,
  Day5_DEGs_HC = RNA_sets$Day5_HC$DEGs,
  Day15_DEGs_HC = RNA_sets$Day15_HC$DEGs,
  Day30_DEGs_HC = RNA_sets$Day30_HC$DEGs
)

fit_list <- list()

for (name in names(DEG_Lists)) {

  # DEG gene vector
  deg_vector <- unique(DEG_Lists[[name]]$Gene)

  # Euler with containment
  fit_list[[name]] <- euler(list(
    AllGenes = all_genes,
    DEGs = deg_vector
  ))

  # Plot
  print(
    plot(
      fit_list[[name]],
      fills = list(
        fill = c("grey85", "firebrick"),
        alpha = 0.6
      ),
      labels = c("NonDEGs", "DEGs"),
      quantities = TRUE,
      main = paste0(name, " (p < 0.05)")
    )
  )
}


```

```{r RNASeq_DGE_Species_TopTable_Subsetting_barplot}
####proportion bar plots####
#first factor the timepoints so that they are in the right order
df <- data.frame(
  Day = c("Day0", "Day2", "Day5", "Day15", "Day30"),
  DEGs = c(6569, 4094, 4145, 5070, 5990),
  Non_DEGs = c(8269, 10744, 10684, 9768, 8848)
)

# Convert to long format for ggplot
df_long <- df %>%
  pivot_longer(cols = c(DEGs, Non_DEGs),
               names_to = "Type",
               values_to = "Count") %>%
  group_by(Day) %>%
  mutate(Proportion = Count / sum(Count))  # calculate proportions

df_long$Day <- factor(df_long$Day,levels = c("Day0", "Day2", "Day5", "Day15", "Day30"),ordered = TRUE)

# df_long

ggplot(df_long, aes(x = Day, y = Proportion, fill = Type)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format()) +  # show % on y-axis
  scale_fill_manual(values = c("DEGs" = "#E41A1C", "Non_DEGs" = "#377EB8")) + # custom colors
  labs(y = "Proportion", x = "", fill = "",title = "Proportion of Species DEGs p < 0.05") +
  theme_minimal(base_size = 14)

```
```{r RNASeq_DGE_Species_TopTable_Subsetting_DEGs0.1}
days <- c("D0", "D2", "D5", "D15", "D30")

RNA_sets_0.1 <- map(
  days,
  ~ {
    df <- TopTable_RNA_All %>%
      filter(Comparisons == paste0("HC_", .x))

    list(
      DEGs = df %>% filter(adj.P.Val < 0.1),
      NonDEGs = df %>% filter(adj.P.Val >= 0.1)
    )
  }
)

names(RNA_sets_0.1) <- paste0("Day", sub("D", "", days), "_HC")

# saveRDS(RNA_sets_0.1,"data/DGE/Species/RNA_DEG_Non_DEG_sets_05.RDS")
```

```{r RNASeq_DGE_Species_TopTable_Subsetting_DEGs0.1}
all_genes <- unique(TopTable_RNA_All$Gene)
  
DEG_Lists <- list(
  Day0_DEGs_HC = RNA_sets_0.1$Day0_HC$DEGs,       # TopTable data.frame
  Day2_DEGs_HC = RNA_sets_0.1$Day2_HC$DEGs,
  Day5_DEGs_HC = RNA_sets_0.1$Day5_HC$DEGs,
  Day15_DEGs_HC = RNA_sets_0.1$Day15_HC$DEGs,
  Day30_DEGs_HC = RNA_sets_0.1$Day30_HC$DEGs
)

fit_list <- list()

for (name in names(DEG_Lists)) {

  # DEG gene vector
  deg_vector <- unique(DEG_Lists[[name]]$Gene)

  # Euler with containment
  fit_list[[name]] <- euler(list(
    AllGenes = all_genes,
    DEGs = deg_vector
  ))

  # Plot
  print(
    plot(
      fit_list[[name]],
      fills = list(
        fill = c("grey85", "firebrick"),
        alpha = 0.6
      ),
      labels = c("NonDEGs", "DEGs"),
      quantities = TRUE,
      main = paste0(name, " (p < 0.1)")
    )
  )
}


```

```{r RNASeq_DGE_Species_TopTable_Subsetting_barplot0.1}
####proportion bar plots####
#first factor the timepoints so that they are in the right order
df <- data.frame(
  Day = c("Day0", "Day2", "Day5", "Day15", "Day30"),
  DEGs = c(7539, 5012, 5216, 6103, 7040),
  Non_DEGs = c(7299, 9826, 9622, 8735, 7798)
)

# Convert to long format for ggplot
df_long <- df %>%
  pivot_longer(cols = c(DEGs, Non_DEGs),
               names_to = "Type",
               values_to = "Count") %>%
  group_by(Day) %>%
  mutate(Proportion = Count / sum(Count))  # calculate proportions

df_long$Day <- factor(df_long$Day,levels = c("Day0", "Day2", "Day5", "Day15", "Day30"),ordered = TRUE)

# df_long

ggplot(df_long, aes(x = Day, y = Proportion, fill = Type)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format()) +  # show % on y-axis
  scale_fill_manual(values = c("DEGs" = "#E41A1C", "Non_DEGs" = "#377EB8")) + # custom colors
  labs(y = "Proportion", x = "", fill = "", title = "Proportion of Species DEGs p < 0.1") +
  theme_minimal(base_size = 14)

```


```{r RNASeq_DGE_Species_TopTable_Subsetting_FC}
TopTable_RNA_All <- readRDS("data/DGE/Species/TopTable_RNA_all.RDS")
all_genes <- readRDS("data/DGE/Species/ExpressedGenes.RDS")
deg_genes <- readRDS("data/DGE/Species/DEG_AtLeastOne.RDS")

Gene_list <- list(
  All_genes  = all_genes,
  DEGs = deg_genes
)

cluster_plots <- lapply(names(Gene_list), function(clust_name) {
  plot_cluster_fc_sig(Gene_list[[clust_name]], clust_name, TopTable_RNA_All)
})
names(cluster_plots) <- names(Gene_list)

for (p in cluster_plots) print(p)

Day0_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D0")
print("Day 0 Average logFC")
print(mean(Day0_AllGenes$logFC))

Day2_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D2")
print("Day 2 Average logFC")
print(mean(Day2_AllGenes$logFC))

Day5_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D5")
print("Day 5 Average logFC")
print(mean(Day5_AllGenes$logFC))

Day15_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D15")
print("Day 15 Average logFC")
print(mean(Day15_AllGenes$logFC))

Day30_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D30")
print("Day 30 Average logFC")
print(mean(Day30_AllGenes$logFC))

```

```{r RNASeq_DGE_Species_TopTable_Subsetting_AbsFC}
all_genes <- readRDS("data/DGE/Species/ExpressedGenes.RDS")
deg_genes <- readRDS("data/DGE/Species/DEG_AtLeastOne.RDS")

TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

Gene_list <- list(
  All_genes  = all_genes,
  DEGs = deg_genes
)

cluster_plots <- lapply(names(Gene_list), function(clust_name) {
  plot_cluster_absfc_sig(Gene_list[[clust_name]], clust_name, TopTable_RNA_All)
})
names(cluster_plots) <- names(Gene_list)

for (p in cluster_plots) print(p)

Day0_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D0")
print("Day 0 Average AbslogFC")
print(mean(Day0_AllGenes$AbsFC))

Day2_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D2")
print("Day 2 Average AbslogFC")
print(mean(Day2_AllGenes$AbsFC))

Day5_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D5")
print("Day 5 Average AbslogFC")
print(mean(Day5_AllGenes$AbsFC))

Day15_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D15")
print("Day 15 Average AbslogFC")
print(mean(Day15_AllGenes$AbsFC))

Day30_AllGenes <- TopTable_RNA_All %>% 
  dplyr::filter(Comparisons == "HC_D30")
print("Day 30 Average AbslogFC")
print(mean(Day30_AllGenes$AbsFC))
```

```{r RNASeq_DGE_Species_TopTable_Venn_ggplot}

# Your DEGs per day (already defined)

sets <- list(
  Day0_DEGs_HC = RNA_sets$Day0_HC$DEGs$Gene,       # TopTable data.frame
  Day2_DEGs_HC = RNA_sets$Day2_HC$DEGs$Gene,
  Day5_DEGs_HC = RNA_sets$Day5_HC$DEGs$Gene,
  Day15_DEGs_HC = RNA_sets$Day15_HC$DEGs$Gene,
  Day30_DEGs_HC = RNA_sets$Day30_HC$DEGs$Gene
)

```


```{r RNASeq_DGE_Species_TopTable_Venn_ggplot_plot,fig.height=13,fig.width=12}
# Create a 5-way Venn diagram
p <- ggVennDiagram(sets,
                   label_alpha = 0,       # makes background of labels transparent
                   label = "count") +     # show counts in intersections
  scale_fill_gradient(low = "skyblue", high = "navy") + # optional color gradient
  theme(legend.position = "none") +                     # hide legend
  ggtitle("5-way DEGs")

# Plot
print(p)

```

```{r RNASeq_DGE_Species_TopTable_Venn_Intersections}


# Helper function to get intersections
get_intersections <- function(sets_list) {
  set_names <- names(sets_list)
  n <- length(sets_list)
  result <- list()
  
  # Loop over all combination lengths (1 to n)
  for (k in 1:n) {
    combos <- combn(set_names, k, simplify = FALSE)
    for (combo in combos) {
      # Start with first set in combo
      genes <- sets_list[[combo[1]]]
      # Intersect with the rest
      if (length(combo) > 1) {
        for (s in combo[-1]) {
          genes <- intersect(genes, sets_list[[s]])
        }
      }
      # Remove genes that appear in other sets outside the combo (exclusive)
      other_sets <- setdiff(set_names, combo)
      if (length(other_sets) > 0) {
        for (s in other_sets) {
          genes <- setdiff(genes, sets_list[[s]])
        }
      }
      # Save if any genes remain
      if (length(genes) > 0) {
        result[[paste(combo, collapse = "&")]] <- genes
      }
    }
  }
  return(result)
}

# Compute all intersections
all_intersections <- get_intersections(sets)
# saveRDS(all_intersections,"data/DGE/Species/all_intersections.RDS")

# # Example: genes only in Day0
# all_intersections$Day0

# # Example: genes only in Day0 & Day2
# all_intersections$`Day0&Day2`


```


```{r RNASeq_DGE_Clusters_FC_Quadrants_0_2}
H_comp <- "HC_D0"
C_comp <- "HC_D2"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

# format(pval, scientific = TRUE, digits =3)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )
```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_5}
H_comp <- "HC_D2"
C_comp <- "HC_D5"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

# format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )
```

```{r RNASeq_DGE_Clusters_FC_Quadrants_5_15}
H_comp <- "HC_D5"
C_comp <- "HC_D15"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

# format(pval, scientific = TRUE, digits = 3)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )
```

```{r RNASeq_DGE_Clusters_FC_Quadrants_15_30}
H_comp <- "HC_D15"
C_comp <- "HC_D30"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

# format(pval, scientific = TRUE, digits = 3)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )
```


```{r Updating Website, eval = FALSE}

# git -> commit all changes
# git -> push
# wflow_publish("analysis/DGE/RNA_DGE_Comp_Species_Ensemble.Rmd")

```
