---
title: "RNA_CorrelationHeatMap_Symbol"
output: html_document
date: "2026-01-27"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Setting_Up_Enviroment,results="hide"}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")

# BiocManager::install("SummarizedExperiment")

ann_colors_No4 <- readRDS("data/QC/ann_colors_no4.RDS")
RNA_fc_df <- readRDS("data/Raw_Data/RNA_fc_df.RDS")
RNA_Metadata <- readRDS("data/Raw_Data/RNA_Metadata.RDS")
Filt_RMGO_RNA_log2cpm_NoD4_unique <- readRDS("data/QC/Symbol/Filt_RMGO_RNA_log2cpm_NoD4_unique.RDS")
RNA_Metadata_No4 <- readRDS("data/QC/RNA_Metatdata_No4.RDS")
```

```{r RNASeq_FeatureCounts_RMG0_No4,results="hide"}
Filt_RMGO_RNA_fc_NoD4 <- readRDS("data/QC/Filt_RMG0_RNA_fc_NoD4.RDS")

####Subset####
Filt_RMGO_RNA_fc_NoD4 <- Filt_RMGO_RNA_fc_NoD4 %>%
  as.data.frame() %>%
  rownames_to_column(var = "ENSEMBL")

gene_symbols <- AnnotationDbi::select(
  org.Hs.eg.db,
  keys = Filt_RMGO_RNA_fc_NoD4$ENSEMBL,
  columns = c("SYMBOL"),
  keytype = "ENSEMBL"
)

# ----------------- Join Back to Main Data -----------------
Filt_RMGO_RNA_fc_NoD4 <- left_join(Filt_RMGO_RNA_fc_NoD4, gene_symbols, by = c("ENSEMBL" = "ENSEMBL"))
Filt_RMGO_RNA_fc_NoD4 <- Filt_RMGO_RNA_fc_NoD4 %>% 
  dplyr::select(-ENSEMBL)

Filt_RMGO_RNA_fc_NoD4_unique <- Filt_RMGO_RNA_fc_NoD4 %>%
  filter(!is.na(SYMBOL)) %>%      # remove NAs
  group_by(SYMBOL) %>%
  slice_max(
    rowSums(abs(pick(where(is.numeric))), na.rm = TRUE),
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup() %>% 
  column_to_rownames("SYMBOL")

Filt_RMGO_RNA_log2cpm_NoD4_unique <- cpm(Filt_RMGO_RNA_fc_NoD4_unique,log = TRUE) %>% 
  as.data.frame()
# ----------------- Save Annotated Output -----------------
# write_csv(Filt_RMGO_RNA_fc_NoD4_unique, "data/QC/Symbol/Filt_RMGO_RNA_fc_NoD4_unique.csv")
# write_csv(Filt_RMGO_RNA_log2cpm_NoD4_unique, "data/QC/Symbol/Filt_RMGO_RNA_log2cpm_NoD4_unique.csv")
# saveRDS(Filt_RMGO_RNA_fc_NoD4_unique,"data/QC/Symbol/Filt_RMGO_RNA_fc_NoD4_unique.RDS")
# saveRDS(Filt_RMGO_RNA_log2cpm_NoD4_unique,"data/QC/Symbol/Filt_RMGO_RNA_log2cpm_NoD4_unique.RDS")

```


```{r rRNASeq_FeatureCounts_Cor_RMG0_No4}

######Cor_HeatMap####

Filt_RMG0_RNA_log2cpm_NoD4 <- Filt_RMGO_RNA_log2cpm_NoD4_unique

Cor_Filt_RMG0_RNA_log2cpm_NoD4 <- cor(Filt_RMG0_RNA_log2cpm_NoD4, method = "spearman")

Cor_metadata_No4 <- RNA_Metadata_No4 %>% 
  dplyr::filter(Timepoint !="Day4")

# saveRDS(Cor_metadata_No4, "data/QC/Symbol/Cor_metadata_No4.RDS")
# saveRDS(Cor_Filt_RMG0_RNA_log2cpm_NoD4, "data/QC/Symbol/Cor_Filt_RMG0_RNA_log2cpm_NoD4.RDS")
```


```{r rRNASeq_FeatureCounts_HeatMap_RMG0_No4,fig.height=10,fig.width=10}
ann_colors_No4$Timepoint <- ann_colors_No4$timepoint_cor
ann_colors_No4$Species <- ann_colors_No4$species_cor
ann_colors_No4$Individual <- ann_colors_No4$individual_cor
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm_NoD4,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No4[, c("Species", "Timepoint","Individual")],
         annotation_colors = ann_colors_No4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2CPM-RowMeans>0-NoDay4)")
)
```

```{r RNA_CHDGene_Species_LogFoldChange}
TopTable_RNA_All <- readRDS("data/DGE/Species/TopTable_RNA_all.RDS")

median_all_df <- TopTable_RNA_All %>%
  group_by(Comparisons) %>%
  summarise(
    median_logFC = median(logFC, na.rm = TRUE),
    .groups = "drop"
  )

TF_Genes <- c("POU5F1","NANOG","SOX2","LIN28","REX1","SSEA5","CD90","NCAM1","T","MIXL1","ROR2","CD13","MESP1","KDR","KIT","")

gene_vector <- ensembl_to_hgnc %>% 
  dplyr::filter(hgnc_symbol %in% chdGenes) %>% 
  dplyr::pull(ensembl_gene_id)

TopTable_RNA_CHD <- TopTable_RNA_All %>% 
  dplyr::filter(Gene %in% gene_vector) %>% 
  dplyr::mutate(
    Comparisons = factor(
      Comparisons,
      levels = c("HC_D0", "HC_D2", "HC_D5", "HC_D15", "HC_D30")
    )
  )

TopTable_RNA_CHD <- TopTable_RNA_CHD %>%
  rowwise() %>%
  mutate(
    isDEG = Gene %in% CHD_overlap_results[[Comparisons]]$DEG_CHD_Genes
  ) %>%
  ungroup()


# Determine bottom-left coordinates
x_min <- min(as.numeric(TopTable_RNA_CHD$Comparisons))  # first comparison
y_min <- min(TopTable_RNA_CHD$logFC, na.rm = TRUE) - 0.5     # lowest logFC among CHD genes

ggplot(TopTable_RNA_CHD, aes(x = Comparisons, y = logFC, group = Gene)) +
  geom_line(alpha = 0.25) +
  geom_point(aes(color = isDEG), size = 2, alpha = 0.8) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "dodgerblue")) +

  # Median line (all genes)
  geom_line(
    data = median_all_df,
    aes(x = Comparisons, y = median_logFC, group = 1),
    inherit.aes = FALSE,
    linewidth = 1.6,
    color = "firebrick"
  ) +
  geom_point(
    data = TopTable_RNA_CHD %>% filter(!isDEG),
    aes(x = Comparisons, y = logFC),
    color = "grey70",
    size = 2,
    alpha = 0.8
  ) +

  # DEG points on top (blue)
  geom_point(
    data = TopTable_RNA_CHD %>% filter(isDEG),
    aes(x = Comparisons, y = logFC),
    color = "dodgerblue",
    size = 2,
    alpha = 0.8
  ) +
  # Median label bottom-left
  geom_text(
    data = data.frame(
      x = 1,
      y = min(TopTable_RNA_CHD$logFC, na.rm = TRUE) - 0.5
    ),
    aes(x = x, y = y, label = "Median (all genes)"),
    inherit.aes = FALSE,
    color = "firebrick",
    size = 4
  ) +

  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    x = "Comparison",
    y = "log2 Fold Change",
    color = "DEG",
    title = "CHD gene trajectories with DEGs highlighted"
  )

```
