---
title: "QC_Checks"
output: html_document
date: "2025-11-29"
---
```{r package_loading}
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
```

```{r RNA-Seq_MultiQC_Metris}
RNA_flagstat <- read.delim("~/diff_timeline_tes/RNA/RNA_flagstat.txt", row.names=1)
#Rename column Names to More Useful Info

RNA_flagstat$Timepoint <- factor(RNA_flagstat$Timepoint, levels=c("Day0","Day2","Day4","Day5","Day15","Day"))

```


```{r Plotting_Bargraph_rawcounts,fig.height=8,fig.width=14}
ggplot(RNA_flagstat, aes(x = row.names(RNA_flagstat), y = Total_Reads/2)) +
  geom_col() +
  geom_hline(yintercept = 10000000, linetype="dotted",color="red",size=1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.4,size=9)) +
  labs(
    title = "Total Read Pairs",
    x = "Sample",
    y = "Total Read Pairs"
  )
```
```{r Plotting_boxplot_rawcounts,fig.height=5,fig.width=5}
ggplot(RNA_flagstat, aes(x="All",y = Total_Reads/2)) +
  geom_boxplot(fill = "lightblue") +
geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.6),
              size = 3,
              alpha = 0.9,
              shape = 21,
              colour = "black",
              stroke = 0.7
  ) +
  scale_y_continuous(limits = c(0, 30000000))
  theme_bw() +
  labs(
    title = "Total Read Pairs Across All Samples",
    y = "Total Read Pairs",
    x = ""
  )
```

```{r Plotting_Boxplot_rawcounts_byspecies fig.height=8,fig.width=12}

ggplot(RNA_flagstat, aes(x = Species, y = Total_Reads/2, fill = Species)) +
  geom_boxplot() +
  geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
  theme_bw() +
  labs(
    title = "Total Read Pairs by Species (H vs C)",
    x = "Species",
    y = "Total Read Pairs"
  )

```

```{r Plotting_Boxplot_rawcounts_bytimepoint fig.height=8,fig.width=12}

Timepoint_Order <- c("Day0","Day2","Day4","Day15","Day30")

ggplot(RNA_flagstat, aes(x = Timepoint, y = Total_Reads/2, fill = Species)) +
  geom_boxplot() +
 geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
  theme_bw() +
  labs(
    title = "Total Read Pairs by Species (H vs C)",
    x = "Timepoint",
    y = "Total Read Pairs"
  )

```

```{r Plotting_Boxplot_rawcounts_bycellline,fig.height=8,fig.width=12}

ggplot(RNA_flagstat, aes(x = CellLine, y = Total_Reads/2, fill = CellLine)) +
  geom_boxplot() +
 geom_jitter(aes(fill = CellLine),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
  theme_bw() +
  labs(
    title = "Total Read Pairs by Cell Line",
    x = "Cell Line",
    y = "Total Read Pairs"
  )

```
```{r Plotting_Barplot_Duplication,fig.height=8,fig.width=14}
ggplot(RNA_flagstat, aes(x = row.names(RNA_flagstat), y = Duplication_Percent*100)) +
  geom_col() +
  ylim(0,100) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.4, size = 9)) +
  labs(
    title = "Duplication Percentage",
    x = "Sample",
    y = "Duplication Percent"
  )

  
```

```{r Plotting_Boxplot_Duplication,fig.height=5,fig.width=3}
ggplot(RNA_flagstat, aes(x="All",y = Duplication_Percent*100)) +
  geom_boxplot(fill = "lightblue") +
geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.6),
              size = 3,
              alpha = 0.9,
              shape = 21,
              colour = "black",
              stroke = 0.7
  ) +
  scale_y_continuous(limits = c(0, 100)) +
  theme_bw() +
  labs(
    title = "Duplication Across 
       All Samples",
    y = "Percent Duplicaiton",
    x = ""
  )
```

```{r Plotting_Boxplot_Duplication_byspecies,fig.height=8,fig.width=4}

ggplot(RNA_flagstat, aes(x = Species, y = Duplication_Percent*100, fill = Species)) +
  geom_boxplot() +
  geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
  scale_y_continuous(limits = c(0, 100)) +
  theme_bw() +
  labs(
    title = "         Duplication Levels
        by Species (H vs C)",
    x = "Species",
    y = "Duplication Percent"
  )

```

```{r Plotting_Boxplot_Duplication_bytimepoint,fig.height=4,fig.width=6}

ggplot(RNA_flagstat, aes(x = Timepoint, y = Duplication_Percent*100, fill = Species)) +
  geom_boxplot() +
 geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
   scale_y_continuous(limits = c(0, 100) )+
  theme_bw() +
  labs(
    title = "Duplication by Species (H vs C)",
    x = "Timepoint",
    y = "Percent Duplication"
  )

```

```{r Plotting_Barplot_Mapping,fig.height=5,fig.width=10}
ggplot(RNA_flagstat, aes(x = row.names(RNA_flagstat), y = Mapped_Percent)) +
  geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.4,size=9)) +
  labs(
    title = "Mapping of Reads",
    x = "Sample",
    y = "Percent Mapping"
  )
```


```{r Plotting_Boxplot_Mapping_bytimepoint,fig.height=4,fig.width=6}

ggplot(RNA_flagstat, aes(x = Timepoint, y = Mapped_Percent, fill = Species)) +
  geom_boxplot() +
 geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
   scale_y_continuous(limits = c(0, 100)) +
  theme_bw() +
  labs(
    title = "Mapping by Species (H vs C)",
    x = "Timepoint",
    y = "Percent Mapping"
  )

```

```{r Plotting_Barplot_ProperPairing,fig.height=5,fig.width=10}
ggplot(RNA_flagstat, aes(x = row.names(RNA_flagstat), y = Properly_Paired_Percent)) +
  geom_col() +
  theme_bw() +
  scale_y_continuous(limits = c(0, 100)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.4,size=9)) +
  labs(
    title = "Proper Pairing of Mapped of Reads",
    x = "Sample",
    y = "Percent Properly Paired"
  )
```

```{r Plotting_Boxplot_ProperPairing_bytimepoint,fig.height=4,fig.width=6}
ggplot(RNA_flagstat, aes(x = Timepoint, y = Properly_Paired_Percent, fill = Species)) +
  geom_boxplot() +
 geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
   scale_y_continuous(limits = c(0, 100)) +
  theme_bw() +
  labs(
    title = "Properly Paired by Species (H vs C)",
    x = "Timepoint",
    y = "Percent Properly Paired"
  )


```

```{r Plotting_Barplot_FinalCount_bytimepoint,fig.height=4,fig.width=6}


ggplot(RNA_flagstat, aes(x = Timepoint, y = Final_Read_Pairs, fill = Species)) +
  geom_boxplot() +
 geom_jitter(aes(fill = Species),
              position = position_jitterdodge(jitter.width = 0.2,
                                              dodge.width = 0.8),
              size = 3,
              alpha = 0.9,
              shape = 21,        # filled circle with border
              colour = "black",  # border/outline
              stroke = 0.7       # outline thickness
  ) +
   scale_y_continuous(limits = c(0, 30000000))+
  theme_bw() +
  labs(
    title = "Final Number of Read Pairs",
    x = "Timepoint",
    y = "Count of Read Pairs"
  )

```

```{r RNA_counts_table}
chimp_RNA_pantro5_fc <- read.delim("~/diff_timeline_tes/RNA/featurecounts/c_samples_counts.txt", comment.char="#",row.names=1)
human_RNA_hg38_fc <- read.delim("~/diff_timeline_tes/RNA/featurecounts/h_sample_counts.txt", comment.char="#",row.names=1)
human_df <- human_RNA_hg38_fc %>%
  tibble::rownames_to_column("gene")
chimp_df <- chimp_RNA_pantro5_fc %>%
  tibble::rownames_to_column("gene")
RNA_joined_fc <- left_join(human_df, chimp_df, by = "gene")

#To keep only OrthoGenes and sample columns
RNA_fc <- RNA_joined_fc[ , !(names(RNA_joined_fc) %in% c("gene","Chr.x","Start.x","End.x","Strand.x","Length.x","Geneid.x","Chr.y","Start.y","End.y","Strand.y","Length.y","Geneid.y"))]
# 89 columns; 7 x 6 = 42 Human Exp, 7 x 6 = 42 Chimp Exp, 4 Human Replicate
rownames(RNA_fc) <- RNA_joined_fc$gene

#Rename column Names to More Useful Info
col_names<- c("H28126_D0",
              "H28126_D2",
              "H28126_D4",
              "H28126_D5",
              "H28126_D15",
              "H28126_D30",
              "H17_D0",
              "H17_D2",
              "H17_D4",
              "H17_D5",
              "H17_D15",
              "H17_D30",
              "H78_D0",
              "H78_D2",
              "H78_D4",
              "H78_D5",
              "H78_D15",
              "H78_D30",
              "H20682_D0",
              "H20682_D2",
              "H20682_D4",
              "H20682_D5",
              "H20682_D15",
              "H20682_D30",
              "H22422_D0",
              "H22422_D2",
              "H22422_D4",
              "H22422_D5",
              "H22422_D15",
              "H22422_D30",
              "H21792_D0",
              "H21792_D2",
              "H21792_D4",
              "H21792_D5",
              "H21792_D15",
              "H21792_D30",
              "H24280_D0",
              "H24280_D2",
              "H24280_D4",
              "H24280_D5",
              "H24280_D15",
              "H24280_D30",
              "H20682R_D0",
              "H20682R_D2",
              "H20682R_D5",
              "H20682R_D30",
              "C3649_D0",
              "C3649_D2",
              "C3649_D4",
              "C3649_D5",
              "C3649_D15",
              "C3649_D30",
              "C4955_D0",
              "C4955_D2",
              "C4955_D4",
              "C4955_D5",
              "C4955_D15",
              "C4955_D30",
              "C3651_D0",
              "C3651_D2",
              "C3651_D4",
              "C3651_D5",
              "C3651_D15",
              "C3651_D30",
              "C40210_D0",
              "C40210_D2",
              "C40210_D4",
              "C40210_D5",
              "C40210_D15",
              "C40210_D30",
              "C8861_D0",
              "C8861_D2",
              "C8861_D4",
              "C8861_D5",
              "C8861_D15",
              "C8861_D30",
              "C40280_D0",
              "C40280_D2",
              "C40280_D4",
              "C40280_D5",
              "C40280_D15",
              "C40280_D30",
              "C3647_D0",
              "C3647_D2",
              "C3647_D4",
              "C3647_D5",
              "C3647_D15",
              "C3647_D30"
)
colnames(RNA_fc)<-col_names
dim(RNA_fc)
```
```{r - Boxplot_and_histograms_unfiltered}
#####Unfiltered####
RNA_log2cpm <- cpm(RNA_fc,log=TRUE)
print(hist(RNA_log2cpm,  main = "Histogram of all counts (unfiltered)",
     xlab =expression("Log"[2]*" counts-per-million"), col =4 ))

boxplot(RNA_log2cpm, main = "Boxplots of log cpm per sample
          (unfiltered)", xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_names),  # positions (one per sample)
     labels = col_names,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.3)        # shrink label size


timepoint <- c(rep(c("D0","D2","D4","D5","D15","D30"),7),"D0R","D2R","D5R","D30R", rep(c("D0","D2","D4","D5","D15","D30"),7))
time_order <- c("D0", "D2", "D4", "D5", "D15", "D30")
species <- c(rep("H",42),rep("HR",4),rep("C",42))

T_RNA_log2cpm <- t(RNA_log2cpm)
pca_raw <- prcomp(T_RNA_log2cpm,scale=TRUE,center=TRUE)
pca_raw_meta <- as.data.frame(pca_raw$x)
pca_raw_meta$sample <- rownames(pca_raw_meta)
pca_raw_meta$species <- species
pca_raw_meta$timepoint <- timepoint
pca_raw_meta$timepoint <- factor(pca_raw_meta$timepoint, levels = time_order)
dim(T_RNA_log2cpm)
```


```{r PCA_RNA-Seq_Unfiltered,fig.height=4,fig.width=9}
print(
  ggplot(pca_raw_meta, aes(x = PC1, y = PC2, color = timepoint, shape = species)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_text_repel(aes(label = sample), size = 3, max.overlaps = 100) +
  theme_minimal() +
  labs(title = "PCA of log2CPM RNA-Seq Data Unfiltered",
       x = paste0("PC1 (", round(summary(pca_raw)$importance[2, 1] * 100, 1), "%)"),
       y = paste0("PC2 (", round(summary(pca_raw)$importance[2, 2] * 100, 1), "%)"))
)

```

```{r RNA-Seq_Filtering_based_on_RowMeans}
#####RowMu>0####
row_means <- rowMeans(RNA_log2cpm)
Filt_RMG0_RNA_fc <- RNA_fc[row_means >0,]
Filt_RMG0_RNA_log2cpm <- cpm(Filt_RMG0_RNA_fc,log=TRUE)

hist(Filt_RMG0_RNA_log2cpm, main = "Histogram of filtered counts using rowMeans > 0 method",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

boxplot(Filt_RMG0_RNA_log2cpm, main = "Boxplots of log cpm per sample (RowMeans>0)",xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_names),  # positions (one per sample)
     labels = col_names,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.3)        # shrink label size

```


```{r PCA_RNA-Seq_RowMeans_Filtering,fig.height=4,fig.width=9}
#####PCA####
T_Filt_RMG0_RNA_log2cpm <- t(Filt_RMG0_RNA_log2cpm)
pca_RMG0 <- prcomp(T_Filt_RMG0_RNA_log2cpm,scale=TRUE,center=TRUE)
pca_RMG0_meta <- as.data.frame(pca_RMG0$x)
pca_RMG0_meta$sample <- rownames(pca_RMG0_meta)
pca_RMG0_meta$species <- species
pca_RMG0_meta$timepoint <- timepoint
pca_RMG0_meta$timepoint <- factor(pca_RMG0_meta$timepoint, levels = time_order)
dim(T_Filt_RMG0_RNA_log2cpm)

######Cor_HeatMap####
cor_Filt_RMG0_RNA_log2cpm <- cor(Filt_RMG0_RNA_log2cpm, method = "pearson")
time <- factor(timepoint,levels = c("D0","D2","D4","D5","D15","D30","D0R","D2R","D5R","D30R"))
metadata <- data.frame(
  sample_cor = colnames(Filt_RMG0_RNA_log2cpm),
  species_cor = species,
  timepoint_cor = timepoint
)
ann_colors <- list(
  timepoint_cor = c(
    "D0" = "#883268",   # Purple
    "D2" = "#3E7274",  # blue
    "D4" = "#5AAA464D",  # light green
    "D5" = "#94C47D",  # Green
    "D15" = "#C03830",  # red
    "D30" = "#830C05",  # dark red
    "D0R" = "#883268",  # pink
    "D2R" = "#3E7274",  # teal
    "D5R" = "#94C47D",  # bright green
    "D30R" = "#830C05"  # bright red
  ),
  species_cor = c(
    "H" = "#171717",  # black
    "C" = "#17171717",   # light grey
    "HR" = "#171717B0"#Dark Grey
  )
)
rownames(metadata) <- metadata$sample_cor
```
```{r Graphing_PCA_RNA-Seq_RowMeans_Filtering,fig.height=4,fig.width=9}
#PC1 vs PC2
print(
  ggplot(pca_RMG0_meta, aes(x = PC1, y = PC2, color = timepoint, shape = species)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_text_repel(aes(label = sample), size = 3, max.overlaps = 100) +
  theme_minimal() +
  labs(title = "PCA of log2CPM RNA-Seq Data (RowMean>0)",
       x = paste0("PC1 (", round(summary(pca_RMG0)$importance[2, 1] * 100, 1), "%)"),
       y = paste0("PC2 (", round(summary(pca_RMG0)$importance[2, 2] * 100, 1), "%)"))
)
```

```{r Graphing_Correlation_HeatMap_RNA-Seq_RowMeans_Filtering,fig.height=10,fig.width=10}
print(
  pheatmap(cor_Filt_RMG0_RNA_log2cpm,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = metadata[, c("species_cor", "timepoint_cor")],
         annotation_colors = ann_colors,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation \n(Pearson-log2CPM-RowMeans>0)")
)
```

```{r RNA-Seq_NoDay4}

####Subset####
time_NoD4 <- c(rep(c("D0","D2","D5","D15","D30"),7),"D0","D2","D5","D30",rep(c("D0","D2","D5","D15","D30"),7))
species_NoD4 <- c(rep("H",35),rep("HR",4),rep("C",35))
keep_timepoints_NoD4 <- time %in% c("D0", "D2", "D5", "D15","D30","D0R","D2R","D5R","D30R")

RNA_fc_NoD4 <- RNA_fc[,keep_timepoints_NoD4]
RNA_log2cpm_NoD4 <- cpm(RNA_fc_NoD4,log=TRUE)
row_means_NoD4 <- rowMeans(RNA_log2cpm_NoD4)
Filt_RMG0_RNA_fc_NoD4 <- RNA_fc_NoD4[row_means_NoD4 >0,]
dim(Filt_RMG0_RNA_fc_NoD4)
Filt_RMG0_RNA_log2cpm_NoD4 <- cpm(Filt_RMG0_RNA_fc_NoD4,log=TRUE)

T_Filt_RMG0_RNA_log2cpm_NoD4 <- t(Filt_RMG0_RNA_log2cpm_NoD4)
pca_NoD4 <- prcomp(T_Filt_RMG0_RNA_log2cpm_NoD4,scale=TRUE,center=TRUE)
pca_NoD4_meta <- as.data.frame(pca_NoD4$x)
pca_NoD4_meta$sample <- rownames(pca_NoD4_meta)
pca_NoD4_meta$species <- species_NoD4
pca_NoD4_meta$timepoint <- time_NoD4
time_NoD4_level <- as.factor(c("D0","D2","D5","D15","D30"))
pca_NoD4_meta$timepoint <- factor(pca_NoD4_meta$timepoint, levels = time_NoD4_level)
dim(T_Filt_RMG0_RNA_log2cpm_NoD4)

######Cor_HeatMap####
cor_Filt_RMG0_RNA_log2cpm_NoD4 <- cor(Filt_RMG0_RNA_log2cpm_NoD4, method = "pearson")
time <- factor(timepoint,levels = c("D0","D2","D5","D15","D30","D0R","D2R","D5R","D30R"))
metadata <- data.frame(
  sample_cor_NoD4 = colnames(Filt_RMG0_RNA_log2cpm_NoD4),
  species_cor_NoD4 = species_NoD4,
  timepoint_cor_NoD4 = time_NoD4
)
ann_colors_NoD4 <- list(
  timepoint_cor_NoD4 = c(
    "D0" = "#883268",   # Purple
    "D2" = "#3E7274",  # blue
    "D5" = "#94C47D",  # Green
    "D15" = "#C03830",  # red
    "D30" = "#830C05",  # dark red
    "D0R" = "#883268",  # pink
    "D2R" = "#3E7274",  # teal
    "D5R" = "#94C47D",  # bright green
    "D30R" = "#830C05"  # bright red
  ),
  species_cor_NoD4 = c(
    "H" = "#171717",  # black
    "C" = "#17171717",   # light grey
    "HR" = "#171717B0"#Dark Grey
  )
)
rownames(metadata) <- metadata$sample_cor_NoD4
```


```{r Graphing_PCA_RNA-Seq_RowMeans_Filtering_NoDay4,fig.height=4,fig.width=9}
print(
  ggplot(pca_NoD4_meta, aes(x = PC1, y = PC2, color = timepoint, shape = species)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_text_repel(aes(label = sample), size = 3, max.overlaps = 100) +
  theme_minimal() +
  labs(title ="       PCA of log2CPM \n(RowMeans>0-NoDay4)",
       x = paste0("PC1 (", round(summary(pca_NoD4)$importance[2, 1] * 100, 1), "%)"),
       y = paste0("PC2 (", round(summary(pca_NoD4)$importance[2, 2] * 100, 1), "%)"))
)

```

```{r Graphing_Correlation_HeatMap_RNA-Seq_RowMeans_Filtering_noDay4,fig.height=10,fig.width=10}
print(
  pheatmap(cor_Filt_RMG0_RNA_log2cpm_NoD4,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = metadata[, c("species_cor_NoD4", "timepoint_cor_NoD4")],
         annotation_colors = ann_colors_NoD4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Pearson) \n (log2CPM-RowMeans>0-NoDay4)")
)
```
