---
title: "RNA_PCA_Symbol"
output: html_document
date: "2026-01-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Setting_Up_Enviroment, results="hide"}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")

# BiocManager::install("SummarizedExperiment")

ann_colors_No4 <- readRDS("data/QC/ann_colors_no4.RDS")
RNA_Metadata_No4 <- readRDS("data/QC/RNA_Metatdata_No4.RDS")
Filt_RMG0_RNA_log2cpm_NoD4 <- readRDS("data/QC/Symbol/Filt_RMGO_RNA_log2cpm_NoD4_unique.RDS")

```


```{r RNA_PCA_RMG0_NoD4}
prcomp_Filt_RMG0_RNA_log2cpm_NoD4 <- prcomp(t(Filt_RMG0_RNA_log2cpm_NoD4), scale=FALSE, center = TRUE)
prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta <- prcomp_Filt_RMG0_RNA_log2cpm_NoD4$x %>% cbind(., RNA_Metadata_No4)
prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta$Timepoint <- factor(prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta$Timepoint, levels = c("Day0","Day2","Day5","Day15","Day30"))
prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta$Species <- factor(prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta$Species, levels = c("H","C"))
#PCA checks
#k=1

ggplot2::autoplot(prcomp_Filt_RMG0_RNA_log2cpm_NoD4 ,
                  data = prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=1,
                  y=2) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = RNA_Metadata_No4$Individual,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("Filtered RMG0 RNA Log2CPM")

# saveRDS(prcomp_Filt_RMG0_RNA_log2cpm_NoD4,"data/QC/Symbol/prcomp_Filt_RMG0_RNA_log2cpm_NoD4.RDS")
# saveRDS(prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta,"data/QC/Symbol/prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta.RDS")

```


```{r RNA_PCA_RawData_PCA Plot,fig.height=4,fig.width=9}
ggplot(prcomp_Filt_RMG0_RNA_log2cpm_NoD4_meta, aes(x = PC1, y = PC2, color = Timepoint, shape = Species)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_text_repel(aes(label = SampleName), size = 3, max.overlaps = 100) +
  theme_minimal() +
  labs(title = "Filtered RMG0 No Day 4 PCA of log2CPM RNA-Seq Data",
       x = paste0("PC1 (", round(summary(prcomp_Filt_RMG0_RNA_log2cpm_NoD4)$importance[2, 1] * 100, 1), "%)"),
       y = paste0("PC2 (", round(summary(prcomp_Filt_RMG0_RNA_log2cpm_NoD4)$importance[2, 2] * 100, 1), "%)"))

```


