---
title: "RNA_CHDGene_Comp_Species"
output: html_document
date: "2026-01-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{r RNA_GWAS_SettingEnviroment, include=FALSE}
#Loading Libraries
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ggrepel)
library(biomaRt)
library(tidyverse)
library(readxl)
library(readr)
library(reshape2)
library(circlize)
library(grid)
library(stringr)
library(org.Hs.eg.db)
library(GO.db)
library(AnnotationDbi)
library(gprofiler2)
library(purrr)
# install.packages("GO.db")
# BiocManager::install("GO.db")

#Loading R Objects
# quadrant_gene_lists <- readRDS("data/DGE/quadrant_gene_lists_DayBefore.RDS")
chdgene_table <- readRDS("data/DGE/chdgene_table.RDS")
all_genes <- readRDS("data/DGE/Species/ExpressedGenes.RDS")
deg_genes <- readRDS("data/DGE/Species/DEG_AtLeastOne.RDS")
RNA_sets <- readRDS("data/DGE/Species/RNA_DEG_Non_DEG_sets_05.RDS")
TopTable_RNA_All <- readRDS("data/DGE/Species/TopTable_RNA_all.RDS")
ensembl_to_hgnc <- readRDS("data/DGE/Species/Ensembl_to_HGNC_mapping.RDS")
```

```{r Volcano_Plot_Function. include=FALSE}
generate_volcano_plot <- function(toptable, title) {
  
  # #check for entrezid 
  # if(!"Entrez_ID" %in% colnames(toptable)) stop("Entrez_ID col not present")
  # 
  #make significance labels
  
  toptable <- toptable %>% 
    mutate(Significance = case_when(
      logFC > 0 & adj.P.Val < 0.05 ~ "Upregulated",
      logFC < 0 & adj.P.Val < 0.05 ~ "Downregulated",
      TRUE  ~ "Not Significant"
    ))
  
  #factor significance
  toptable$Significance <- factor(
    toptable$Significance, 
    levels = c("Upregulated", 
               "Not Significant", 
               "Downregulated")
  )
  
  #count genes in each category
  upgenes <- sum(toptable$Significance == "Upregulated")
  nsgenes <- sum(toptable$Significance == "Not Significant")
  downgenes <- sum(toptable$Significance == "Downregulated")
  
  
  #labels for legend
  legend_lab <- c(
    paste0("Upregulated: ", upgenes),
    paste0("Not Significant: ", nsgenes),
    paste0("Downregulated: ", downgenes)
  )
  
  #colors 
  color_map <- c("Upregulated" = "blue",
                 "Not Significant" = "grey30",
                 "Downregulated" = "red")
  
  #generate volcano plots
  p <- ggplot(toptable, aes(x = logFC, 
                            y = -log10(P.Value),
                            color = Significance)) +
    geom_point_rast(alpha = 0.8, size = 3) +
    scale_color_manual(values = color_map, 
                       labels = legend_lab,
                       breaks = c("Upregulated",
                                  "Not Significant", 
                                  "Downregulated"))  +
    xlim(-20,20) +
    labs(title = title, 
         x = expression("log"[2]*"FC"),
         y = expression("-log"[10]*"p-value")) +
    # theme_custom() +
    theme(legend.position = "right")
  
  return(p)
}


```

```{r Volcano_Plot_chdgene_Function, include=FALSE}
generate_volcano_plot_CHDGene <- function(toptable, title, chdgene_genes = NULL) {
  
  # Determine significance
  toptable <- toptable %>% 
    mutate(Significance = case_when(
      logFC > 0 & adj.P.Val < 0.05 ~ "Upregulated",
      logFC < 0 & adj.P.Val < 0.05 ~ "Downregulated",
      TRUE  ~ "Not Significant"
    ))

  toptable$Significance <- factor(
    toptable$Significance, 
    levels = c("Upregulated", "Not Significant", "Downregulated")
  )

  # Mark GWAS hits
  toptable <- toptable %>%
    mutate(highlight = if_else(Gene %in% chdgene_genes, TRUE, FALSE))

  # Split data for layers
  df_non_chdgene <- toptable %>% filter(!highlight)
  df_chdgene     <- toptable %>% filter(highlight)

  # Colors for significance
  color_map <- c(
    "Upregulated" = "blue",
    "Not Significant" = "grey30",
    "Downregulated" = "red"
  )

  p <- ggplot() +
    # Non-chdgene points
    geom_point(data = df_non_chdgene,
               aes(x = logFC, y = -log10(P.Value), color = Significance),
               alpha = 0.8, size = 3) +
    scale_color_manual(values = color_map) +

    # GWAS points on top with outline
    geom_point(data = df_chdgene,
               aes(x = logFC, y = -log10(P.Value), fill = Significance),
               shape = 21, color = "limegreen", size = 4, stroke = 1.5) +

    # Optional: label chdgene genes
    # geom_text_repel(data = df_gwas,
    #                 aes(x = logFC, y = -log10(P.Value), label = Gene),
    #                 size = 3, fontface = "bold", color = "black", max.overlaps = 20) +

    xlim(-20, 20) +
    labs(title = title, 
         x = expression("log"[2]*"FC"),
         y = expression("-log"[10]*"p-value")) +
    theme_bw() +
    theme(legend.position = "right") +
    guides(color = guide_legend(override.aes = list(size = 3)),
           fill = guide_legend(override.aes = list(size = 3)))

  return(p)
}

```

```{r RNA_CHDGene_Species_DataSets}
# #CHD Curated Gene List
# chdgene_table <- read.csv("C:/Users/jdhurley/Downloads/chdgene_table.csv")
# # saveRDS(chdgene_table,"data/DGE/chdgene_table.RDS")
# 
# # Make a copy to be safe
chdgene_table_copy <- chdgene_table
# 
# # Check
# colnames(chdgene_table_copy)
# 
# #ENSEMBL ID
# all_ensembl_ids <- unique(TopTable_RNA_All$Gene)
# 
# ensembl <- useMart(
#   "ensembl",
#   dataset = "hsapiens_gene_ensembl"
# )
# 
# ensembl_to_hgnc <- getBM(
#   attributes = c("ensembl_gene_id", "hgnc_symbol"),
#   filters = "ensembl_gene_id",
#   values = all_ensembl_ids,
#   mart = ensembl
# ) %>%
#   filter(hgnc_symbol != "") %>%
#   distinct()
# 
# saveRDS(
#   ensembl_to_hgnc,
#   "data/DGE/Species/Ensembl_to_HGNC_mapping.RDS"
# )

ensembl_to_hgnc <- readRDS("data/DGE/Species/Ensembl_to_HGNC_mapping.RDS")

# Loop through my data sets to overlap
known_genes <- chdgene_table_copy$Gene

CHD_overlap_results <- list()

for (day in names(RNA_sets)) {

  message("Processing ", day)

  DEG_Set <- unique(RNA_sets[[day]]$DEGs$Gene)
  Non_DEG_Set <- unique(RNA_sets[[day]]$NonDEGs$Gene)

  # ---- DEG overlaps ----
  DEG_Overlaps_symbols <- ensembl_to_hgnc$ensembl_gene_id[
    ensembl_to_hgnc$ensembl_gene_id %in% DEG_Set &
    ensembl_to_hgnc$hgnc_symbol %in% known_genes 
  ]

  # ---- Non-DEG overlaps ----
  Non_DEG_Overlaps_symbols <- ensembl_to_hgnc$ensembl_gene_id[
    ensembl_to_hgnc$ensembl_gene_id %in% Non_DEG_Set &
    ensembl_to_hgnc$hgnc_symbol %in% known_genes
  ]

  CHD_overlap_results[[day]] <- list(
    DEG_CHD_Genes = unique(DEG_Overlaps_symbols),
    NonDEG_CHD_Genes = unique(Non_DEG_Overlaps_symbols)
  )

  saveRDS(
    unique(DEG_Overlaps_symbols),
    paste0("data/DGE/Species/", day, "_DEG_CHDGenes.RDS")
  )

  saveRDS(
    unique(Non_DEG_Overlaps_symbols),
    paste0("data/DGE/Species/", day, "_NonDEG_CHDGenes.RDS")
  )
}

```

```{r RNA_CHDGene_Species_DataSets_Significance}

# Create the table
Day0_DEGs_CHD_ChiSq  <- matrix(c(58,(6569-58),106,(8269-106)), nrow = 2, byrow = TRUE)
rownames(Day0_DEGs_CHD_ChiSq) <- c("Day0 DEGs", "Day0 NonDEGs")
colnames(Day0_DEGs_CHD_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day0_DEGs_CHD_ChiSq)

# Create the table
Day2_DEGs_CHD_ChiSq  <- matrix(c(27,(4094-27),137,(10744-137)), nrow = 2, byrow = TRUE)
rownames(Day2_DEGs_CHD_ChiSq) <- c("Day2 DEGs", "Day2 NonDEGs")
colnames(Day2_DEGs_CHD_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day2_DEGs_CHD_ChiSq)

# Create the table
Day5_DEGs_CHD_ChiSq <- matrix(c(33,(4154-33),131,(10648-131)), nrow = 2, byrow = TRUE)
rownames(Day5_DEGs_CHD_ChiSq) <- c("Day5 DEGs", "Day5 NonDEGs")
colnames(Day5_DEGs_CHD_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day5_DEGs_CHD_ChiSq)

# Create the table
Day15_DEGs_CHD_ChiSq  <- matrix(c(56,(5070-56),108,(9768-108)), nrow = 2, byrow = TRUE)
rownames(Day15_DEGs_CHD_ChiSq) <- c("Day15 DEGs", "Day15 NonDEGs")
colnames(Day15_DEGs_CHD_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day15_DEGs_CHD_ChiSq)

# Create the table
Day30_DEGs_CHD_ChiSq  <- matrix(c(59,(5990-59),105,(8848-105)), nrow = 2, byrow = TRUE)
rownames(Day30_DEGs_CHD_ChiSq) <- c("Day30 DEGs", "Day30 NonDEGs")
colnames(Day30_DEGs_CHD_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day30_DEGs_CHD_ChiSq)
```


```{r RNA_CHDGene_Species_Barplot}
df <- data.frame(
  Day = c("Day0","Day0","Day2","Day2","Day5","Day5","Day15","Day15","Day30","Day30"),
  Status = c("DEG","NonDEG","DEG","NonDEG","DEG","NonDEG","DEG","NonDEG","DEG","NonDEG"),
  Cond = c("Day0_DEG","Day0_NonDEG","Day2_DEG","Day2_NonDEG","Day5_DEG","Day5_NonDEG","Day15_DEG","Day15_NonDEG","Day30_DEG","Day30_NonDEG"),
  CHDGene = c(58,106,27,137,33,131,56,108,59,105),
  Non_CHDGene = c(6511,8163,4067,10607,4121,10517,5014,9660,5931,8743)
)

# Convert to long format for ggplot
df_long <- df %>%
  pivot_longer(cols = c(CHDGene, Non_CHDGene),
               names_to = "Type",
               values_to = "Count") %>%
  group_by(Cond) %>%
  mutate(Proportion = Count / sum(Count))  # calculate proportions

df_long$Cond <- factor(df_long$Cond, levels = c("Day0_DEG","Day0_NonDEG","Day2_DEG","Day2_NonDEG","Day5_DEG","Day5_NonDEG","Day15_DEG","Day15_NonDEG","Day30_DEG","Day30_NonDEG"), ordered = TRUE)

ggplot(df_long, aes(x = Cond, y = Proportion, fill = Type)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("DEGs" = "#E41A1C", "CHDGene" = "#377EB8")) +
  labs(y = "Proportion", x = "Cond", fill = "",title = "Overlaps of CHD Genes by Day") +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
  )

```

```{r RNA_CHDGene_Species_LogFoldChange}
median_all_df <- TopTable_RNA_All %>%
  group_by(Comparisons) %>%
  summarise(
    median_logFC = median(logFC, na.rm = TRUE),
    .groups = "drop"
  )

gene_set <- chdgene_table$Gene

gene_vector <- ensembl_to_hgnc %>% 
  dplyr::filter(hgnc_symbol %in% gene_set) %>% 
  dplyr::pull(ensembl_gene_id)

TopTable_Filt <- TopTable_RNA_All %>% 
  dplyr::filter(Gene %in% gene_vector) %>% 
  dplyr::mutate(
    Comparisons = factor(
      Comparisons,
      levels = c("HC_D0", "HC_D2", "HC_D5", "HC_D15", "HC_D30")
    )
  )

TopTable_Filt <- TopTable_Filt %>%
  rowwise() %>%
  mutate(
    isDEG = Gene %in% RNA_sets[[Comparisons]]$DEGs$Gene
  ) %>%
  ungroup()


# Determine bottom-left coordinates
x_min <- min(as.numeric(TopTable_Filt$Comparisons))  # first comparison
y_min <- min(TopTable_Filt$logFC, na.rm = TRUE) - 0.5     # lowest logFC among CHD genes

ggplot(TopTable_Filt, aes(x = Comparisons, y = logFC, group = Gene)) +
  geom_line(alpha = 0.25) +
  geom_point(aes(color = isDEG), size = 2, alpha = 0.8) +
  scale_color_manual(values = c("FALSE" = "grey70", "TRUE" = "dodgerblue")) +

  # Median line (all genes)
  geom_line(
    data = median_all_df,
    aes(x = Comparisons, y = median_logFC, group = 1),
    inherit.aes = FALSE,
    linewidth = 1.6,
    color = "firebrick"
  ) +
  geom_point(
    data = TopTable_Filt %>% filter(!isDEG),
    aes(x = Comparisons, y = logFC),
    color = "grey70",
    size = 2,
    alpha = 0.8
  ) +

  # DEG points on top (blue)
  geom_point(
    data = TopTable_Filt %>% filter(isDEG),
    aes(x = Comparisons, y = logFC),
    color = "dodgerblue",
    size = 2,
    alpha = 0.8
  ) +
  # Median label bottom-left
  geom_text(
    data = data.frame(
      x = 1,
      y = min(TopTable_Filt$logFC, na.rm = TRUE) - 0.5
    ),
    aes(x = x, y = y, label = "Median (all genes)"),
    inherit.aes = FALSE,
    color = "firebrick",
    size = 4
  ) +

  geom_hline(yintercept = 0, linetype = "dashed") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    x = "Comparison",
    y = "log2 Fold Change",
    color = "DEG",
    title = "CHD gene trajectories with DEGs highlighted"
  )

```
```{r}

gene_categories <- TopTable_Filt %>%
  group_by(Gene) %>%
  summarize(
    n_comparisons = n(),
    n_DEG = sum(isDEG),
    .groups = "drop"
  ) %>%
  mutate(
    category = case_when(
      n_DEG == n_comparisons ~ "DEG in all comparisons",
      n_DEG == 0            ~ "Non-DEG in all comparisons",
      TRUE                   ~ "Other"
    )
  )

TopTable_Filt <- TopTable_Filt %>%
  left_join(gene_categories %>% 
  dplyr::select(Gene, category), by = "Gene")

TopTable_Filt %>%
  group_by(category) %>%
  summarize(n_genes = n_distinct(Gene)) %>%
  arrange(desc(n_genes))

```



```{r RNA_CHDGene_Species_Barplot_DGE_Venn}
df <- data.frame(
  Day = c("Day0-Only", "Day2-Only", "Day5-Only", "Day15-Only", "Day30-Only","Shared_All"),
  CHDGene = c(16,6,6,14,18,8),
  Non_CHDGene = c(1719,441,499,602,1217,1884)
)

# Convert to long format for ggplot
df_long <- df %>%
  pivot_longer(cols = c(CHDGene, Non_CHDGene),
               names_to = "Type",
               values_to = "Count") %>%
  group_by(Day) %>%
  mutate(Proportion = Count / sum(Count))  # calculate proportions

df_long$Day <- factor(df_long$Day, levels = c("Day0-Only", "Day2-Only", "Day5-Only", "Day15-Only", "Day30-Only","Shared_All"), ordered = TRUE)

ggplot(df_long, aes(x = Day, y = Proportion, fill = Type)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format()) +  # show % on y-axis
  scale_fill_manual(values = c("DEGs" = "#E41A1C", "CHDGene" = "#377EB8")) + # custom colors
  labs(y = "Proportion", x = "Day", fill = "",title = "Species DEGs overlaping CHD Gene
Based on DGE Venn Overlaps") +
  theme_minimal(base_size = 14)
```

```{r RNA_CHDGene_Species_DataSets_Significance}
# Create the table
Day0_Only_DEGs_ChiSq <- matrix(c(16, 1719, 8, 1184), nrow = 2, byrow = TRUE)
rownames(Day0_Only_DEGs_ChiSq) <- c("Day0", "Day0-2-5-15-30")
colnames(Day0_Only_DEGs_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day0_Only_DEGs_ChiSq)

# Create the table
Day2_Only_DEGs_ChiSq <- matrix(c(6, 441, 8, 1184), nrow = 2, byrow = TRUE)
rownames(Day2_Only_DEGs_ChiSq) <- c("Day2", "Day0-2-5-15-30")
colnames(Day2_Only_DEGs_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day2_Only_DEGs_ChiSq)

# Create the table
Day5_Only_DEGs_ChiSq <- matrix(c(6,499, 8, 1184), nrow = 2, byrow = TRUE)
rownames(Day5_Only_DEGs_ChiSq) <- c("Day5", "Day0-2-5-15-30")
colnames(Day5_Only_DEGs_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day5_Only_DEGs_ChiSq)

# Create the table
Day15_Only_DEGs_ChiSq <- matrix(c(14,602, 8, 1184), nrow = 2, byrow = TRUE)
rownames(Day15_Only_DEGs_ChiSq) <- c("Day15", "Day0-2-5-15-30")
colnames(Day15_Only_DEGs_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day15_Only_DEGs_ChiSq)

# Create the table
Day30_Only_DEGs_ChiSq <- matrix(c(18,1217, 8, 1184), nrow = 2, byrow = TRUE)
rownames(Day30_Only_DEGs_ChiSq) <- c("Day30", "Day0-2-5-15-30")
colnames(Day30_Only_DEGs_ChiSq) <- c("CHDGene", "Non-CHDGene")

# Run chi-square test
chisq.test(Day30_Only_DEGs_ChiSq)
```

```{r Updating Website, eval = FALSE}

# git -> commit all changes
# git -> push
# wflow_publish("analysis/RNA_CHDGene_Comp_Species.Rmd")

```
