---
title: "RNA_Cormotif_Species"
output:
  html_document:
    toc: true
    toc_float: true
date: "2026-01-28"
---

```{r setup, include=FALSE, warning = FALSE, message=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png", "pdf")
)
```

# RNA Cormotif

## Setting up the environment

### Loading libraries
```{r Setting_Up_Enviroment, warning=FALSE, message=FALSE}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")
library("clusterProfiler")
library("enrichplot")
library("gprofiler2")
library("Cormotif")

# BiocManager::install("SummarizedExperiment")

#Loading objects used in this workbook
ann_colors <- readRDS("data/Raw_Data/concat/ann_colors.RDS")
ann_colors_No4 <- readRDS("data/QC/concat/ann_colors_No4.RDS")
ann_colors_No5 <-readRDS("data/QC/concat/ann_colors_No5.RDS")

```

### Defining Functions
```{r Load_CorMotif_Functions, warning=FALSE, message=FALSE}
#Run the Function corMotifcustom.R

#Check_Overlap Function

check_overlap <- function(list_of_lists) {
  # create empty list to store results
  overlap_results <- list()
  
  # loop over each cluster
  for (i in seq_along(list_of_lists)) {
    cluster_name <- names(list_of_lists)[i]
    genes_i <- list_of_lists[[i]]
    
    # compare to all other clusters
    overlaps <- sapply(seq_along(list_of_lists), function(j) {
      if (i == j) return(NA)  # skip self
      genes_j <- list_of_lists[[j]]
      length(intersect(genes_i, genes_j))  # count of overlapping genes
    })
    names(overlaps) <- names(list_of_lists)
    
    overlap_results[[cluster_name]] <- overlaps
  }
  
  return(overlap_results)
}

#FC_Plot_Function_sig

plot_cluster_fc_sig <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day25","H_Day515","H_Day1530","C_Day02","C_Day25","C_Day515","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # Global test across comparisons
  kw <- kruskal.test(logFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}

#FC_Plot_Function_sig_species

plot_cluster_fc_sig_species <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HvC_Day0","HvC_Day2","HvC_Day5","HvC_Day15","HvC_Day30")))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # Global test across comparisons
  kw <- kruskal.test(logFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}

#AbsFC_Plot_Function

plot_cluster_absfc <- function(gene_vector, cluster_name, top_table) {
  
  # Filter TopTable for the genes in this cluster
  df <- top_table %>% dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HC_D0","HC_D2","HC_D5","HC_D15","HC_D30"
    )))
  
  # Optional: print dimensions and unique genes
  cat(cluster_name, ":", dim(df)[1], "rows,", length(unique(df$Gene)), "unique genes\n")
  
  # Create boxplot
  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    guides(fill = guide_legend(title = "Comparisons")) +
    theme_bw() +
    xlab(" ") +
    ylab("AbsFC") +
    ggtitle(paste0(cluster_name, " RNA AbsFC Comparisons")) +
    theme(
      plot.title = element_text(size = rel(1.5), hjust = 0.5),
      axis.title = element_text(size = 15, colour = "black"),
      strip.background = element_rect(fill = "#CAD899"),
      axis.text.x = element_text(size = 8, colour = "white", angle = 15),
      strip.text.x = element_text(size = 12, colour = "black", face = "bold")
    )
  
  return(p)
}

#AbsFC_Plot_Function_sig

plot_cluster_absfc_sig <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day25","H_Day515","H_Day1530","C_Day02","C_Day25","C_Day515","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")
  
  # Global test across comparisons
  kw <- kruskal.test(AbsFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$AbsFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("AbslogFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA AbsFC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}

#AbsFC_Plot_Function_sig_species

plot_cluster_absfc_sig_species <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "HvC_Day0","HvC_Day2","HvC_Day5","HvC_Day15","HvC_Day30")))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # Global test across comparisons
  kw <- kruskal.test(logFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("abslogFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}


```

## No Day 4

### Modeling Filtered Only on Laptop

#### Data Preparation
```{r RNA-Seq_No4_Species_modeling_computer_dataset,fig.height=8,fig.width=15}
counts <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_fc_No4.RDS")
metadata <- readRDS("data/Raw_Data/concat/RNA_Metadata_No4_NoRep.RDS")

counts_norep <- counts %>%
  dplyr::select(-(contains("R")))

log2cpm <- cpm(counts_norep, log=TRUE) 

# --- Align metadata and log2cpm
metadata <- metadata[match(colnames(log2cpm), metadata$SampleName), ]

# --- Build group and comp IDs from metadata ---
metadata$group <- paste(metadata$Species, metadata$Timepoint, sep = "_")

time_order <- c("Day0", "Day2","Day5","Day15","Day30")
species_order <- c("H","C")

group_levels <- c(paste("H",time_order,sep = "_"), paste("C",time_order, sep = "_"))

metadata$group <- factor(metadata$group, levels = group_levels, ordered = TRUE)

groupid <- as.numeric(metadata$group)

# Build Human vs Chimp same-timepoint comparisons
make_species_comparison <- function(levels_vec, times) {
  h_idx <- match(paste("H", times, sep = "_"), levels_vec)
  c_idx <- match(paste("C", times, sep = "_"), levels_vec)

  keep <- !is.na(h_idx) & !is.na(c_idx)

  cbind(h_idx[keep], c_idx[keep])
}

compid <- make_species_comparison(
  levels(metadata$group),
  time_order
)

colnames(compid) <- c("Human", "Chimp")
rownames(compid) <- paste0(time_order, "_H_vs_C")

compid

#Model Fitting

# # Run model
# set.seed(8)
# motif.fitted <- cormotiffit(
#   exprs = log2cpm,
#   groupid = groupid,
#   compid = compid,
#   K = 1:20,
#   max.iter = 2000,
#   runtype = "logCPM"
# )
# 
# saveRDS(motif.fitted,"data/Cormotif/Species/SpeciesMotif_logcpm_G1_SpTp_No4_NoRep_Computer.RDS")
```

#### Graphing

```{r RNA-Seq_No4_Species_modeling_computer_plot,fig.height=8,fig.width=15}
motif.fitted <- readRDS("data/Cormotif/Species/SpeciesMotif_logcpm_G1_SpTp_No4_NoRep_Computer.RDS")

plotIC(motif.fitted)
plotMotif(motif.fitted)
cols <- gray(seq(1, 0, length.out = 6))

legend(
  "topright",
  legend = seq(0, 1, length.out = 6),
  fill = cols,
  border = "black",
  title = "Posterior probability")


```



### Filtered Only on TACC

#### RScript
```{r RNA-Seq_No4_Species_TACC_RScript,fig.height=8,fig.width=15}

# set.seed(8)
# print(runif(5))
# print(runif(5))
# 
# # --- Load required libraries ---
# suppressPackageStartupMessages({
#         library(edgeR)
#         library(BiocParallel)
#         library(Biobase)
#         library(limma)
#         library(Rfast)
# })
# 
# # --- Load custom function ---
# source("cormotif_function.R")
# 
# # --- Load data ---
# load("Filt_logcpm_G1_SpTp_RNA_log2cpm_No4_NoRep.RData")
# 
# load("RNA_Metadata_No4_NoRep.RData")
# 
# # --- Define Variables ---
# log2cpm <- Filt_logcpm_G1_SpTp_RNA_log2cpm_No4_NoRep
# metadata <- RNA_Metadata_No4_NoRep
# 
# # --- Align metadata and log2cpm
# metadata <- metadata[match(colnames(log2cpm), metadata$SampleName), ]
# 
# # --- Build group and comp IDs from metadata ---
# metadata$group <- paste(metadata$Species, metadata$Timepoint, sep = "_")
# 
# time_order <- c("Day0", "Day2","Day5","Day15","Day30")
# species_order <- c("H","C")
# 
# group_levels <- c(paste("H",time_order,sep = "_"), paste("C",time_order, sep = "_"))
# 
# metadata$group <- factor(metadata$group, levels = group_levels, ordered = TRUE)
# 
# groupid <- as.numeric(metadata$group)
# 
# # Build Human vs Chimp same-timepoint comparisons
# make_species_comparison <- function(levels_vec, times) {
#   h_idx <- match(paste("H", times, sep = "_"), levels_vec)
#   c_idx <- match(paste("C", times, sep = "_"), levels_vec)
# 
#   keep <- !is.na(h_idx) & !is.na(c_idx)
# 
#   cbind(h_idx[keep], c_idx[keep])
# }
# 
# compid <- make_species_comparison(
#   levels(metadata$group),
#   time_order
# )
# 
# colnames(compid) <- c("Human", "Chimp")
# rownames(compid) <- paste0(time_order, "_H_vs_C")
# 
# 
# # ==============================
# # Run model
# # ==============================
# cat("Fitting CorMotif...\n")
# 
# set.seed(8)
# motif.fitted <- cormotiffit(
#   exprs = log2cpm,
#   groupid = groupid,
#   compid = compid,
#   K = 1:20,
#   max.iter = 2000,
#   runtype = "logCPM"
# )
# 
# saveRDS(motif.fitted,
#         file = paste0("CorMotif_k1_k20_No4_seed8_Species_TACC.rds"))
# 
# pdf(paste0("CorMotif_k1_k20_plots_No4_seed8_Species_TACC.pdf"))
# plotIC(motif.fitted)
# plotMotif(motif.fitted)
# dev.off()
# 
# topgenelist <- generank(motif.fitted$bestmotif$p.post)
# write.csv(topgenelist,
#           paste0("CorMotif_top_genes_No4_seed8_Sepcies_TACC.csv"),
#           row.names = TRUE)
# 
# cat(">>> Finished No4 seed:8")

```

#### Graphing

```{r RNA-Seq_No4_Species_TACC_Plot,fig.height=8,fig.width=15}
motif.fitted <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_seed8_Species_TACC.rds")

plotIC(motif.fitted)
plotMotif(motif.fitted)
cols <- gray(seq(1, 0, length.out = 6))

legend(
  "topright",
  legend = seq(0, 1, length.out = 6),
  fill = cols,
  border = "black",
  title = "Posterior probability")


```

#### PPost

```{r RNA-Seq_No4_Species_TACC_PPost}
motif.fitted <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_seed8_Species_TACC.rds")

counts <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_fc_No4.RDS")

counts_norep <- counts %>%
  dplyr::select(-(contains("R")))

log2cpm <- cpm(counts_norep, log=TRUE) 

motif.fit <- motif.fitted
log2cpm <- log2cpm

TopTable <- readRDS("data/DGE/TopTable_Filt_logcpm_G1_SpTp_RNA_fc_NoRep_No4.RDS")

#extract the posterior probability that these genes belong to motifs
gene_prob_ppost <- motif.fit$bestmotif$p.post
rownames(gene_prob_ppost) <- rownames(log2cpm)
saveRDS(gene_prob_ppost,"data/Cormotif/Species/RNA_gene_prob_ppost_Species.RDS")

#assign each gene to a motif with max post prob
assigned_motifs <- apply(gene_prob_ppost, 1, which.max)
max_probs <- apply(gene_prob_ppost, 1, max)

#combine these into a dataframe - motif assigned genes (p.post)
motif_assignment_df <- gene_prob_ppost %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>%
  mutate(
    Assigned_Motif = assigned_motifs[Gene],
    Max_Probability = max_probs[Gene]
  )

#make some histograms of the unfiltered data from Cormotif p.post

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V1))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V1")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V2))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V2")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V3))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V3")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V4))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V4")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V5))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V5")

```

#### Cluster Assignments

```{r RNA-Seq_No4_Species_TACC_CluserAssign}
motif.fit <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_seed8_Species_TACC.rds")

counts <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_fc_No4.RDS")

counts_norep <- counts %>%
  dplyr::select(-(contains("R")))

log2cpm <- cpm(counts_norep, log=TRUE) 

motif.fit <- motif.fitted
log2cpm <- log2cpm

TopTable <- readRDS("data/DGE/TopTable_Filt_logcpm_G1_SpTp_RNA_fc_NoRep_No4.RDS")

# Extract cluster probabilities
motif_prob <- motif.fit$bestmotif$clustlike
rownames(motif_prob) <- rownames(gene_prob_ppost)

saveRDS(
  motif_prob,
  "data/Cormotif/Species/RNA_motif_prob_Species.RDS"
)

# Keep species comparisons only
TopTable <- TopTable %>%
  filter(
    Comparisons %in% c(
      "HvC_Day0",
      "HvC_Day2",
      "HvC_Day5",
      "HvC_Day15",
      "HvC_Day30"
    )
  )

# Define clusters
clust1_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 > 0.59, V2 < 0.5, V3 < 0.5, V4 < 0.5, V5 < 0.5) %>%
  rownames()

clust2_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 < 0.59, V2 > 0.5, V3 < 0.5, V4 < 0.5, V5 < 0.5) %>%
  rownames()

clust3_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 < 0.59, V2 < 0.5, V3 > 0.5, V4 < 0.5, V5 < 0.5) %>%
  rownames()

clust4_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 < 0.59, V2 < 0.5, V3 < 0.5, V4 > 0.5, V5 < 0.5) %>%
  rownames()

clust5_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 < 0.59, V2 < 0.5, V3 < 0.5, V4 < 0.5, V5 > 0.5) %>%
  rownames()

# Cluster list
clust_names_list <- list(
  clust1 = clust1_RNA,
  clust2 = clust2_RNA,
  clust3 = clust3_RNA,
  clust4 = clust4_RNA,
  clust5 = clust5_RNA
)

# Check sizes
sapply(clust_names_list, length)

# Overlap
overlap_matrix <- check_overlap(clust_names_list)
print(overlap_matrix)

TopTable$AbsFC <- abs(TopTable$logFC)

# FC plots
cluster_plots <- lapply(names(clust_names_list), function(clust_name) {
  plot_cluster_fc_sig_species(
    clust_names_list[[clust_name]],
    clust_name,
    TopTable
  )
})

for (p in cluster_plots) {
  if (!is.null(p)) print(p)
}

# AbsFC plots
cluster_plots <- lapply(names(clust_names_list), function(clust_name) {
  plot_cluster_absfc_sig_species(
    clust_names_list[[clust_name]],
    clust_name,
    TopTable
  )
})

for (p in cluster_plots) {
  if (!is.null(p)) print(p)
}


```

```{r RNA-Seq_No4_Species_TACC_ClusterOverlapChecks}

clust_names_list <- list(
  clust1_RNA,
  clust2_RNA,
  clust3_RNA,
  clust4_RNA,
  clust5_RNA
)

names(clust_names_list) <- paste0("clust", 1:5)

print(overlap_matirx <- check_overlap(clust_names_list))

```

#### GoProfiler2

```{r RNA-Seq_No4_Species_TACC_GProfiler2}

motif.fit <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_seed8_Species_TACC.rds")

TopTable <- readRDS("data/DGE/TopTable_Filt_logcpm_G1_SpTp_RNA_fc_NoRep_No4.RDS")

all_genes <- unique(TopTable$Gene)


# convert_to_entrez_df <- function(genes) {
# 
#   genes <- sub("\\..*", "", genes)
# 
#   bitr(
#     genes,
#     fromType = "ENSEMBL",
#     toType   = "ENTREZID",
#     OrgDb    = org.Hs.eg.db
#   ) %>% distinct()
# }
# 
# background_entrez <- convert_to_entrez_df(all_genes)$ENTREZID
# 
# gost_results <- setNames(
# 
#   lapply(names(clust_names_list), function(clust_name) {
# 
#     genes <- clust_names_list[[clust_name]]
# 
#     entrez_df <- convert_to_entrez_df(genes)
# 
#     if (nrow(entrez_df) == 0) return(NULL)
# 
#     gost(
#       query = entrez_df$ENTREZID,
# 
#       organism = "hsapiens",
# 
#       significant = FALSE,
#       ordered_query = FALSE,         # TRUE only if ranked
#       domain_scope = "custom",
# 
#       measure_underrepresentation = FALSE,
#       evcodes = FALSE,
# 
#       numeric_ns = "ENTREZGENE",
# 
#       user_threshold = 0.05,
#       correction_method = "fdr",
# 
#       custom_bg = background_entrez,
# 
#       sources = c("GO:BP", "KEGG")
#     )
#   }),
# 
#   names(clust_names_list)
# )
# 
# saveRDS(gost_results, "data/Cormotif/Species/SpeciesGo_logcpm_G1_SpTp_No4_NoRep.RDS")
# 
# gost_results <- readRDS("data/Cormotif/Species/SpeciesGo_logcpm_G1_SpTp_No4_NoRep.RDS")
# 
# gost_combined <- do.call(rbind, lapply(names(gost_results), function(clust_name) {
# 
#   res <- gost_results[[clust_name]]
# 
#   if (is.null(res)) return(NULL)
# 
#   df <- res$result
#   df$Cluster <- clust_name
#   df
# }))
# 
# saveRDS(gost_combined, "data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.RDS")
# 
# gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.RDS")
# 
# gost_export <- gost_combined
# 
# gost_export[] <- lapply(gost_export, function(col) {
# 
#   if (is.list(col)) {
#     sapply(col, paste, collapse = ";")
#   } else {
#     col
#   }
# 
# })
# 
# write.csv(gost_export,
#           "data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.csv",
#           row.names = FALSE)

```

##### Plotting

###### GO:BP
```{r RNA-Seq_No4_Species_TACC_GProfiler_GO,fig.height=3, fig.width=7}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.RDS")

top_terms <- gost_combined %>%
  filter(source == "GO:BP") %>%        # keep only BP terms
  group_by(Cluster) %>%
  slice_min(p_value, n = 10) %>%       # top 10 per cluster
  ungroup()

cluster_list <- split(top_terms, top_terms$Cluster)

library(ggplot2)

for (clust_name in names(cluster_list)) {
  
  df <- cluster_list[[clust_name]]
  
  p <- ggplot(df,
              aes(x = Cluster, y = term_name, fill = -log10(p_value))) +
    geom_tile(color = "white") +
    scale_fill_gradient(low = "grey90", high = "firebrick") +
    labs(fill = "-log10(p-value)",
         x = "Cluster",
         y = "GO Term") +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 8))
  
  print(p)   # display in RStudio
  
}

library(dplyr)
library(ggplot2)

top_terms <- gost_combined %>%
  filter(source == "GO:BP",
         p_value < 0.05) %>%
  group_by(Cluster) %>%
  slice_min(p_value, n = 3, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(
    Cluster_num = as.numeric(gsub("clust", "", Cluster)),
    term_label = paste0(Cluster, " : ", term_name)
  ) %>%
  arrange(desc(Cluster_num))

top_terms$term_label <- factor(
  top_terms$term_label,
  levels = rev(top_terms$term_label)
)

ggplot(top_terms,
       aes(x = 1,
           y = term_label,
           fill = -log10(p_value))) +
  geom_tile(color = "white", width = 0.8) +
  geom_text(aes(label = Cluster), size = 3) +
  scale_fill_gradient(low = "grey90", high = "firebrick") +
  labs(fill = "-log10(p-value)",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 8),
    panel.grid = element_blank()
  )
```



```{r RNA-Seq_No4_Species_TACC_GProfiler_Go_combined,fig.height=5}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.RDS")



library(dplyr)
library(tidyr)
library(ggplot2)

sig_thresh <- 0.05

# 1. For each cluster, keep significant terms and max 10 lowest p-values
top_sig_terms_per_cluster <- gost_combined %>%
  filter(source == "GO:BP") %>%
  group_by(Cluster) %>%
  filter(p_value < sig_thresh) %>%                    # keep only significant
  slice_min(order_by = p_value, n = 10, with_ties = FALSE) %>%  # max 10 per cluster
  ungroup()

# 2. Keep all unique terms across clusters
unique_terms <- unique(top_sig_terms_per_cluster$term_name)

# 3. Filter original gost_combined for these terms, retain p-values from all clusters
heatmap_data <- gost_combined %>%
  filter(source == "GO:BP", term_name %in% unique_terms) %>%
  mutate(logp = -log10(p_value)) %>%
  select(Cluster, term_name, logp)

# 4. Pivot to wide format for matrix-style heatmap
heatmap_wide <- heatmap_data %>%
  pivot_wider(names_from = Cluster, values_from = logp)

saveRDS(heatmap_wide, "data/Cormotif/Species/SpeciesGoWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesGoWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# 5. Convert to long format for ggplot
heatmap_long <- heatmap_wide %>%
  pivot_longer(cols = -term_name, names_to = "Cluster", values_to = "logp")

saveRDS(heatmap_long, "data/Cormotif/Species/SpeciesGoLong_logcpm_G1_SpTp_No4_NoRep.RDS")

heatmap_long <- readRDS("data/Cormotif/Species/SpeciesGoLong_logcpm_G1_SpTp_No4_NoRep.RDS")

# 6. Plot heatmap
ggplot(heatmap_long, aes(x = Cluster, y = term_name, fill = logp)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "grey90", high = "firebrick", na.value = "white") +
  labs(fill = "-log10(p-value)", x = "Cluster", y = "GO Term") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 6))

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesGoWide_logcpm_G1_SpTp_No4_NoRep.RDS")

library(dplyr)
library(tidyr)
library(pheatmap)

# Prepare the matrix for clustering: rows = terms, columns = clusters
heatmap_matrix <- heatmap_wide %>%
  column_to_rownames(var = "term_name") %>%   # rows = GO terms
  as.matrix()

# Optional: replace NAs with 0 for clustering (or leave NA if you want)
heatmap_matrix[is.na(heatmap_matrix)] <- 0

sig_matrix <- gost_combined %>%
  filter(
    source == "GO:BP",
    term_name %in% unique_terms
  ) %>%
  mutate(
    sig = ifelse(p_value < 0.05, "*", "")
  ) %>%
  select(Cluster, term_name, sig) %>%
  pivot_wider(
    names_from = Cluster,
    values_from = sig,
    values_fill = ""
  ) %>%
  column_to_rownames("term_name") %>%
  as.matrix()

# Create clustered heatmap
pheatmap(
  heatmap_matrix,
  color = colorRampPalette(c("grey90", "firebrick"))(100),
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = TRUE,
  fontsize_row = 6,
  fontsize_col = 8,
  main = "GO:BP Enrichment Heatmap",
  display_numbers = sig_matrix,
  number_color = "black"
)




```

###### KEG

```{r RNA-Seq_No4_Species_TACC_GProfiler_KEGG,fig.height=3, fig.width=7}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.RDS")

top_terms <- gost_combined %>%
  filter(source == "KEGG") %>%        # keep only BP terms
  group_by(Cluster) %>%
  slice_min(p_value, n = 10) %>%       # top 10 per cluster
  ungroup()

cluster_list <- split(top_terms, top_terms$Cluster)

library(ggplot2)

for (clust_name in names(cluster_list)) {
  
  df <- cluster_list[[clust_name]]
  
  p <- ggplot(df,
              aes(x = Cluster, y = term_name, fill = -log10(p_value))) +
    geom_tile(color = "white") +
    scale_fill_gradient(low = "grey90", high = "firebrick") +
    labs(fill = "-log10(p-value)",
         x = "Cluster",
         y = "KEGG Term") +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 8))
  
  print(p)   # display in RStudio
  
}

library(dplyr)
library(ggplot2)

top_terms <- gost_combined %>%
  filter(source == "KEGG",
         p_value < 0.05) %>%
  group_by(Cluster) %>%
  slice_min(p_value, n = 3, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(
    Cluster_num = as.numeric(gsub("clust", "", Cluster)),
    term_label = paste0(Cluster, " : ", term_name)
  ) %>%
  arrange(desc(Cluster_num))

top_terms$term_label <- factor(
  top_terms$term_label,
  levels = rev(top_terms$term_label)
)

ggplot(top_terms,
       aes(x = 1,
           y = term_label,
           fill = -log10(p_value))) +
  geom_tile(color = "white", width = 0.8) +
  geom_text(aes(label = Cluster), size = 3) +
  scale_fill_gradient(low = "grey90", high = "firebrick") +
  labs(fill = "-log10(p-value)",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 8),
    panel.grid = element_blank()
  )
```

```{r RNA-Seq_No4_Species_TACC_GProfiler_KEGG_combined,fig.height=5}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_No4_NoRep.RDS")



library(dplyr)
library(tidyr)
library(ggplot2)

sig_thresh <- 0.05

# 1. For each cluster, keep significant terms and max 10 lowest p-values
top_sig_terms_per_cluster <- gost_combined %>%
  filter(source == "KEGG") %>%
  group_by(Cluster) %>%
  filter(p_value < sig_thresh) %>%                    # keep only significant
  slice_min(order_by = p_value, n = 10, with_ties = FALSE) %>%  # max 10 per cluster
  ungroup()

# 2. Keep all unique terms across clusters
unique_terms <- unique(top_sig_terms_per_cluster$term_name)

# 3. Filter original gost_combined for these terms, retain p-values from all clusters
heatmap_data <- gost_combined %>%
  filter(source == "KEGG", term_name %in% unique_terms) %>%
  mutate(logp = -log10(p_value)) %>%
  select(Cluster, term_name, logp)

# 4. Pivot to wide format for matrix-style heatmap
heatmap_wide <- heatmap_data %>%
  pivot_wider(names_from = Cluster, values_from = logp)

saveRDS(heatmap_wide, "data/Cormotif/Species/SpeciesKEGGWide_logcpm_G1_SpTp_No4_NoRep.RDS")

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesKEGGWide_logcpm_G1_SpTp_No4_NoRep.RDS")

# 5. Convert to long format for ggplot
heatmap_long <- heatmap_wide %>%
  pivot_longer(cols = -term_name, names_to = "Cluster", values_to = "logp")

saveRDS(heatmap_long, "data/Cormotif/Species/SpeciesKEGGLong_logcpm_G1_SpTp_No4_NoRep.RDS")

heatmap_long <- readRDS("data/Cormotif/Species/SpeciesKEGGLong_logcpm_G1_SpTp_No4_NoRep.RDS")

# 6. Plot heatmap
ggplot(heatmap_long, aes(x = Cluster, y = term_name, fill = logp)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "grey90", high = "firebrick", na.value = "white") +
  labs(fill = "-log10(p-value)", x = "Cluster", y = "GO Term") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 6))

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesKEGGWide_logcpm_G1_SpTp_No4_NoRep.RDS")

library(dplyr)
library(tidyr)
library(pheatmap)

# Prepare the matrix for clustering: rows = terms, columns = clusters
heatmap_matrix <- heatmap_wide %>%
  column_to_rownames(var = "term_name") %>%   # rows = GO terms
  as.matrix()

# Optional: replace NAs with 0 for clustering (or leave NA if you want)
heatmap_matrix[is.na(heatmap_matrix)] <- 0

sig_matrix <- gost_combined %>%
  filter(
    source == "KEGG",
    term_name %in% unique_terms
  ) %>%
  mutate(
    sig = ifelse(p_value < 0.05, "*", "")
  ) %>%
  select(Cluster, term_name, sig) %>%
  pivot_wider(
    names_from = Cluster,
    values_from = sig,
    values_fill = ""
  ) %>%
  column_to_rownames("term_name") %>%
  as.matrix()

# Create clustered heatmap
pheatmap(
  heatmap_matrix,
  color = colorRampPalette(c("grey90", "firebrick"))(100),
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = TRUE,
  fontsize_row = 6,
  fontsize_col = 8,
  main = "KEGG Enrichment Heatmap",
  display_numbers = sig_matrix,
  number_color = "black"
)




```

### Filtered and TMM on TACC

#### RScript

```{r RNA-Seq_No4_TMM_Species_TACC_RScript,fig.height=8,fig.width=15}



# set.seed(8)
# print(runif(5))
# print(runif(5))
# 
# # --- Load required libraries ---
# suppressPackageStartupMessages({
#         library(edgeR)
#         library(BiocParallel)
#         library(Biobase)
#         library(limma)
#         library(Rfast)
# })
# 
# # --- Load custom function ---
# source("cormotif_function.R")
# 
# # --- Load data ---
# load("Filt_logcpm_G1_SpTp_RNA_log2cpm_No4_TMM.RData")
# 
# load("RNA_Metadata_No4_NoRep.RData")
# 
# # --- Define Variables ---
# log2cpm <- Filt_logcpm_G1_SpTp_RNA_log2cpm_No4_TMM
# metadata <- RNA_Metadata_No4_NoRep
# 
# # --- Align metadata and log2cpm
# metadata <- metadata[match(colnames(log2cpm), metadata$SampleName), ]
# 
# # --- Build group and comp IDs from metadata ---
# metadata$group <- paste(metadata$Species, metadata$Timepoint, sep = "_")
# 
# time_order <- c("Day0", "Day2","Day5","Day15","Day30")
# species_order <- c("H","C")
# 
# group_levels <- c(paste("H",time_order,sep = "_"), paste("C",time_order, sep = "_"))
# 
# metadata$group <- factor(metadata$group, levels = group_levels, ordered = TRUE)
# 
# groupid <- as.numeric(metadata$group)
# 
# # Build Human vs Chimp same-timepoint comparisons
# make_species_comparison <- function(levels_vec, times) {
#   h_idx <- match(paste("H", times, sep = "_"), levels_vec)
#   c_idx <- match(paste("C", times, sep = "_"), levels_vec)
# 
#   keep <- !is.na(h_idx) & !is.na(c_idx)
# 
#   cbind(h_idx[keep], c_idx[keep])
# }
# 
# compid <- make_species_comparison(
#   levels(metadata$group),
#   time_order
# )
# 
# colnames(compid) <- c("Human", "Chimp")
# rownames(compid) <- paste0(time_order, "_H_vs_C")
# 
# 
# # ==============================
# # Run model
# # ==============================
# cat("Fitting CorMotif...\n")
# 
# set.seed(8)
# motif.fitted <- cormotiffit(
#   exprs = log2cpm,
#   groupid = groupid,
#   compid = compid,
#   K = 1:20,
#   max.iter = 2000,
#   runtype = "logCPM"
# )
# 
# saveRDS(motif.fitted,
#         file = paste0("CorMotif_k1_k20_No4_TMM_seed8_Species_TACC.rds"))
# 
# pdf(paste0("CorMotif_k1_k20_plots_No4_TMM_seed8_Species_TACC.pdf"))
# plotIC(motif.fitted)
# plotMotif(motif.fitted)
# dev.off()
# 
# topgenelist <- generank(motif.fitted$bestmotif$p.post)
# write.csv(topgenelist,
#           paste0("CorMotif_top_genes_No4_TMM_seed8_Species_TACC.csv"),
#           row.names = TRUE)
# 
# cat(">>> Finished No4_TMM seed:8")


```

#### Graphing

```{r RNA-Seq_No4_TMM_Species_TACC_plot ,fig.height=8,fig.width=15}
motif.fitted <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_TMM_seed8_Species_TACC.rds")

plotIC(motif.fitted)
plotMotif(motif.fitted)
cols <- gray(seq(1, 0, length.out = 6))

legend(
  "topright",
  legend = seq(0, 1, length.out = 6),
  fill = cols,
  border = "black",
  title = "Posterior probability")


```

#### PPost

```{r RRNA-Seq_No4_TMM_Species_TACC_PPost}
motif.fitted <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_TMM_seed8_Species_TACC.rds")

log2cpm <- readRDS("data/Cormotif/TACC/ToCormotif/Filt_logcpm_G1_SpTp_RNA_log2cpm_No4_TMM.RDS")

motif.fit <- motif.fitted

TopTable <- readRDS("data/DGE/TopTable_Filt_logcpm_G1_SpTp_RNA_fc_NoRep_No4.RDS")

#extract the posterior probability that these genes belong to motifs
gene_prob_ppost <- motif.fit$bestmotif$p.post
rownames(gene_prob_ppost) <- rownames(log2cpm)
saveRDS(gene_prob_ppost,"data/Cormotif/Species/RNA_gene_prob_ppost_Species.RDS")

#assign each gene to a motif with max post prob
assigned_motifs <- apply(gene_prob_ppost, 1, which.max)
max_probs <- apply(gene_prob_ppost, 1, max)

#combine these into a dataframe - motif assigned genes (p.post)
motif_assignment_df <- gene_prob_ppost %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>%
  mutate(
    Assigned_Motif = assigned_motifs[Gene],
    Max_Probability = max_probs[Gene]
  )

#make some histograms of the unfiltered data from Cormotif p.post

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V1))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V1")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V2))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V2")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V3))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V3")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V4))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V4")

gene_prob_ppost %>%
  as.data.frame() %>%
  ggplot(., aes(x = V5))+
  geom_histogram(bins = 50)+
  xlim(0,1)+
  ggtitle("Cormtif p.post RNA V5")

```

#### Cluster Assignments

```{r RNA-Seq_No4_TMM_Species_TACC_ClusterAssign}

motif.fitted <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_TMM_seed8_Species_TACC.rds")

log2cpm <- readRDS("data/Cormotif/TACC/ToCormotif/Filt_logcpm_G1_SpTp_RNA_log2cpm_No4_TMM.RDS")

motif.fit <- motif.fitted

TopTable <- readRDS("data/DGE/TopTable_Filt_logcpm_G1_SpTp_RNA_fc_NoRep_No4.RDS")

gene_prob_ppost <- readRDS("data/Cormotif/Species/RNA_gene_prob_ppost_Species.RDS")

# Extract cluster probabilities
motif_prob <- motif.fit$bestmotif$clustlike
rownames(motif_prob) <- rownames(gene_prob_ppost)

saveRDS(
  motif_prob,
  "data/Cormotif/Species/PPost_Filt_logcpm_G1_SpTp_RNA_TMM_fc_NoRep_No4.RDS"
)

# Keep species comparisons only
TopTable <- TopTable %>%
  filter(
    Comparisons %in% c(
      "HvC_Day0",
      "HvC_Day2",
      "HvC_Day5",
      "HvC_Day15",
      "HvC_Day30"
    )
  )

# Define clusters
clust1_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 > 0.56, V2 < 0.5, V3 < 0.5, V4 < 0.5, V5 < 0.5) %>%
  rownames()

clust2_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 <  0.56, V2 > 0.5, V3 < 0.5, V4 < 0.5, V5 < 0.5) %>%
  rownames()

clust3_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 <  0.56, V2 < 0.5, V3 > 0.5, V4 < 0.5, V5 < 0.5) %>%
  rownames()

clust4_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 <  0.56, V2 < 0.5, V3 < 0.5, V4 > 0.5, V5 < 0.5) %>%
  rownames()

clust5_RNA <- motif_prob %>%
  as.data.frame() %>%
  filter(V1 <  0.56, V2 < 0.5, V3 < 0.5, V4 < 0.5, V5 > 0.5) %>%
  rownames()

# Create cluster annotation for every gene
cluster_annotation <- c(
  setNames(rep("cluster1", length(clust1_RNA)), clust1_RNA),
  setNames(rep("cluster2", length(clust2_RNA)), clust2_RNA),
  setNames(rep("cluster3", length(clust3_RNA)), clust3_RNA),
  setNames(rep("cluster4", length(clust4_RNA)), clust4_RNA),
  setNames(rep("cluster5", length(clust5_RNA)), clust5_RNA)
)

saveRDS(cluster_annotation, "data/Cormotif/Species/SpeciesClusterAnnotation_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")


# Cluster list
clust_names_list <- list(
  clust1 = clust1_RNA,
  clust2 = clust2_RNA,
  clust3 = clust3_RNA,
  clust4 = clust4_RNA,
  clust5 = clust5_RNA
)

# Check sizes
sapply(clust_names_list, length)

# Overlap
overlap_matrix <- check_overlap(clust_names_list)
print(overlap_matrix)

TopTable$AbsFC <- abs(TopTable$logFC)

# FC plots
cluster_plots <- lapply(names(clust_names_list), function(clust_name) {
  plot_cluster_fc_sig_species(
    clust_names_list[[clust_name]],
    clust_name,
    TopTable
  )
})

for (p in cluster_plots) {
  if (!is.null(p)) print(p)
}

# AbsFC plots
cluster_plots <- lapply(names(clust_names_list), function(clust_name) {
  plot_cluster_absfc_sig_species(
    clust_names_list[[clust_name]],
    clust_name,
    TopTable
  )
})

for (p in cluster_plots) {
  if (!is.null(p)) print(p)
}


```

```{r RNA-Seq_No4_TMM_Species_TACC_ClusterOverlapChecks}

clust_names_list <- list(
  clust1_RNA,
  clust2_RNA,
  clust3_RNA,
  clust4_RNA,
  clust5_RNA
)

names(clust_names_list) <- paste0("clust", 1:5)

print(overlap_matirx <- check_overlap(clust_names_list))

```

#### GoProfiler2

```{r RNA-Seq_No4_TMM_Species_TACC_GProfiler2}

motif.fitted <- readRDS("data/Cormotif/TACC/Species/CorMotif_k1_k20_No4_TMM_seed8_Species_TACC.rds")

TopTable <- readRDS("data/DGE/TopTable_Filt_logcpm_G1_SpTp_RNA_fc_NoRep_No4.RDS")

all_genes <- unique(TopTable$Gene)


# convert_to_entrez_df <- function(genes) {
# 
#   genes <- sub("\\..*", "", genes)
# 
#   bitr(
#     genes,
#     fromType = "ENSEMBL",
#     toType   = "ENTREZID",
#     OrgDb    = org.Hs.eg.db
#   ) %>% distinct()
# }
# 
# background_entrez <- convert_to_entrez_df(all_genes)$ENTREZID
# 
# gost_results <- setNames(
# 
#   lapply(names(clust_names_list), function(clust_name) {
# 
#     genes <- clust_names_list[[clust_name]]
# 
#     entrez_df <- convert_to_entrez_df(genes)
# 
#     if (nrow(entrez_df) == 0) return(NULL)
# 
#     gost(
#       query = entrez_df$ENTREZID,
# 
#       organism = "hsapiens",
# 
#       significant = FALSE,
#       ordered_query = FALSE,         # TRUE only if ranked
#       domain_scope = "custom",
# 
#       measure_underrepresentation = FALSE,
#       evcodes = FALSE,
# 
#       numeric_ns = "ENTREZGENE",
# 
#       user_threshold = 0.05,
#       correction_method = "fdr",
# 
#       custom_bg = background_entrez,
# 
#       sources = c("GO:BP", "KEGG")
#     )
#   }),
# 
#   names(clust_names_list)
# )
# 
# saveRDS(gost_results, "data/Cormotif/Species/SpeciesGo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

gost_results <- readRDS("data/Cormotif/Species/SpeciesGo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# gost_combined <- do.call(rbind, lapply(names(gost_results), function(clust_name) {
# 
#   res <- gost_results[[clust_name]]
# 
#   if (is.null(res)) return(NULL)
# 
#   df <- res$result
#   df$Cluster <- clust_name
#   df
# }))
# 
# saveRDS(gost_combined, "data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# gost_export <- gost_combined
# 
# gost_export[] <- lapply(gost_export, function(col) {
# 
#   if (is.list(col)) {
#     sapply(col, paste, collapse = ";")
#   } else {
#     col
#   }
# 
# })
# 
# write.csv(gost_export,
#           "data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.csv",
#           row.names = FALSE)

```

##### Plotting

###### GO:BP

```{r RNA-Seq_No4_TMM_Species_TACC_GProfiler_GO, fig.height=3, fig.width=7}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

top_terms <- gost_combined %>%
  filter(source == "GO:BP") %>%        # keep only BP terms
  group_by(Cluster) %>%
  slice_min(p_value, n = 10) %>%       # top 10 per cluster
  ungroup()

cluster_list <- split(top_terms, top_terms$Cluster)

library(ggplot2)

for (clust_name in names(cluster_list)) {
  
  df <- cluster_list[[clust_name]]
  
  p <- ggplot(df,
              aes(x = Cluster, y = term_name, fill = -log10(p_value))) +
    geom_tile(color = "white") +
    scale_fill_gradient(low = "grey90", high = "firebrick") +
    labs(fill = "-log10(p-value)",
         x = "Cluster",
         y = "GO Term") +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 8))
  
  print(p)   # display in RStudio
  
}

library(dplyr)
library(ggplot2)

top_terms <- gost_combined %>%
  filter(source == "GO:BP",
         p_value < 0.05) %>%
  group_by(Cluster) %>%
  slice_min(p_value, n = 3, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(
    Cluster_num = as.numeric(gsub("clust", "", Cluster)),
    term_label = paste0(Cluster, " : ", term_name)
  ) %>%
  arrange(desc(Cluster_num))

top_terms$term_label <- factor(
  top_terms$term_label,
  levels = rev(top_terms$term_label)
)

ggplot(top_terms,
       aes(x = 1,
           y = term_label,
           fill = -log10(p_value))) +
  geom_tile(color = "white", width = 0.8) +
  geom_text(aes(label = Cluster), size = 3) +
  scale_fill_gradient(low = "grey90", high = "firebrick") +
  labs(fill = "-log10(p-value)",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 8),
    panel.grid = element_blank()
  )
```



```{r RNA-Seq_No4_TMM_Species_TACC_GProfiler_GO_combined,fig.height=5}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")



library(dplyr)
library(tidyr)
library(ggplot2)

sig_thresh <- 0.05

# 1. For each cluster, keep significant terms and max 10 lowest p-values
top_sig_terms_per_cluster <- gost_combined %>%
  filter(source == "GO:BP") %>%
  group_by(Cluster) %>%
  filter(p_value < sig_thresh) %>%                    # keep only significant
  slice_min(order_by = p_value, n = 10, with_ties = FALSE) %>%  # max 10 per cluster
  ungroup()

# 2. Keep all unique terms across clusters
unique_terms <- unique(top_sig_terms_per_cluster$term_name)

# 3. Filter original gost_combined for these terms, retain p-values from all clusters
heatmap_data <- gost_combined %>%
  filter(source == "GO:BP", term_name %in% unique_terms) %>%
  mutate(logp = -log10(p_value)) %>%
  select(Cluster, term_name, logp)

# 4. Pivot to wide format for matrix-style heatmap
heatmap_wide <- heatmap_data %>%
  pivot_wider(names_from = Cluster, values_from = logp)

saveRDS(heatmap_wide, "data/Cormotif/Species/SpeciesGoWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesGoWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# 5. Convert to long format for ggplot
heatmap_long <- heatmap_wide %>%
  pivot_longer(cols = -term_name, names_to = "Cluster", values_to = "logp")

saveRDS(heatmap_long, "data/Cormotif/Species/SpeciesGoLong_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

heatmap_long <- readRDS("data/Cormotif/Species/SpeciesGoLong_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# 6. Plot heatmap
ggplot(heatmap_long, aes(x = Cluster, y = term_name, fill = logp)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "grey90", high = "firebrick", na.value = "white") +
  labs(fill = "-log10(p-value)", x = "Cluster", y = "GO Term") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 6))

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesGoWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

library(dplyr)
library(tidyr)
library(pheatmap)

# Prepare the matrix for clustering: rows = terms, columns = clusters
heatmap_matrix <- heatmap_wide %>%
  column_to_rownames(var = "term_name") %>%   # rows = GO terms
  as.matrix()

# Optional: replace NAs with 0 for clustering (or leave NA if you want)
heatmap_matrix[is.na(heatmap_matrix)] <- 0

sig_matrix <- gost_combined %>%
  filter(
    source == "GO:BP",
    term_name %in% unique_terms
  ) %>%
  mutate(
    sig = ifelse(p_value < 0.05, "*", "")
  ) %>%
  select(Cluster, term_name, sig) %>%
  pivot_wider(
    names_from = Cluster,
    values_from = sig,
    values_fill = ""
  ) %>%
  column_to_rownames("term_name") %>%
  as.matrix()

# Create clustered heatmap
pheatmap(
  heatmap_matrix,
  color = colorRampPalette(c("grey90", "firebrick"))(100),
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = TRUE,
  fontsize_row = 6,
  fontsize_col = 8,
  main = "GO:BP Enrichment Heatmap",
  display_numbers = sig_matrix,
  number_color = "black"
)




```

###### KEGG

```{r RNA-Seq_No4_TMM_Species_TACC_GProfiler_KEGG, fig.height=3, fig.width=7}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

top_terms <- gost_combined %>%
  filter(source == "KEGG") %>%        # keep only BP terms
  group_by(Cluster) %>%
  slice_min(p_value, n = 10) %>%       # top 10 per cluster
  ungroup()

cluster_list <- split(top_terms, top_terms$Cluster)

library(ggplot2)

for (clust_name in names(cluster_list)) {
  
  df <- cluster_list[[clust_name]]
  
  p <- ggplot(df,
              aes(x = Cluster, y = term_name, fill = -log10(p_value))) +
    geom_tile(color = "white") +
    scale_fill_gradient(low = "grey90", high = "firebrick") +
    labs(fill = "-log10(p-value)",
         x = "Cluster",
         y = "KEGG Term") +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 8))
  
  print(p)   # display in RStudio
  
}

library(dplyr)
library(ggplot2)

top_terms <- gost_combined %>%
  filter(source == "KEGG",
         p_value < 0.05) %>%
  group_by(Cluster) %>%
  slice_min(p_value, n = 3, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(
    Cluster_num = as.numeric(gsub("clust", "", Cluster)),
    term_label = paste0(Cluster, " : ", term_name)
  ) %>%
  arrange(desc(Cluster_num))

top_terms$term_label <- factor(
  top_terms$term_label,
  levels = rev(top_terms$term_label)
)

ggplot(top_terms,
       aes(x = 1,
           y = term_label,
           fill = -log10(p_value))) +
  geom_tile(color = "white", width = 0.8) +
  geom_text(aes(label = Cluster), size = 3) +
  scale_fill_gradient(low = "grey90", high = "firebrick") +
  labs(fill = "-log10(p-value)",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size = 8),
    panel.grid = element_blank()
  )
```

```{r RNA-Seq_No4_TMM_Species_TACC_GProfiler_KEGG_combined,fig.height=5}

gost_combined <- readRDS("data/Cormotif/Species/SpeciesGoCombo_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")



library(dplyr)
library(tidyr)
library(ggplot2)

sig_thresh <- 0.05

# 1. For each cluster, keep significant terms and max 10 lowest p-values
top_sig_terms_per_cluster <- gost_combined %>%
  filter(source == "KEGG") %>%
  group_by(Cluster) %>%
  filter(p_value < sig_thresh) %>%                    # keep only significant
  slice_min(order_by = p_value, n = 10, with_ties = FALSE) %>%  # max 10 per cluster
  ungroup()

# 2. Keep all unique terms across clusters
unique_terms <- unique(top_sig_terms_per_cluster$term_name)

# 3. Filter original gost_combined for these terms, retain p-values from all clusters
heatmap_data <- gost_combined %>%
  filter(source == "KEGG", term_name %in% unique_terms) %>%
  mutate(logp = -log10(p_value)) %>%
  select(Cluster, term_name, logp)

# 4. Pivot to wide format for matrix-style heatmap
heatmap_wide <- heatmap_data %>%
  pivot_wider(names_from = Cluster, values_from = logp)

saveRDS(heatmap_wide, "data/Cormotif/Species/SpeciesKEGGWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesKEGGWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# 5. Convert to long format for ggplot
heatmap_long <- heatmap_wide %>%
  pivot_longer(cols = -term_name, names_to = "Cluster", values_to = "logp")

saveRDS(heatmap_long, "data/Cormotif/Species/SpeciesKEGGLong_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

heatmap_long <- readRDS("data/Cormotif/Species/SpeciesKEGGLong_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

# 6. Plot heatmap
ggplot(heatmap_long, aes(x = Cluster, y = term_name, fill = logp)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "grey90", high = "firebrick", na.value = "white") +
  labs(fill = "-log10(p-value)", x = "Cluster", y = "GO Term") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 6))

heatmap_wide <- readRDS("data/Cormotif/Species/SpeciesKEGGWide_logcpm_G1_SpTp_TMM_No4_NoRep.RDS")

library(dplyr)
library(tidyr)
library(pheatmap)

# Prepare the matrix for clustering: rows = terms, columns = clusters
heatmap_matrix <- heatmap_wide %>%
  column_to_rownames(var = "term_name") %>%   # rows = GO terms
  as.matrix()

# Optional: replace NAs with 0 for clustering (or leave NA if you want)
heatmap_matrix[is.na(heatmap_matrix)] <- 0

sig_matrix <- gost_combined %>%
  filter(
    source == "KEGG",
    term_name %in% unique_terms
  ) %>%
  mutate(
    sig = ifelse(p_value < 0.05, "*", "")
  ) %>%
  select(Cluster, term_name, sig) %>%
  pivot_wider(
    names_from = Cluster,
    values_from = sig,
    values_fill = ""
  ) %>%
  column_to_rownames("term_name") %>%
  as.matrix()

# Create clustered heatmap
pheatmap(
  heatmap_matrix,
  color = colorRampPalette(c("grey90", "firebrick"))(100),
  cluster_rows = TRUE,
  cluster_cols = TRUE,
  show_rownames = TRUE,
  show_colnames = TRUE,
  fontsize_row = 6,
  fontsize_col = 8,
  main = "KEGG Enrichment Heatmap",
  display_numbers = sig_matrix,
  number_color = "black"
)




```


```{r Updating Website, eval = FALSE}

# git -> commit all changes
# git -> push
wflow_publish("analysis/RNA_Cormotif_Species.Rmd")

```
