---
title: "RNA_CorrelationHeatMap_ExpressedinOneTissue"
output: html_document
date: "2026-01-14"
---

```{r setup, include=FALSE, warning = FALSE, message=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{r Setting_Up_Enviroment, include=FALSE, warning = FALSE, message=FALSE}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")
library("tidyr")
library("forcats")


library(tidyr)
library(ggplot2)

# BiocManager::install("SummarizedExperiment")

RNA_fc_df <- readRDS("data/Raw_Data/concat/RNA_fc_df.RDS")
RNA_Metadata <- readRDS("data/Raw_Data/concat/RNA_Metadata.RDS")
marker_genes <- readRDS("data/Raw_Data/concat/marker_genes.RDS")
total_reads_df <- readRDS("data/Raw_Data/concat/total_reads_df.RDS")

RNA_fc <- readRDS("data/QC/concat/RNA_fc.RDS")
RNA_log2cpm <- readRDS("data/QC/concat/RNA_log2cpm.RDS")
ann_colors <- readRDS("data/QC/concat/ann_colors.RDS")

RNA_Metadata_No4 <- readRDS("data/QC/concat/RNA_Metatdata_No4.RDS")
Cor_metadata_No4 <- readRDS("data/QC/Cor_metadata_No4.RDS")

ann_colors_No4 <- readRDS("data/QC/ann_colors_no4.RDS")
RNA_Metadata_NoD4_NoRep <- readRDS("data/DGE/Trajectory/RNA_Metadata_NoD4_NoRep.RDS")

RNA_Metadata_No5 <- readRDS("data/QC/concat/RNA_Metatdata_No5.RDS")

Cor_metadata_No5 <-readRDS("data/QC/concat/Cor_metadata_No5.RDS")

ann_colors_No5 <-readRDS("data/QC/concat/ann_colors_no5.RDS")

Filt_RMG0_RNA_fc_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_PerDay.RDS")
Filt_RMG0_RNA_log2cpm_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_PerDay.RDS")
Cor_Filt_RMG0_RNA_log2cpm_PerDay <- readRDS("data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_PerDay.RDS")

Filt_RMG0_RNA_fc_NoD4_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD4_PerDay.RDS")
Filt_RMG0_RNA_log2cpm_NoD4_PerDay<- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD4_PerDay.RDS")
Cor_Filt_RMG0_RNA_log2cpm_NoD4_PerDay <- readRDS("data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD4_PerDay.RDS")

Filt_RMG0_RNA_fc_NoD5_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD5_PerDay.RDS")
Filt_RMG0_RNA_log2cpm_NoD5_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD5_PerDay.RDS")
Cor_Filt_RMG0_RNA_log2cpm_NoD5_PerDay <-readRDS("data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD5_PerDay.RDS")

Filt_lcpm_RNA_fc_BlakeEndo <- readRDS("data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo.RDS")
Filt_lcpm_RNA_log2cpm_BlakeEndo <-readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo.RDS")

Filt_lcpm_RNA_fc_BlakeEndo_PerDay <- readRDS("data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo_PerDay.RDS")
Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay <- readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay.RDS")
Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay <- readRDS("data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay.RDS")

Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4 <- readRDS("data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4.RDS")
Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4<- readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4.RDS")
Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4 <- readRDS("data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4.RDS")

Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5 <-readRDS("data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5.RDS")
Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5 <-readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5")
Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5 <-readRDS("data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5.RDS")

Filt_lcpm_RNA_fc_BlakeTissue <-readRDS("data/QC/concat/Filt_lcpm_RNA_fc_BlakeTissue.RDS")
Filt_lcpm_RNA_log2cpm_BlakeTissue <-readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue")

Filt_lcpm_RNA_fc_BlakeTissue_PerDay <- readRDS("data/QC/concat/Filt_lcpm_RNA_fc_BlakeTissue_PerDay.RDS")
Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay <- readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay.RDS")
Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay <- readRDS("data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay.RDS")

Filt_lcpm_RNA_fc_NoD4 <- readRDS("data/QC/concat/Filt_lcpm_RNA_fc_NoD4.RDS")
Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4 <- readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4.RDS")
Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4 <- readRDS("data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4.RDS")

Filt_lcpm_RNA_fc_NoD5 <- readRDS("data/QC/concat/Filt_lcpm_RNA_fc_NoD5.RDS")
Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5 <- readRDS("data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5.RDS")
Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5 <- readRDS("data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5.RDS")



```


```{r Setting_Up_Data, results="hide"}

# RNA_Metadata <- read_excel("~/diff_timeline_tes/RNA/RNA_Metadata.xlsx")
# counts_table <- read.delim("~/diff_timeline_tes/RNA/rna_concat/featureCounts/all_counts.txt")
# marker_genes <- read.delim("~/diff_timeline_tes/RNA/CM_Diff_PurityPanel.txt")
# 
# RNA_fc <- counts_table %>%
#   filter(Geneid != "#") %>%
#   filter(Geneid != "Geneid") %>%
#   column_to_rownames("Geneid")
# 
# # #Rename column Names to More Useful Info
# col_labels <- RNA_Metadata$SampleName
# colnames(RNA_fc) <- col_labels
# dim(RNA_fc)
# 
# ensembl_ids_unfilt <- rownames(RNA_fc)
# entrez_ids_unfilt <- mapIds(org.Hs.eg.db,
#                             keys = ensembl_ids_unfilt,
#                             column = "ENTREZID",
#                             keytype = "ENSEMBL",
#                             multiVals = "first")
# symbol_ids_unfilt <- mapIds(org.Hs.eg.db,
#                             keys = ensembl_ids_unfilt,
#                             column = "SYMBOL",
#                             keytype = "ENSEMBL",
#                             multiVals = "first")
# 
# RNA_fc_df <- as.data.frame(RNA_fc)
# RNA_fc_df <- RNA_fc_df %>%
#   rownames_to_column(var = "Ensemble") %>%
#   dplyr::mutate(
#     Entrez_ID = entrez_ids_unfilt,
#     Symbol    = symbol_ids_unfilt
#   ) %>%
#   dplyr::select(
#     Ensemble,        # 1st column
#     Entrez_ID,       # 2nd column
#     Symbol,          # 3rd column
#     everything()     # rest unchanged
#   )
# 
# rn <- rownames(RNA_fc)
# 
# RNA_fc <- as.data.frame(
#   lapply(RNA_fc, function(x) as.numeric(as.character(x)))
# )
# 
# rownames(RNA_fc) <- rn
# 
# saveRDS(RNA_fc,"data/QC/concat/RNA_fc.RDS")
# saveRDS(RNA_fc_df,"data/Raw_Data/concat/RNA_fc_df.RDS")
# saveRDS(RNA_Metadata,"data/Raw_Data/concat/RNA_Metadata.RDS")
# saveRDS(marker_genes,"data/Raw_Data/concat/marker_genes.RDS")
```

####Seqeuncing Statistics

```{r RNASeq_Statistics_data}
total_reads_df <- RNA_fc %>%
  as.data.frame() %>%
  mutate(Gene = rownames(.)) %>%
  dplyr::select(-Gene) %>%
  summarise(across(everything(), \(x) sum(x, na.rm = TRUE))) %>%
  pivot_longer(
    cols = everything(),
    names_to = "Sample",
    values_to = "Total_Counts"
  ) %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))

day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")

total_reads_df <- total_reads_df %>%
  mutate(
    Timepoint = factor(Timepoint, levels = day_levels, ordered = TRUE),

    # force species order: chimp first, human second
    Species = factor(Species, levels = c("C", "H")),

    Individual_Color = ann_colors$individual_cor[Individual]
  ) %>%
  arrange(Species, Individual, Timepoint) %>%
  mutate(Sample = factor(Sample, levels = Sample))
# saveRDS(total_reads_df,"data/Raw_Data/concat/total_reads_df.RDS")
```

```{r RNASeq_bySample_graph, fig.height=6,fig.width=12}
library(ggplot2)

ggplot(total_reads_df, aes(x = Sample, y = Total_Reads, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Total Reads per Sample",
    x = "Individual",
    y = "Total Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Sample, y = Mapped_Reads, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Mapped Reads per Sample",
    x = "Individual",
    y = "Mapped Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Sample, y = Percent_Mapped, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Percent Mapping per Sample",
    x = "Individual",
    y = "Percent Mapping",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Sample, y = Usable_Fragments, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Usable Fragments per Sample",
    x = "Individual",
    y = "Number Fragments",
    fill = "Timepoint",
    color = "Individual"
  )

```

```{r RNASeq_bySpecies_graph, fig.height=6,fig.width=12}
ggplot(total_reads_df, aes(x = Species, y = Total_Reads)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Total Reads per Species",
    x = "Species",
    y = "Total_Reads",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Species, y = Mapped_Reads)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Mapped Reads per Species",
    x = "Species",
    y = "Mapped_Reads",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Species, y = Percent_Mapped)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Percent of Reads Mapped per Species",
    x = "Species",
    y = "Percent of reads Mapping",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Species, y = Usable_Fragments)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Usable Fragments per Species",
    x = "Species",
    y = "Number of Fragments",
    color = "Individual"
  )
  
```

```{r RNASeq_byDaybySpecies_graph, fig.height=6,fig.width=12}

ggplot(total_reads_df, aes(x = Timepoint, y = Total_Reads)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Total Reads per Day by Species",
    x = "Day",
    y = "Total Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Timepoint, y = Mapped_Reads)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Mapped Reads per Day by Species",
    x = "Day",
    y = "Mapped Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Timepoint, y = Percent_Mapped)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Percent of Reads Mapping per Day by Species",
    x = "Day",
    y = "Percent_Mapped",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Timepoint, y = Usable_Fragments)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Usable Fragments per Day by Species",
    x = "Day",
    y = "Number of Fragments",
    fill = "Timepoint",
    color = "Individual"
  )
```

```{r RNASeq_byIndividualbySpecies_graph, fig.height=6,fig.width=12}
ggplot(total_reads_df, aes(x = Individual, y = Total_Reads)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Total Reads per Individual by Species",
    x = "Individual",
    y = "Total Reads",
    fill = "Individual",
    color = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Individual, y = Mapped_Reads)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Mapped Reads per Individual by Species",
    x = "Individual",
    y = "Mapped Reads",
    fill = "Individual",
    color = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Individual, y = Percent_Mapped)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Percentage of Mapped Reads per Individual by Species",
    x = "Individual",
    y = "Percentage of Mapped Reads",
    fill = "Individual",
    color = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Individual, y = Usable_Fragments)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Usable Fragments per Individual by Species",
    x = "Individual",
    y = "Number of Fragments",
    fill = "Individual",
    color = "Timepoint"
  )
```

```{r RNASeq_Purities,results="hide"}
# -----------------------------
# 1. Prepare long-format data
# -----------------------------
day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")
marker_levels <- c("OCT3/4", "Brachy", "ISL-1", "TNNT-2")

RNA_Metadata_NoRep <- RNA_Metadata %>%
  dplyr::filter(!SampleName %in% c(
    "H20682R_Day0",
    "H20682R_Day2",
    "H20682R_Day5",
    "H20682R_Day30"
  ))

df_long_all <- RNA_Metadata_NoRep %>%
  dplyr::select(Individual,Cond, `OCT3/4`, Brachy, `ISL-1`, `TNNT-2`,Species) %>%
  mutate(
    `OCT3/4` = as.numeric(`OCT3/4`),
    Brachy = as.numeric(Brachy),
    `ISL-1` = as.numeric(`ISL-1`),
    `TNNT-2` = as.numeric(`TNNT-2`),
    Group = ifelse(grepl("^H_", Cond), "H", "C")
  ) %>%
  pivot_longer(
    cols = c(`OCT3/4`, Brachy, `ISL-1`, `TNNT-2`),
    names_to = "Marker",
    values_to = "Percent_Positive"
  ) %>%
  mutate(
    Day = gsub(".*_(Day\\d+)$", "\\1", Cond),
    Day = factor(Day, levels = day_levels, ordered = TRUE),
    Marker = factor(Marker, levels = marker_levels, ordered = TRUE)
  )

# -----------------------------
# 2. Compute summary with SEM
# -----------------------------
summary_df <- df_long_all %>%
  group_by(Marker, Day, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD = sd(Percent_Positive, na.rm = TRUE),
    N = sum(!is.na(Percent_Positive)),
    SEM = SD / sqrt(N),
    .groups = "drop"
  )

library(dplyr)

results <- df_long_all %>%
  group_by(Day, Marker, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD   = sd(Percent_Positive, na.rm = TRUE),
    N    = sum(!is.na(Percent_Positive)),
    SEM  = SD / sqrt(N),
    .groups = "drop"
  ) %>%
  tidyr::pivot_wider(
    names_from = Group,
    values_from = c(Mean, SD, SEM, N),
    names_sep = "_"
  ) %>%
  left_join(
    df_long_all %>%
      group_by(Day, Marker) %>%
      summarise(
        p_value = t.test(Percent_Positive ~ Group)$p.value,
        .groups = "drop"
      ),
    by = c("Day", "Marker")
  )
```

```{r RNASeq_Purities_graph, fig.height=6,fig.width=12}
# -----------------------------
# 3. Plot lines over time with SEM error bars
# -----------------------------
library(dplyr)
library(scales)

ggplot(summary_df,
       aes(x = Day, y = Mean,
           linetype = Group,
           group = Group)) +

  # Individual points
  geom_point(
    data = df_long_all,
    aes(
      x = Day,
      y = Percent_Positive,
      color = Individual,
      shape = Group
    ),
    size = 2.5,
    alpha = 0.9,
    position = position_jitter(width = 0.08, height = 0)
  ) +

  # Mean line (black, texture = species)
  geom_line(
    linewidth = 0.5,
    color = "black"
  ) +

  # Mean point (black)
  geom_point(
    size = 0.5,
    color = "black"
  ) +

  # Error bars (black)
  geom_errorbar(
    aes(ymin = Mean - SD, ymax = Mean + SD),
    width = 0.2,
    color = "black"
  ) +

  facet_wrap(~ Marker, nrow = 1) +

  # species as line texture
  scale_linetype_manual(
    values = c(
      "H" = "solid",
      "C" = "dashed"
    ),
    name = "Species"
  ) +

  # species as shape
  scale_shape_manual(
    values = c(
      "H" = 17,  # triangle
      "C" = 16   # circle
    ),
    name = "Species"
  ) +

  # individual colors from your manual palette
  scale_color_manual(
    values = ann_colors$individual_cor,
    name = "Individual"
  ) +

  # Use coord_cartesian instead of scale_y_continuous to avoid dropped points
  coord_cartesian(ylim = c(0, 100)) +

  labs(
    title = "Mean Percent Positive Across Timepoints for Each Marker",
    x = "Day",
    y = "Mean Percent Positive (%)",
    caption = "Color = individual, shape/line = species, error bars = SD"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    plot.caption = element_text(hjust = 0, face = "italic", size = 10)
  )
```

```{r RNASeq_Purities_No4,results="hide"}
# -----------------------------
# 1. Prepare long-format data
# -----------------------------
day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")
marker_levels <- c("OCT3/4", "Brachy", "ISL-1", "TNNT-2")

RNA_Metadata_NoD4_NoRep <- RNA_Metadata %>%
  dplyr::filter(Timepoint != "Day4") %>%
  dplyr::filter(!SampleName %in% c(
    "H20682R_Day0",
    "H20682R_Day2",
    "H20682R_Day5",
    "H20682R_Day30"
  ))

df_long_No4 <- RNA_Metadata_NoD4_NoRep %>%
  dplyr::select(Individual,Cond, `OCT3/4`, Brachy, `ISL-1`, `TNNT-2`) %>%
  mutate(
    `OCT3/4` = as.numeric(`OCT3/4`),
    Brachy = as.numeric(Brachy),
    `ISL-1` = as.numeric(`ISL-1`),
    `TNNT-2` = as.numeric(`TNNT-2`),
    Group = ifelse(grepl("^H_", Cond), "H", "C")
  ) %>%
  pivot_longer(
    cols = c(`OCT3/4`, Brachy, `ISL-1`, `TNNT-2`),
    names_to = "Marker",
    values_to = "Percent_Positive"
  ) %>%
  mutate(
    Day = gsub(".*_(Day\\d+)$", "\\1", Cond),
    Day = factor(Day, levels = day_levels, ordered = TRUE),
    Marker = factor(Marker, levels = marker_levels, ordered = TRUE)
  )

# -----------------------------
# 2. Compute summary with SEM
# -----------------------------
summary_df_No4 <- df_long_No4 %>%
  group_by(Marker, Day, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD = sd(Percent_Positive, na.rm = TRUE),
    N = sum(!is.na(Percent_Positive)),
    SEM = SD / sqrt(N),
    .groups = "drop"
  )
```

```{r RNASeq_Purities_graph_No4_graph, fig.height=6,fig.width=12}
# -----------------------------
# 3. Plot lines over time with SEM error bars
# -----------------------------
library(dplyr)
library(scales)

ggplot(summary_df_No4,
       aes(x = Day, y = Mean,
           linetype = Group,
           group = Group)) +

  # Individual points
  geom_point(
    data = df_long_No4,
    aes(
      x = Day,
      y = Percent_Positive,
      color = Individual,
      shape = Group
    ),
    size = 2.5,
    alpha = 0.9,
    position = position_jitter(width = 0.08, height = 0)
  ) +

  # Mean line (black, texture = species)
  geom_line(
    linewidth = 0.5,
    color = "black"
  ) +

  # Mean point (black)
  geom_point(
    size = 0.5,
    color = "black"
  ) +

  # Error bars (black)
  geom_errorbar(
    aes(ymin = Mean - SD, ymax = Mean + SD),
    width = 0.2,
    color = "black"
  ) +

  facet_wrap(~ Marker, nrow = 1) +

  # species as line texture
  scale_linetype_manual(
    values = c(
      "H" = "solid",
      "C" = "dashed"
    ),
    name = "Species"
  ) +

  # species as shape
  scale_shape_manual(
    values = c(
      "H" = 17,  # triangle
      "C" = 16   # circle
    ),
    name = "Species"
  ) +

  # individual colors from your manual palette
  scale_color_manual(
    values = ann_colors$individual_cor,
    name = "Individual"
  ) +

  # Use coord_cartesian instead of scale_y_continuous to avoid dropped points
  coord_cartesian(ylim = c(0, 100)) +

  labs(
    title = "Mean Percent Positive Across Timepoints for Each Marker",
    x = "Day",
    y = "Mean Percent Positive (%)",
    caption = "Color = individual, shape/line = species, error bars = SD"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    plot.caption = element_text(hjust = 0, face = "italic", size = 10)
  )
```

```{r RNASeq_Purities_No5,results="hide"}
# -----------------------------
# 1. Prepare long-format data
# -----------------------------
day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")
marker_levels <- c("OCT3/4", "Brachy", "ISL-1", "TNNT-2")

RNA_Metadata_NoD5_NoRep <- RNA_Metadata %>%
  dplyr::filter(Timepoint != "Day5") %>%
  dplyr::filter(!SampleName %in% c(
    "H20682R_Day0",
    "H20682R_Day2",
    "H20682R_Day5",
    "H20682R_Day30"
  ))

df_long_No5 <- RNA_Metadata_NoD5_NoRep %>%
  dplyr::select(Individual,Cond, `OCT3/4`, Brachy, `ISL-1`, `TNNT-2`) %>%
  mutate(
    `OCT3/4` = as.numeric(`OCT3/4`),
    Brachy = as.numeric(Brachy),
    `ISL-1` = as.numeric(`ISL-1`),
    `TNNT-2` = as.numeric(`TNNT-2`),
    Group = ifelse(grepl("^H_", Cond), "H", "C")
  ) %>%
  pivot_longer(
    cols = c(`OCT3/4`, Brachy, `ISL-1`, `TNNT-2`),
    names_to = "Marker",
    values_to = "Percent_Positive"
  ) %>%
  mutate(
    Day = gsub(".*_(Day\\d+)$", "\\1", Cond),
    Day = factor(Day, levels = day_levels, ordered = TRUE),
    Marker = factor(Marker, levels = marker_levels, ordered = TRUE)
  )

# -----------------------------
# 2. Compute summary with SEM
# -----------------------------
summary_df_No5 <- df_long_No5 %>%
  group_by(Marker, Day, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD = sd(Percent_Positive, na.rm = TRUE),
    N = sum(!is.na(Percent_Positive)),
    SEM = SD / sqrt(N),
    .groups = "drop"
  )

```

```{r RNASeq_Purities_graph_No5_graph, fig.height=6,fig.width=12}
# -----------------------------
# 3. Plot lines over time with SEM error bars
# -----------------------------
library(dplyr)
library(scales)

ggplot(summary_df_No5,
       aes(x = Day, y = Mean,
           linetype = Group,
           group = Group)) +

  # Individual points
  geom_point(
    data = df_long_No5,
    aes(
      x = Day,
      y = Percent_Positive,
      color = Individual,
      shape = Group
    ),
    size = 2.5,
    alpha = 0.9,
    position = position_jitter(width = 0.08, height = 0)
  ) +

  # Mean line (black, texture = species)
  geom_line(
    linewidth = 0.5,
    color = "black"
  ) +

  # Mean point (black)
  geom_point(
    size = 0.5,
    color = "black"
  ) +

  # Error bars (black)
  geom_errorbar(
    aes(ymin = Mean - SD, ymax = Mean + SD),
    width = 0.2,
    color = "black"
  ) +

  facet_wrap(~ Marker, nrow = 1) +

  # species as line texture
  scale_linetype_manual(
    values = c(
      "H" = "solid",
      "C" = "dashed"
    ),
    name = "Species"
  ) +

  # species as shape
  scale_shape_manual(
    values = c(
      "H" = 17,  # triangle
      "C" = 16   # circle
    ),
    name = "Species"
  ) +

  # individual colors from your manual palette
  scale_color_manual(
    values = ann_colors$individual_cor,
    name = "Individual"
  ) +

  # Use coord_cartesian instead of scale_y_continuous to avoid dropped points
  coord_cartesian(ylim = c(0, 100)) +

  labs(
    title = "Mean Percent Positive Across Timepoints for Each Marker",
    x = "Day",
    y = "Mean Percent Positive (%)",
    caption = "Color = individual, shape/line = species, error bars = SD"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    plot.caption = element_text(hjust = 0, face = "italic", size = 10)
  )
```

```{r RNASeq_FeatureCounts_Box_Unfiltered, fig.height=6,fig.width=12}
#####Unfiltered####
RNA_log2cpm <- cpm(RNA_fc, log = TRUE)

col_labels <- colnames(RNA_log2cpm)

hist(RNA_log2cpm,  main = "Histogram of all counts (unfiltered)",
     xlab =expression("Log"[2]*" counts-per-million"), col =4 )

boxplot(RNA_log2cpm, main = "Boxplots of log cpm per sample
          (unfiltered)", xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_labels),  # positions (one per sample)
     labels = col_labels,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.6)        # shrink label size
# saveRDS(RNA_log2cpm,"data/QC/concat/RNA_log2cpm.RDS")
```

####PerDay-RowMeans

```{r RNASeq_FeatureCounts_RMG0_PerDay, fig.height=6,fig.width=12}
RNA_log2cpm_df <- as.data.frame(RNA_log2cpm)
RNA_log2cpm_Day0 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day0"))

row_means <- rowMeans(RNA_log2cpm_Day0)
Filt_RMG0_RNA_log2cpm_Day0 <- RNA_log2cpm_Day0[row_means >0,]

RNA_log2cpm_Day2 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day2"))

row_means <- rowMeans(RNA_log2cpm_Day2)
Filt_RMG0_RNA_log2cpm_Day2 <- RNA_log2cpm_Day2[row_means >0,]

RNA_log2cpm_Day4 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day4"))

row_means <- rowMeans(RNA_log2cpm_Day4)
Filt_RMG0_RNA_log2cpm_Day4 <- RNA_log2cpm_Day4[row_means >0,]

RNA_log2cpm_Day5 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day5"))

row_means <- rowMeans(RNA_log2cpm_Day5)
Filt_RMG0_RNA_log2cpm_Day5 <- RNA_log2cpm_Day5[row_means >0,]

RNA_log2cpm_Day15 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day15"))

row_means <- rowMeans(RNA_log2cpm_Day15)
Filt_RMG0_RNA_log2cpm_Day15 <- RNA_log2cpm_Day15[row_means >0,]

RNA_log2cpm_Day30 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day30"))

row_means <- rowMeans(RNA_log2cpm_Day30)
Filt_RMG0_RNA_log2cpm_Day30 <- RNA_log2cpm_Day30[row_means >0,]

g0   <- rownames(Filt_RMG0_RNA_log2cpm_Day0)
g2   <- rownames(Filt_RMG0_RNA_log2cpm_Day2)
g4   <- rownames(Filt_RMG0_RNA_log2cpm_Day4)
g5   <- rownames(Filt_RMG0_RNA_log2cpm_Day5)
g15  <- rownames(Filt_RMG0_RNA_log2cpm_Day15)
g30  <- rownames(Filt_RMG0_RNA_log2cpm_Day30)

exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

Filt_RMG0_RNA_fc_PerDay <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids) %>% 
  column_to_rownames("Ensembl.ID")
  
# saveRDS(Filt_RMG0_RNA_fc_PerDay,"data/QC/concat/Filt_RMG0_RNA_fc_PerDay.RDS")

Filt_RMG0_RNA_log2cpm_PerDay <- cpm(Filt_RMG0_RNA_fc_PerDay,log=TRUE)

# saveRDS(Filt_RMG0_RNA_log2cpm_PerDay,"data/QC/concat/Filt_RMG0_RNA_log2cpm_PerDay.RDS")

hist(Filt_RMG0_RNA_log2cpm_PerDay, main = "Histogram of filtered counts using rowMeans > 0 method",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

```

```{r RNASeq_FeatureCounts_Box_RMG0, fig.height=6,fig.width=12}
boxplot(Filt_RMG0_PerDay_RNA_log2cpm_PerDay, main = "Boxplots of log cpm per sample (RowMeans>0)",xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_labels),  # positions (one per sample)
     labels = col_labels,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.6)        # shrink label size

```

```{r RNASeq_Counts_graph, fig.height=6,fig.width=12}
library(ggplot2)
library(dplyr)

# Define ordered day factor
day_levels <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

total_reads_df <- total_reads_df %>%
  mutate(
    # Order Timepoint for bars
    Timepoint = factor(Timepoint, levels = day_levels, ordered = TRUE),
    
    # Individual text color
    Individual_Color = ann_colors$individual_cor[Individual]
  ) %>%
  # Order Sample for x-axis: first by Individual, then by Day
  arrange(Individual, Timepoint) %>%
  mutate(Sample = factor(Sample, levels = Sample))  # preserve order in ggplot

# Plot
ggplot(total_reads_df, aes(x = Sample, y = Total_Counts, fill = Timepoint)) +
  
  # Bars colored by Timepoint
  geom_col() +

  # Annotate Individual names under bars, colored by individual
  geom_text(
    aes(label = Individual, color = Individual_Color),
    y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3
  ) +

  # Manual Timepoint colors
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Use exact color for individual labels
  scale_color_identity() +

  # Facet by Species if desired
  facet_grid(~Species, scales = "free_x", space = "free_x") +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_blank(),  # hide default X labels
    axis.ticks.x = element_blank(),
    legend.position = "top"
  ) +

  labs(
    title = "Counts per Sample",
    x = "Individual (bars grouped by individual, ordered by day)",
    y = "Total Counts",
    fill = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Species, y = Total_Counts)) +
  
  # Boxplot for each species
  geom_boxplot(aes(fill = Species), alpha = 0.3, outlier.shape = NA) + 
  
  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Optional: species fill colors (light grey / black)
  scale_fill_manual(values = c("H" = "#17171717", "C" = "#17171717")) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top"
  ) +

  labs(
    title = "Counts per Species",
    x = "Species",
    y = "Total Counts",
    color = "Individual",
    fill = "Species"
  )


ggplot(total_reads_df, aes(x = Timepoint, y = Total_Counts)) +
  
  # Boxplot per day
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +

  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Use timepoint colors for boxplots
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Separate x-axis by species
  facet_wrap(~Species, scales = "free_x") +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Counts per Day by Species",
    x = "Day",
    y = "Total Counts",
    color = "Individual",
    fill = "Timepoint"
  )


# Plot
ggplot(total_reads_df, aes(x = Individual, y = Total_Counts)) +
  
  # Boxplots colored by individual
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +

  # Overlay points colored by Timepoint
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +

  # Use manual colors
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +

  # Facet by species
  facet_wrap(~Species, scales = "free_x", nrow = 1) +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Counts per Individual by Species",
    x = "Individual",
    y = "Total Counts",
    fill = "Individual",
    color = "Timepoint"
  )
```

```{r RNASeq_TotalReads_dataset}
library(tidyverse)

total_reads_df <- RNA_fc %>%
  as.data.frame() %>%
  mutate(Gene = rownames(.)) %>%
  dplyr::select(-Gene) %>%
  summarise(across(everything(), \(x) sum(x, na.rm = TRUE))) %>%
  pivot_longer(
    cols = everything(),
    names_to = "Sample",
    values_to = "Total_Reads"
  ) %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))
```

```{r RNASeq_TotalReads_graph, fig.height=6,fig.width=12}
library(ggplot2)
library(dplyr)

# Define ordered day factor
day_levels <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

total_reads_df <- total_reads_df %>%
  mutate(
    # Order Timepoint for bars
    Timepoint = factor(Timepoint, levels = day_levels, ordered = TRUE),
    
    # Individual text color
    Individual_Color = ann_colors$individual_cor[Individual]
  ) %>%
  # Order Sample for x-axis: first by Individual, then by Day
  arrange(Individual, Timepoint) %>%
  mutate(Sample = factor(Sample, levels = Sample))  # preserve order in ggplot

# Plot
ggplot(total_reads_df, aes(x = Sample, y = Total_Reads.x, fill = Timepoint)) +
  
  # Bars colored by Timepoint
  geom_col() +

  # Annotate Individual names under bars, colored by individual
  geom_text(
    aes(label = Individual, color = Individual_Color),
    y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3
  ) +

  # Manual Timepoint colors
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Use exact color for individual labels
  scale_color_identity() +

  # Facet by Species if desired
  facet_grid(~Species, scales = "free_x", space = "free_x") +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_blank(),  # hide default X labels
    axis.ticks.x = element_blank(),
    legend.position = "top"
  ) +

  labs(
    title = "Total Reads per Sample",
    x = "Individual (bars grouped by individual, ordered by day)",
    y = "Total Reads",
    fill = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Species, y = Total_Reads.x)) +
  
  # Boxplot for each species
  geom_boxplot(aes(fill = Species), alpha = 0.3, outlier.shape = NA) + 
  
  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Optional: species fill colors (light grey / black)
  scale_fill_manual(values = c("H" = "#17171717", "C" = "#17171717")) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top"
  ) +

  labs(
    title = "Total Reads per Species",
    x = "Species",
    y = "Total Reads",
    color = "Individual",
    fill = "Species"
  )


ggplot(total_reads_df, aes(x = Timepoint, y = Total_Reads.x)) +
  
  # Boxplot per day
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +

  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Use timepoint colors for boxplots
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Separate x-axis by species
  facet_wrap(~Species, scales = "free_x") +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Total Reads per Day by Species",
    x = "Day",
    y = "Total Reads",
    color = "Individual",
    fill = "Timepoint"
  )


# Plot
ggplot(total_reads_df, aes(x = Individual, y = Total_Reads.x)) +
  
  # Boxplots colored by individual
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +

  # Overlay points colored by Timepoint
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +

  # Use manual colors
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +

  # Facet by species
  facet_wrap(~Species, scales = "free_x", nrow = 1) +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Total Reads per Individual by Species",
    x = "Individual",
    y = "Total Reads",
    fill = "Individual",
    color = "Timepoint"
  )
```

```{r RNASeq_FeatureCounts_Cor_RMG0_PerDay}
######Cor_HeatMap####
Cor_Filt_RMG0_RNA_log2cpm_PerDay <- cor(Filt_RMG0_RNA_log2cpm_PerDay, method = "spearman")
individual <- RNA_Metadata$Individual
species <- RNA_Metadata$Species
timepoint <- RNA_Metadata$Timepoint
timepoint <- factor(timepoint,levels = c("Day0","Day2","Day4","Day5","Day15","Day30"))
Cor_metadata <- data.frame(
  sample_cor = colnames(Filt_RMG0_RNA_log2cpm_PerDay),
  species_cor = species,
  timepoint_cor = timepoint,
  individual_cor = individual
)


ann_colors <- list(
  timepoint_cor = c(
    "Day0" = "#883268",   # Purple
    "Day2" = "#3E7274",  # blue
    "Day4" = "#5AAA464D",  # light green
    "Day5" = "#94C47D",  # Green
    "Day15" = "#C03830",  # red
    "Day30" = "#830C05"  # dark red
  ),
  species_cor = c(
    "H" = "black",  # black
    "C" = "white"   # white
  ),
  individual_cor = c(
    H1 = "#091638", #Blue-Green Darkest
    H2 = "#11185B",
    H3 = "#0F2C71",
    H4 = "#0D568F",
    H4R = "#0D568F",
    H5 = "#1D8296",
    H6 = "#46A389",
    H7 = "#9DD484", #Blue-Green Lightest
    C1 = "#340702", #Brown-Orange darkest
    C2 = "#5D0B02",
    C3 = "#951302",
    C4 = "#D32804",
    C5 = "#F74019",
    C6 = "#FA7A38",
    C7 = "#FCC598"
    
  )
)
rownames(Cor_metadata) <- Cor_metadata$sample_cor

saveRDS(Cor_Filt_RMG0_RNA_log2cpm_PerDay, "data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_PerDay.RDS")
# saveRDS(Cor_metadata, "data/QC/concat/Cor_RNA_metadata.RDS")
# saveRDS(ann_colors,"data/QC/concat/ann_colors.RDS")

```

```{r RNASeq_FeatureCounts_HeatMap_RMG0_PerDay,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm_PerDay,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation \n(Spearman-log2CPM-RowMeans>0 Row PerDay)")
)
```

```{r RNASeq_FeatureCounts_RMG0_PerDay_No4}

####Subset####
exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

RNA_fc_No4 <- RNA_fc %>% 
  dplyr::select(-contains("Day4"))

Filt_RMG0_RNA_fc_NoD4_PerDay <- RNA_fc_No4 %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids_No4) %>% 
  column_to_rownames("Ensembl.ID")

dim(Filt_RMG0_RNA_fc_NoD4_PerDay)
Filt_RMG0_RNA_log2cpm_NoD4_PerDay <- cpm(Filt_RMG0_RNA_fc_NoD4_PerDay,log=TRUE)

# saveRDS(RNA_Metadata_No4,"data/QC/concat/RNA_Metatdata_No4.RDS")
# saveRDS(Filt_RMG0_RNA_fc_NoD4_PerDay,"data/QC/concat/Filt_RMG0_RNA_fc_NoD4_PerDay.RDS")
# saveRDS(Filt_RMG0_RNA_log2cpm_NoD4_PerDay, "data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD4_PerDay.RDS")

```

```{r rRNASeq_FeatureCounts_Cor_RMG0_PerDay_No4}
######Cor_HeatMap####
Cor_Filt_RMG0_RNA_log2cpm_NoD4_PerDay <- cor(Filt_RMG0_RNA_log2cpm_NoD4_PerDay, method = "spearman")

Cor_metadata_No4 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day4")

ann_colors_No4 <- ann_colors
ann_colors_No4$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day4"
]

# saveRDS(Cor_metadata_No4, "data/QC/concat/Cor_metadata_No4.RDS")
# saveRDS(Cor_Filt_RMG0_RNA_log2cpm_NoD4_PerDay, "data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD4_PerDay.RDS")
# saveRDS(ann_colors_No4,"data/QC/concat/ann_colors_no4.RDS")
```

```{r rRNASeq_FeatureCounts_HeatMap_RMG0_PerDay_No4,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm_NoD4_PerDay,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No4[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2CPM-RowMeans>0 PerDay-NoDay4)")
)
```

```{r RNASeq_FeatureCounts_RMG0_PerDay_No5}

####Subset####
RNA_Metadata_No5 <- RNA_Metadata %>% 
 filter(Timepoint != "Day5")

RNA_fc_No5 <- RNA_fc %>% 
  dplyr::select(-contains("Day5"))

exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

Filt_RMG0_RNA_fc_NoD5_PerDay <- RNA_fc_No5 %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids_No5) %>% 
  column_to_rownames("Ensembl.ID")

dim(Filt_RMG0_RNA_fc_NoD5_PerDay)
Filt_RMG0_RNA_log2cpm_NoD5_PerDay <- cpm(Filt_RMG0_RNA_fc_NoD5_PerDay,log=TRUE)

# saveRDS(RNA_Metadata_No5,"data/QC/concat/RNA_Metatdata_No5.RDS")
# saveRDS(Filt_RMG0_RNA_fc_NoD5_PerDay,"data/QC/concat/Filt_RMG0_RNA_fc_NoD5_PerDay.RDS")
# saveRDS(Filt_RMG0_RNA_log2cpm_NoD5_PerDay, "data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD5_PerDay.RDS")

```

```{r rRNASeq_FeatureCounts_Cor_RMG0_PerDay_No5}
######Cor_HeatMap####
Cor_Filt_RMG0_RNA_log2cpm_NoD5_PerDay <- cor(Filt_RMG0_RNA_log2cpm_NoD5_PerDay, method = "spearman")

Cor_metadata_No5 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day5")

ann_colors_No5 <- ann_colors
ann_colors_No5$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day5"
]

# saveRDS(Cor_metadata_No5, "data/QC/concat/Cor_metadata_No5.RDS")
# saveRDS(Cor_Filt_RMG0_RNA_log2cpm_NoD5_PerDay, "data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD5_PerDay.RDS")
# saveRDS(ann_colors_No5,"data/QC/concat/ann_colors_no5.RDS")
```

```{r rRNASeq_FeatureCounts_HeatMap_RMG0_PerDay_No5,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm_NoD5_PerDay,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No5[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No5,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2CPM-RowMeans>0-NoDay5)")
)
```

```{r RNASeq_MarkerGenes_dataset_PerDay, fig.height=6,fig.width=12}
markers <- marker_genes$Ensembl.ID

log2cpm_long <- RNA_log2cpm %>%
  as.data.frame() %>%
  rownames_to_column("Ensembl.ID") %>%
  filter(Ensembl.ID %in% markers) %>% 
  pivot_longer(
    cols = -Ensembl.ID,
    names_to = "Sample",
    values_to = "log2CPM"
  )

log2cpm_long <- log2cpm_long %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))

log2cpm_long <- log2cpm_long %>%
  left_join(marker_genes, by = "Ensembl.ID")

log2cpm_long$Timepoint <- factor(
  log2cpm_long$Timepoint,
  levels = c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")
)

log2cpm_long_NoR <- log2cpm_long %>% 
  filter(Individual != "H4R")

library(dplyr)

mean_df <- log2cpm_long_NoR %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )

log2cpm_long_NoR$Stage <- factor(
  log2cpm_long_NoR$Stage,
  levels = c(
    "Pluripotency",
    "Mesoderm",
    "CardiacMesoderm",
    "CardiacProgenitors",
    "EarlyCardiomyocytes",
    "MatureCardiomyocytes"
  )
)
```

```{r RNASeq_MarkerGenes_graph_PerDay, fig.height=12,fig.width=12}
library(ggplot2)

ggplot(log2cpm_long_NoR, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
    aes(fill = Stage),
    alpha = 0.3,
    outlier.shape = NA
  ) +

  geom_line(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_PerDay, fig.height=12,fig.width=12}
library(ggplot2)

ggplot(log2cpm_long_NoR, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
  aes(fill = Species, group = interaction(Timepoint, Species)),
  alpha = 0.3,
  outlier.shape = NA,
  position = position_dodge(width = 0.8)
  ) +
  
    scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_expressed_PerDay, fig.height=12,fig.width=12}
library(ggplot2)
expressed_genes <- exp_ensembl_ids

log2cpm_long_NoR_expressed <- log2cpm_long_NoR %>% 
  filter(Ensembl.ID %in% expressed_genes)
  
ggplot(log2cpm_long_NoR_expressed, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
  aes(fill = Species, group = interaction(Timepoint, Species)),
  alpha = 0.3,
  outlier.shape = NA,
  position = position_dodge(width = 0.8)
  ) +
  
    scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_means_PerDay, fig.height=6,fig.width=6}
mean_df$Stage <- factor(
  mean_df$Stage,
  levels=c("MatureCardiomyocytes","EarlyCardiomyocytes","CardiacProgenitors","CardiacMesoderm","Mesoderm","Pluripotency")
)

levels(mean_df$Stage)
mean_df$Stage

ggplot(mean_df, aes(
  x = Timepoint,
  y = Stage,
  fill = mean_log2CPM
)) +
  geom_tile(color = "white") +

  facet_wrap(~ Species) +

  scale_fill_gradient2(
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0
  ) +

  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_means_expressed_PerDay, fig.height=6,fig.width=6}
mean_df_expressed <- log2cpm_long_NoR_expressed %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )

mean_df_expressed$Stage <- factor(
  mean_df_expressed$Stage,
  levels=c("MatureCardiomyocytes","EarlyCardiomyocytes","CardiacProgenitors","CardiacMesoderm","Mesoderm","Pluripotency")
)

levels(mean_df_expressed$Stage)
mean_df_expressed$Stage

ggplot(mean_df_expressed, aes(
  x = Timepoint,
  y = Stage,
  fill = mean_log2CPM
)) +
  geom_tile(color = "white") +

  facet_wrap(~ Species) +

  scale_fill_gradient2(
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0
  ) +

  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_data, fig.height=6,fig.width=6}
library(dplyr)
library(tidyr)
library(tibble)

mat <- log2cpm_long_NoR %>%
  dplyr::group_by(Gene, Sample) %>%
  dplyr::summarise(log2CPM = mean(log2CPM, na.rm = TRUE), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = Sample, values_from = log2CPM) %>%
  tibble::column_to_rownames("Gene") %>%
  as.matrix()

stage_order <- c(
  "Pluripotency",
  "Mesoderm",
  "CardiacMesoderm",
  "CardiacProgenitors",
  "EarlyCardiomyocytes",
  "MatureCardiomyocytes"
)

gene_annot <- log2cpm_long_NoR %>%
  dplyr::select(Gene, Stage) %>%
  distinct() %>%
  dplyr::mutate(Stage = factor(Stage, levels = stage_order)) %>%
  dplyr::arrange(Stage)

mat <- mat[gene_annot$Gene, ]

gene_annot <- data.frame(Stage = gene_annot$Stage)
rownames(gene_annot) <- gene_annot$Gene

tp_order <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

sample_annot <- log2cpm_long_NoR %>%
  distinct(Sample, Timepoint, Species, Individual) %>%
  mutate(Timepoint = trimws(Timepoint)) %>%
  column_to_rownames("Sample")

sample_annot <- sample_annot[colnames(mat), ]

rownames(sample_annot) <- sample_annot$Sample
sample_annot <- sample_annot[, c("Timepoint", "Species", "Individual")]

annotation_colors = list(
  Timepoint  = ann_colors$timepoint_cor,
  Species    = ann_colors$species_cor,
  Individual = ann_colors$individual_cor,

  Stage = c(
    Pluripotency = "#1f77b4",
    Mesoderm = "#ff7f0e",
    CardiacMesoderm = "yellow",
    CardiacProgenitors = "#2ca02c",
    EarlyCardiomyocytes = "#d62728",
    MatureCardiomyocytes = "#9467bd"
  )
)
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_graph, fig.height=10,fig.width=10}
pheatmap(
  mat,
  annotation_col = sample_annot,
  annotation_row = gene_annot,
  annotation_colors = annotation_colors,
  cluster_rows = FALSE,
  clustering_distance_cols = "correlation",
  color = colorRampPalette(c("#2166AC", "white", "#B2182B"))(100)
)
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_data_expressed_PerDay, fig.height=6,fig.width=6}
library(dplyr)
library(tidyr)
library(tibble)

mat_expressed <- log2cpm_long_NoR_expressed %>%
  dplyr::group_by(Gene, Sample) %>%
  dplyr::summarise(log2CPM = mean(log2CPM, na.rm = TRUE), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = Sample, values_from = log2CPM) %>%
  tibble::column_to_rownames("Gene") %>%
  as.matrix()

stage_order <- c(
  "Pluripotency",
  "Mesoderm",
  "CardiacMesoderm",
  "CardiacProgenitors",
  "EarlyCardiomyocytes",
  "MatureCardiomyocytes"
)

gene_annot_expressed <- log2cpm_long_NoR_expressed %>%
  dplyr::select(Gene, Stage) %>%
  distinct() %>%
  dplyr::mutate(Stage = factor(Stage, levels = stage_order)) %>%
  dplyr::arrange(Stage)

mat_expressed <- mat_expressed[gene_annot_expressed$Gene, ]

gene_annot_expressed <- data.frame(Stage = gene_annot_expressed$Stage)
rownames(gene_annot_expressed) <- gene_annot_expressed$Gene

tp_order <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

sample_annot_expressed <- log2cpm_long_NoR_expressed %>%
  distinct(Sample, Timepoint, Species, Individual) %>%
  mutate(Timepoint = trimws(Timepoint)) %>%
  column_to_rownames("Sample")

sample_annot_expressed <- sample_annot_expressed[colnames(mat_expressed), ]

rownames(sample_annot_expressed) <- sample_annot_expressed$Sample
sample_annot_expressed <- sample_annot_expressed[, c("Timepoint", "Species", "Individual")]

annotation_colors = list(
  Timepoint  = ann_colors$timepoint_cor,
  Species    = ann_colors$species_cor,
  Individual = ann_colors$individual_cor,

  Stage = c(
    Pluripotency = "#1f77b4",
    Mesoderm = "#ff7f0e",
    CardiacMesoderm = "yellow",
    CardiacProgenitors = "#2ca02c",
    EarlyCardiomyocytes = "#d62728",
    MatureCardiomyocytes = "#9467bd"
  )
)
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_graph_expressed_PerDay, fig.height=10,fig.width=10}
pheatmap(
  mat_expressed,
  annotation_col = sample_annot_expressed,
  annotation_row = gene_annot_expressed,
  annotation_colors = annotation_colors,
  cluster_rows = FALSE,
  clustering_distance_cols = "correlation",
  color = colorRampPalette(c("#2166AC", "white", "#B2182B"))(100)
)
```

```{r RNASeq_MarkerGenes_graph_species_separated_pluri_PerDay, fig.height=12,fig.width=12}
pluri_genes <- log2cpm_long_NoR %>%
  filter(Stage == "Pluripotency")

ggplot(pluri_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
     geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 3,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_meso_PerDay, fig.height=12,fig.width=12}
meso_genes <- log2cpm_long_NoR %>%
  filter(Stage == "Mesoderm")

ggplot(meso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +

    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardmeso_PerDay, fig.height=12,fig.width=12}
cardmeso_genes <- log2cpm_long_NoR %>%
  filter(Stage == "CardiacMesoderm")

ggplot(cardmeso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardprog_PerDay, fig.height=12,fig.width=12}
cardprog_genes <- log2cpm_long_NoR %>%
  filter(Stage == "CardiacProgenitors")

ggplot(cardprog_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardearly_PerDay, fig.height=12,fig.width=12}
cardearly_genes <- log2cpm_long_NoR %>%
  filter(Stage == "EarlyCardiomyocytes")

ggplot(cardearly_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardlate_PerDay, fig.height=12,fig.width=12}
cardlate_genes <- log2cpm_long_NoR %>%
  filter(Stage == "MatureCardiomyocytes")

ggplot(cardlate_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +

  scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


####Half Species log2cpm >1.5 (Blake EndoPaper)

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerSpecies, fig.height=6,fig.width=12}
RNA_log2cpm_df <- as.data.frame(RNA_log2cpm)

# log2cpm = your matrix/data frame (rows = genes, cols = samples)

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(RNA_log2cpm_df))
C_samples <- grep("^C", colnames(RNA_log2cpm_df))

# Number needed to pass (half of each group)
H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(RNA_log2cpm_df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- RNA_log2cpm_df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")
  
# saveRDS(Filt_lcpm_RNA_fc_BlakeEndo,"data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo.RDS")

Filt_lcpm_RNA_log2cpm_BlakeEndo <- cpm(Filt_lcpm_RNA_fc_BlakeEndo,log=TRUE)

# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeEndo,"data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo.RDS")

hist(Filt_lcpm_RNA_log2cpm_BlakeEndo, main = "Histogram of filtered counts using Half of Human or Chimp have log2cpm>1.5 (Blake-Endo Paper)",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

```

####PerDay-Species log2cpm >1.5 half samples

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerSpeciesPerDay, fig.height=6,fig.width=12}
RNA_log2cpm_df <- as.data.frame(RNA_log2cpm)
RNA_log2cpm_Day0 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day0"))


#Day0
df <- RNA_log2cpm_Day0

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(df))
C_samples <- grep("^C", colnames(df))

H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_Day0_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day0
df <- RNA_log2cpm_Day2

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(df))
C_samples <- grep("^C", colnames(df))

H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_Day2_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day4
df <- RNA_log2cpm_Day4

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(df))
C_samples <- grep("^C", colnames(df))

H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_Day4_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day5
df <- RNA_log2cpm_Day5

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(df))
C_samples <- grep("^C", colnames(df))

H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_Day5_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day15
df <- RNA_log2cpm_Day15

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(df))
C_samples <- grep("^C", colnames(df))

H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_Day15_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day30
df <- RNA_log2cpm_Day30

# Define sample groups (edit based on your column names)
H_samples <- grep("^H", colnames(df))
C_samples <- grep("^C", colnames(df))

H_min <- ceiling(length(H_samples) / 2)
C_min <- ceiling(length(C_samples) / 2)

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[H_samples] > 1.5) >= H_min ||
  sum(x[C_samples] > 1.5) >= C_min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_Day30_BlakeEndo <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")


g0   <- rownames(Filt_lcpm_RNA_fc_Day0_BlakeEndo)
g2   <- rownames(Filt_lcpm_RNA_fc_Day2_BlakeEndo)
g4   <- rownames(Filt_lcpm_RNA_fc_Day4_BlakeEndo)
g5   <- rownames(Filt_lcpm_RNA_fc_Day5_BlakeEndo)
g15  <- rownames(Filt_lcpm_RNA_fc_Day15_BlakeEndo)
g30  <- rownames(Filt_lcpm_RNA_fc_Day30_BlakeEndo)

exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

Filt_lcpm_RNA_fc_BlakeEndo_PerDay <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids) %>% 
  column_to_rownames("Ensembl.ID")

# saveRDS(Filt_lcpm_RNA_fc_BlakeEndo_PerDay,"data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo_PerDay.RDS")

Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay <- cpm(Filt_lcpm_RNA_fc_BlakeEndo_PerDay,log=TRUE)

# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay,"data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay.RDS")

hist(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay, main = "Histogram of filtered counts using log2cpm >1.5 in half of a days samples regardless of species",
     xlab =expression("Log"[2]*" counts-per-million PerDay-BlakeEndo"), col =5 )

```

```{r RNASeq_FeatureCounts_Box_log2cpm_HalfSamplesPerSpeciesPerDay, fig.height=6,fig.width=12}
boxplot(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay, main = "Boxplots of log cpm per sample (Log2cpm > 1.5 in half of the samples in a species-timepoint)",xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_labels),  # positions (one per sample)
     labels = col_labels,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.6)        # shrink label size

```

```{r RNASeq_FeatureCounts_Cor_log2cpm_HalfSamplesPerSpeciesPerDay}
######Cor_HeatMap####
Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay <- cor(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay, method = "spearman")
individual <- RNA_Metadata$Individual
species <- RNA_Metadata$Species
timepoint <- RNA_Metadata$Timepoint
timepoint <- factor(timepoint,levels = c("Day0","Day2","Day4","Day5","Day15","Day30"))
Cor_metadata <- data.frame(
  sample_cor = colnames(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay),
  species_cor = species,
  timepoint_cor = timepoint,
  individual_cor = individual
)


ann_colors <- list(
  timepoint_cor = c(
    "Day0" = "#883268",   # Purple
    "Day2" = "#3E7274",  # blue
    "Day4" = "#5AAA464D",  # light green
    "Day5" = "#94C47D",  # Green
    "Day15" = "#C03830",  # red
    "Day30" = "#830C05"  # dark red
  ),
  species_cor = c(
    "H" = "black",  # black
    "C" = "white"   # white
  ),
  individual_cor = c(
    H1 = "#091638", #Blue-Green Darkest
    H2 = "#11185B",
    H3 = "#0F2C71",
    H4 = "#0D568F",
    H4R = "#0D568F",
    H5 = "#1D8296",
    H6 = "#46A389",
    H7 = "#9DD484", #Blue-Green Lightest
    C1 = "#340702", #Brown-Orange darkest
    C2 = "#5D0B02",
    C3 = "#951302",
    C4 = "#D32804",
    C5 = "#F74019",
    C6 = "#FA7A38",
    C7 = "#FCC598"
    
  )
)
rownames(Cor_metadata) <- Cor_metadata$sample_cor

saveRDS(Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay, "data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay.RDS")
# saveRDS(Cor_metadata, "data/QC/concat/Cor_RNA_metadata.RDS")
# saveRDS(ann_colors,"data/QC/concat/ann_colors.RDS")

```

```{r RNASeq_FeatureCounts_HeatMap_log2cpm_HalfSamplesPerSpeciesPerDay,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation \n(log2cpm >1.5 in half individuals per species per day)")
)
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerSpeciesPerDay_No4}

####Subset####
exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

RNA_fc_No4 <- RNA_fc %>% 
  dplyr::select(-contains("Day4"))

Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4 <- RNA_fc_No4 %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids_No4) %>% 
  column_to_rownames("Ensembl.ID")

dim(Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4)

# saveRDS(Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4, "data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4.RDS")

Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4 <- cpm(Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD4,log=TRUE)

# saveRDS(RNA_Metadata_No4,"data/QC/concat/RNA_Metatdata_No4.RDS")
# saveRDS(Filt_RMG0_RNA_fc_NoD4,"data/QC/concat/Filt_RMG0_RNA_fc_NoD4.RDS")
# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4, "data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4.RDS")

```

```{r rRNASeq_FeatureCounts_Cor_log2cpm_HalfSamplesPerSpeciesPerDay_No4}
######Cor_HeatMap####
Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4 <- cor(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4, method = "spearman")

Cor_metadata_No4 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day4")

ann_colors_No4 <- ann_colors
ann_colors_No4$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day4"
]

# saveRDS(Cor_metadata_No4, "data/QC/concat/Cor_metadata_No4.RDS")
# saveRDS(Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4, "data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4.RDS")
# saveRDS(ann_colors_No4,"data/QC/concat/ann_colors_no4.RDS")
```

```{r rRNASeq_FeatureCounts_HeatMap_log2cpm_HalfSamplesPerSpeciesPerDay_No4,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD4,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No4[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2cpm >1.5 in half individuals per species per day-NoDay4)")
)
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerSpeciesPerDay_No5}

####Subset####
RNA_Metadata_No5 <- RNA_Metadata %>% 
 filter(Timepoint != "Day5")

RNA_fc_No5 <- RNA_fc %>% 
  dplyr::select(-contains("Day5"))

exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5 <- RNA_fc_No5 %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids_No5) %>% 
  column_to_rownames("Ensembl.ID")

dim(Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5)

# saveRDS(Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5, "data/QC/concat/Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5.RDS")

Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5 <- cpm(Filt_lcpm_RNA_fc_BlakeEndo_PerDay_NoD5,log=TRUE)

# saveRDS(RNA_Metadata_No5,"data/QC/concat/RNA_Metatdata_No5.RDS")
# saveRDS(Filt_RMG0_RNA_fc_NoD5,"data/QC/concat/Filt_RMG0_RNA_fc_NoD5.RDS")
# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5, "data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5")

```

```{r rRNASeq_FeatureCounts_Cor_log2cpm_HalfSamplesPerSpeciesPerDay_No5}
######Cor_HeatMap####
Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5 <- cor(Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5, method = "spearman")

Cor_metadata_No5 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day5")

ann_colors_No5 <- ann_colors
ann_colors_No5$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day5"
]

# saveRDS(Cor_metadata_No5, "data/QC/concat/Cor_metadata_No5.RDS")
# saveRDS(Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5, "data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5.RDS")
# saveRDS(ann_colors_No5,"data/QC/concat/ann_colors_no5.RDS")
```

```{r rRNASeq_FeatureCounts_HeatMap_log2cpm_HalfSamplesPerSpeciesPerDay_No5,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_lcpm_RNA_log2cpm_BlakeEndo_PerDay_NoD5,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No5[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No5,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2cpm >1.5 half individuals per species per day-NoDay5)")
)
```

```{r RNASeq_MarkerGenes_graph_species_separated_expressed_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
library(ggplot2)
expressed_genes <- exp_ensembl_ids

log2cpm_long_NoR_expressed <- log2cpm_long_NoR %>% 
  filter(Ensembl.ID %in% expressed_genes)


mean_df_expressed <- log2cpm_long_NoR_expressed %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )
 
ggplot(log2cpm_long_NoR_expressed, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
  aes(fill = Species, group = interaction(Timepoint, Species)),
  alpha = 0.3,
  outlier.shape = NA,
  position = position_dodge(width = 0.8)
  ) +
  
    scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    data = mean_df_expressed,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR_expressed$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_means_expressed_HalfSamplesPerSpeciesPerDay, fig.height=6,fig.width=6}
mean_df_expressed <- log2cpm_long_NoR_expressed %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )

mean_df_expressed$Stage <- factor(
  mean_df_expressed$Stage,
  levels=c("MatureCardiomyocytes","EarlyCardiomyocytes","CardiacProgenitors","CardiacMesoderm","Mesoderm","Pluripotency")
)

levels(mean_df_expressed$Stage)
mean_df_expressed$Stage

ggplot(mean_df_expressed, aes(
  x = Timepoint,
  y = Stage,
  fill = mean_log2CPM
)) +
  geom_tile(color = "white") +

  facet_wrap(~ Species) +

  scale_fill_gradient2(
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0
  ) +

  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_data_expressed_HalfSamplesPerSpeciesPerDay, fig.height=6,fig.width=6}
mat_expressed <- log2cpm_long_NoR_expressed %>%
  dplyr::group_by(Gene, Sample) %>%
  dplyr::summarise(log2CPM = mean(log2CPM, na.rm = TRUE), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = Sample, values_from = log2CPM) %>%
  tibble::column_to_rownames("Gene") %>%
  as.matrix()

stage_order <- c(
  "Pluripotency",
  "Mesoderm",
  "CardiacMesoderm",
  "CardiacProgenitors",
  "EarlyCardiomyocytes",
  "MatureCardiomyocytes"
)

gene_annot_expressed <- log2cpm_long_NoR_expressed %>%
  dplyr::select(Gene, Stage) %>%
  distinct() %>%
  dplyr::mutate(Stage = factor(Stage, levels = stage_order)) %>%
  dplyr::arrange(Stage)

mat_expressed <- mat_expressed[gene_annot_expressed$Gene, ]

gene_annot_expressed <- data.frame(Stage = gene_annot_expressed$Stage)
rownames(gene_annot_expressed) <- gene_annot_expressed$Gene

tp_order <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

sample_annot_expressed <- log2cpm_long_NoR_expressed %>%
  distinct(Sample, Timepoint, Species, Individual) %>%
  mutate(Timepoint = trimws(Timepoint)) %>%
  column_to_rownames("Sample")

sample_annot_expressed <- sample_annot_expressed[colnames(mat_expressed), ]

rownames(sample_annot_expressed) <- sample_annot_expressed$Sample
sample_annot_expressed <- sample_annot_expressed[, c("Timepoint", "Species", "Individual")]

annotation_colors = list(
  Timepoint  = ann_colors$timepoint_cor,
  Species    = ann_colors$species_cor,
  Individual = ann_colors$individual_cor,

  Stage = c(
    Pluripotency = "#1f77b4",
    Mesoderm = "#ff7f0e",
    CardiacMesoderm = "yellow",
    CardiacProgenitors = "#2ca02c",
    EarlyCardiomyocytes = "#d62728",
    MatureCardiomyocytes = "#9467bd"
  )
)
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_graph_HalfSamplesPerSpeciesPerDay, fig.height=10,fig.width=10}
pheatmap(
  mat_expressed,
  annotation_col = sample_annot_expressed,
  annotation_row = gene_annot_expressed,
  annotation_colors = annotation_colors,
  cluster_rows = FALSE,
  clustering_distance_cols = "correlation",
  color = colorRampPalette(c("#2166AC", "white", "#B2182B"))(100)
)
```

```{r RNASeq_MarkerGenes_graph_species_separated_pluri_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
pluri_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "Pluripotency")

ggplot(pluri_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
     geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 3,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_meso_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
meso_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "Mesoderm")

ggplot(meso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +

    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardmeso_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
cardmeso_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "CardiacMesoderm")

ggplot(cardmeso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardprog_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
cardprog_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "CardiacProgenitors")

ggplot(cardprog_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardearly_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
cardearly_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "EarlyCardiomyocytes")

ggplot(cardearly_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardlate_HalfSamplesPerSpeciesPerDay, fig.height=12,fig.width=12}
cardlate_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "MatureCardiomyocytes")

ggplot(cardlate_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +

  scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

####Half All log2cpm >1.5 (Blake TissuePaper)

```{r RNASeq_FeatureCounts_log2cpm_HalfSamples, fig.height=6,fig.width=12}
RNA_log2cpm_df <- as.data.frame(RNA_log2cpm)

# log2cpm = your matrix/data frame (rows = genes, cols = samples)

samples = colnames(RNA_log2cpm_df)

min = length(samples)/2

# Apply filtering
keep <- apply(RNA_log2cpm_df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- RNA_log2cpm_df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_BlakeTissue <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")
  
# saveRDS(Filt_lcpm_RNA_fc_BlakeTissue,"data/QC/concat/Filt_lcpm_RNA_fc_BlakeTissue.RDS")

Filt_lcpm_RNA_log2cpm_BlakeTissue <- cpm(Filt_lcpm_RNA_fc_BlakeTissue,log=TRUE)

# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeTissue,"data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue")

hist(Filt_lcpm_RNA_log2cpm_BlakeTissue, main = "Histogram of filtered counts using Half of all samples have log2cpm>1.5   (Blake-Tissue Paper)",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

```

####PerDay log2cpm >1.5 half samples####

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay, fig.height=6,fig.width=12}
RNA_log2cpm_df <- as.data.frame(RNA_log2cpm)
RNA_log2cpm_Day0 <- RNA_log2cpm_df %>% 
  dplyr::select(contains("Day0"))


#Day0
df <- RNA_log2cpm_Day0

samples = colnames(df)

min = length(samples)/2

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_BlakeTissue_Day0 <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day2
df <- RNA_log2cpm_Day2

samples = colnames(df)

min = length(samples)/2

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_BlakeTissue_Day2 <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day4
df <- RNA_log2cpm_Day4

samples = colnames(df)

min = length(samples)/2

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_BlakeTissue_Day4 <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day5
df <- RNA_log2cpm_Day5

samples = colnames(df)

min = length(samples)/2

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()
  

Filt_lcpm_RNA_fc_BlakeTissue_Day5 <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day15
df <- RNA_log2cpm_Day15

samples = colnames(df)

min = length(samples)/2

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()

Filt_lcpm_RNA_fc_BlakeTissue_Day15 <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")

#Day30
df <- RNA_log2cpm_Day30

samples = colnames(df)

min = length(samples)/2

# Apply filtering
keep <- apply(df, 1, function(x) {
  sum(x[samples] > 1.5) >= min
})

# Subset data
filtered_ids <- df[keep, ] %>% 
  rownames_to_column("Ensembl.ID") %>%  
  pull(Ensembl.ID) %>% 
  unique()

Filt_lcpm_RNA_fc_BlakeTissue_Day30 <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% filtered_ids) %>% 
  column_to_rownames("Ensembl.ID")


g0   <- rownames(Filt_lcpm_RNA_fc_BlakeTissue_Day0)
g2   <- rownames(Filt_lcpm_RNA_fc_BlakeTissue_Day2)
g4   <- rownames(Filt_lcpm_RNA_fc_BlakeTissue_Day4)
g5   <- rownames(Filt_lcpm_RNA_fc_BlakeTissue_Day5)
g15  <- rownames(Filt_lcpm_RNA_fc_BlakeTissue_Day15)
g30  <- rownames(Filt_lcpm_RNA_fc_BlakeTissue_Day30)

exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

Filt_lcpm_RNA_fc_BlakeTissue_PerDay <- RNA_fc %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids) %>% 
  column_to_rownames("Ensembl.ID")

# saveRDS(Filt_lcpm_RNA_fc_BlakeTissue_PerDay,"data/QC/concat/Filt_lcpm_RNA_fc_BlakeTissue_PerDay.RDS")

Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay <- cpm(Filt_lcpm_RNA_fc_BlakeTissue_PerDay,log=TRUE)

# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay,"data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay.RDS")

hist(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay, main = "Histogram of filtered counts using log2cpm >1.5 in half of a days samples regardless of species",
     xlab =expression("Log"[2]*" counts-per-million PerDay-BlakeTissue"), col =5 )

```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_DataSet, fig.height=12,fig.width=12}
counts_table <- read.delim("~/diff_timeline_tes/RNA/rna_concat/featureCounts/all_counts.txt")
counts_table_genes <- unique(counts_table$Geneid)
Expressed_Genes <- unique(exp_ensembl_ids)
marker_genes_ortho <- marker_genes %>% 
  filter(Ensembl.ID %in% counts_table_genes)
marker_genes_ortho_expressed <- marker_genes_ortho %>% 
  filter(Ensembl.ID %in% Expressed_Genes)
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_Box, fig.height=6,fig.width=12}
boxplot(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay, main = "Boxplots of log cpm per sample (RowMeans>0)",xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_labels),  # positions (one per sample)
     labels = col_labels,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.6)        # shrink label size

```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_Cor}
######Cor_HeatMap####
Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay <- cor(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay, method = "spearman")
individual <- RNA_Metadata$Individual
species <- RNA_Metadata$Species
timepoint <- RNA_Metadata$Timepoint
timepoint <- factor(timepoint,levels = c("Day0","Day2","Day4","Day5","Day15","Day30"))
Cor_metadata <- data.frame(
  sample_cor = colnames(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay),
  species_cor = species,
  timepoint_cor = timepoint,
  individual_cor = individual
)


ann_colors <- list(
  timepoint_cor = c(
    "Day0" = "#883268",   # Purple
    "Day2" = "#3E7274",  # blue
    "Day4" = "#5AAA464D",  # light green
    "Day5" = "#94C47D",  # Green
    "Day15" = "#C03830",  # red
    "Day30" = "#830C05"  # dark red
  ),
  species_cor = c(
    "H" = "black",  # black
    "C" = "white"   # white
  ),
  individual_cor = c(
    H1 = "#091638", #Blue-Green Darkest
    H2 = "#11185B",
    H3 = "#0F2C71",
    H4 = "#0D568F",
    H4R = "#0D568F",
    H5 = "#1D8296",
    H6 = "#46A389",
    H7 = "#9DD484", #Blue-Green Lightest
    C1 = "#340702", #Brown-Orange darkest
    C2 = "#5D0B02",
    C3 = "#951302",
    C4 = "#D32804",
    C5 = "#F74019",
    C6 = "#FA7A38",
    C7 = "#FCC598"
    
  )
)
rownames(Cor_metadata) <- Cor_metadata$sample_cor

# saveRDS(Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay, "data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay.RDS")
# saveRDS(Cor_metadata, "data/QC/concat/Cor_RNA_metadata.RDS")
# saveRDS(ann_colors,"data/QC/concat/ann_colors.RDS")

```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_CorHeatMap,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation \n(log2cpm >1.5 half individuals per species per day)")
)
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_NoD4}

####Subset####
exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

RNA_fc_No4 <- RNA_fc %>% 
  dplyr::select(-contains("Day4"))

Filt_lcpm_RNA_fc_NoD4 <- RNA_fc_No4 %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids_No4) %>% 
  column_to_rownames("Ensembl.ID")

dim(Filt_lcpm_RNA_fc_NoD4)

Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4 <- cpm(Filt_lcpm_RNA_fc_NoD4,log=TRUE)

# saveRDS(RNA_Metadata_No4,"data/QC/concat/RNA_Metatdata_No4.RDS")
# saveRDS(Filt_lcpm_RNA_fc_NoD4,"data/QC/concat/Filt_lcpm_RNA_fc_NoD4.RDS")
# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4, "data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4.RDS")

```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_NoD4_Cor}
######Cor_HeatMap####
Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4 <- cor(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4, method = "spearman")

Cor_metadata_No4 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day4")

ann_colors_No4 <- ann_colors
ann_colors_No4$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day4"
]

# saveRDS(Cor_metadata_No4, "data/QC/concat/Cor_metadata_No4.RDS")
# saveRDS(Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4, "data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4.RDS")
# saveRDS(ann_colors_No4,"data/QC/concat/ann_colors_no4.RDS")
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_NoD4_CorHeatMap,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD4,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No4[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2cpm >1.5 half individuals per species per day-NoDay4)")
)
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_NoD5}

####Subset####
RNA_Metadata_No5 <- RNA_Metadata %>% 
 filter(Timepoint != "Day5")

RNA_fc_No5 <- RNA_fc %>% 
  dplyr::select(-contains("Day5"))

exp_ensembl_ids <- unique(c(g0, g2, g4, g5, g15, g30))
exp_ensembl_ids_No4 <- unique(c(g0, g2, g5, g15, g30))
exp_ensembl_ids_No5 <- unique(c(g0, g2, g4, g15, g30))

Filt_lcpm_RNA_fc_NoD5 <- RNA_fc_No5 %>% 
  rownames_to_column("Ensembl.ID") %>% 
  filter(Ensembl.ID %in% exp_ensembl_ids_No5) %>% 
  column_to_rownames("Ensembl.ID")

dim(Filt_lcpm_RNA_fc_NoD5)
Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5 <- cpm(Filt_lcpm_RNA_fc_NoD5,log=TRUE)

# saveRDS(RNA_Metadata_No5,"data/QC/concat/RNA_Metatdata_No5.RDS")
# saveRDS(Filt_lcpm_RNA_fc_NoD5,"data/QC/concat/Filt_lcpm_RNA_fc_NoD5.RDS")
# saveRDS(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5, "data/QC/concat/Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5.RDS")

```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_NoD5_Cor}
######Cor_HeatMap####
Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5 <- cor(Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5, method = "spearman")

Cor_metadata_No5 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day5")

ann_colors_No5 <- ann_colors
ann_colors_No5$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day5"
]

# saveRDS(Cor_metadata_No5, "data/QC/concat/Cor_metadata_No5.RDS")
# saveRDS(Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5, "data/QC/concat/Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5.RDS")
# saveRDS(ann_colors_No5,"data/QC/concat/ann_colors_no5.RDS")
```

```{r RNASeq_FeatureCounts_log2cpm_HalfSamplesPerDay_NoD5_CorHeatMapy,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_lcpm_RNA_log2cpm_BlakeTissue_PerDay_NoD5,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No5[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No5,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2cpm >1.5 half individuals per species per day-NoDay5)")
)
```

```{r RNASeq_MarkerGenes_dataset_HalfSamplesPerDay, fig.height=6,fig.width=12}
markers <- marker_genes$Ensembl.ID

log2cpm_long <- RNA_log2cpm %>%
  as.data.frame() %>%
  rownames_to_column("Ensembl.ID") %>%
  filter(Ensembl.ID %in% markers) %>% 
  pivot_longer(
    cols = -Ensembl.ID,
    names_to = "Sample",
    values_to = "log2CPM"
  )

log2cpm_long <- log2cpm_long %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))

log2cpm_long <- log2cpm_long %>%
  left_join(marker_genes, by = "Ensembl.ID")

log2cpm_long$Timepoint <- factor(
  log2cpm_long$Timepoint,
  levels = c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")
)

log2cpm_long_NoR <- log2cpm_long %>% 
  filter(Individual != "H4R")

library(dplyr)

mean_df <- log2cpm_long_NoR %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )

log2cpm_long_NoR$Stage <- factor(
  log2cpm_long_NoR$Stage,
  levels = c(
    "Pluripotency",
    "Mesoderm",
    "CardiacMesoderm",
    "CardiacProgenitors",
    "EarlyCardiomyocytes",
    "MatureCardiomyocytes"
  )
)
```

```{r RNASeq_MarkerGenes_graph_species_separated_expressed_HalfSamplesPerDay, fig.height=12,fig.width=12}

expressed_genes <- exp_ensembl_ids

log2cpm_long_NoR_expressed <- log2cpm_long_NoR %>% 
  filter(Ensembl.ID %in% expressed_genes)


mean_df_expressed <- log2cpm_long_NoR_expressed %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )
 
ggplot(log2cpm_long_NoR_expressed, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
  aes(fill = Species, group = interaction(Timepoint, Species)),
  alpha = 0.3,
  outlier.shape = NA,
  position = position_dodge(width = 0.8)
  ) +
  
    scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    data = mean_df_expressed,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR_expressed$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_means_expressed_HalfSamplesPerDay, fig.height=6,fig.width=6}
mean_df_expressed <- log2cpm_long_NoR_expressed %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )

mean_df_expressed$Stage <- factor(
  mean_df_expressed$Stage,
  levels=c("MatureCardiomyocytes","EarlyCardiomyocytes","CardiacProgenitors","CardiacMesoderm","Mesoderm","Pluripotency")
)

levels(mean_df_expressed$Stage)
mean_df_expressed$Stage

ggplot(mean_df_expressed, aes(
  x = Timepoint,
  y = Stage,
  fill = mean_log2CPM
)) +
  geom_tile(color = "white") +

  facet_wrap(~ Species) +

  scale_fill_gradient2(
    low = "blue",
    mid = "white",
    high = "red",
    midpoint = 0
  ) +

  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_data_expressed_HalfSamplesPerDay, fig.height=6,fig.width=6}
library(dplyr)
library(tidyr)
library(tibble)

mat_expressed <- log2cpm_long_NoR_expressed %>%
  dplyr::group_by(Gene, Sample) %>%
  dplyr::summarise(log2CPM = mean(log2CPM, na.rm = TRUE), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = Sample, values_from = log2CPM) %>%
  tibble::column_to_rownames("Gene") %>%
  as.matrix()

stage_order <- c(
  "Pluripotency",
  "Mesoderm",
  "CardiacMesoderm",
  "CardiacProgenitors",
  "EarlyCardiomyocytes",
  "MatureCardiomyocytes"
)

gene_annot_expressed <- log2cpm_long_NoR_expressed %>%
  dplyr::select(Gene, Stage) %>%
  distinct() %>%
  dplyr::mutate(Stage = factor(Stage, levels = stage_order)) %>%
  dplyr::arrange(Stage)

mat_expressed <- mat_expressed[gene_annot_expressed$Gene, ]

gene_annot_expressed <- data.frame(Stage = gene_annot_expressed$Stage)
rownames(gene_annot_expressed) <- gene_annot_expressed$Gene

tp_order <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

sample_annot_expressed <- log2cpm_long_NoR_expressed %>%
  distinct(Sample, Timepoint, Species, Individual) %>%
  mutate(Timepoint = trimws(Timepoint)) %>%
  column_to_rownames("Sample")

sample_annot_expressed <- sample_annot_expressed[colnames(mat_expressed), ]

rownames(sample_annot_expressed) <- sample_annot_expressed$Sample
sample_annot_expressed <- sample_annot_expressed[, c("Timepoint", "Species", "Individual")]

annotation_colors = list(
  Timepoint  = ann_colors$timepoint_cor,
  Species    = ann_colors$species_cor,
  Individual = ann_colors$individual_cor,

  Stage = c(
    Pluripotency = "#1f77b4",
    Mesoderm = "#ff7f0e",
    CardiacMesoderm = "yellow",
    CardiacProgenitors = "#2ca02c",
    EarlyCardiomyocytes = "#d62728",
    MatureCardiomyocytes = "#9467bd"
  )
)
```

```{r RNASeq_MarkerGenes_graph_species_Heatmap_graph_HalfSamplesPerDay, fig.height=10,fig.width=10}
pheatmap(
  mat_expressed,
  annotation_col = sample_annot_expressed,
  annotation_row = gene_annot_expressed,
  annotation_colors = annotation_colors,
  cluster_rows = FALSE,
  clustering_distance_cols = "correlation",
  color = colorRampPalette(c("#2166AC", "white", "#B2182B"))(100)
)
```

```{r RNASeq_MarkerGenes_graph_species_separated_pluri_HalfSamplesPerDay, fig.height=12,fig.width=12}
pluri_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "Pluripotency")

ggplot(pluri_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
     geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 3,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_meso_HalfSamplesPerDay, fig.height=12,fig.width=12}
meso_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "Mesoderm")

ggplot(meso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +

    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardmeso_HalfSamplesPerDay, fig.height=12,fig.width=12}
cardmeso_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "CardiacMesoderm")

ggplot(cardmeso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardprog_HalfSamplesPerDay, fig.height=12,fig.width=12}
cardprog_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "CardiacProgenitors")

ggplot(cardprog_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardearly_HalfSamplesPerDay, fig.height=12,fig.width=12}
cardearly_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "EarlyCardiomyocytes")

ggplot(cardearly_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardlate_HalfSamplesPerDay, fig.height=12,fig.width=12}
cardlate_genes <- log2cpm_long_NoR_expressed %>%
  filter(Stage == "MatureCardiomyocytes")

ggplot(cardlate_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +

  scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r Updating Website, eval = FALSE}

# git -> commit all changes
# git -> push
wflow_publish("RNA_CorrelationHeatMap_ExpressedInOneTissue.Rmd")

```


