---
title: "RNA_CorrelationHeatMap"
output: html_document
date: "2026-01-14"
---

```{r setup, include=FALSE, warning = FALSE, message=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{r Setting_Up_Enviroment, include=FALSE, warning = FALSE, message=FALSE}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")
library("tidyr")
library("forcats")


library(tidyr)
library(ggplot2)

# BiocManager::install("SummarizedExperiment")

RNA_fc_df <- readRDS("data/Raw_Data/concat/RNA_fc_df.RDS")
RNA_Metadata <- readRDS("data/Raw_Data/concat/RNA_Metadata.RDS")
marker_genes <- readRDS("data/Raw_Data/concat/marker_genes.RDS")

RNA_fc <- readRDS("data/QC/concat/RNA_fc.RDS")
RNA_log2cpm <- readRDS("data/QC/concat/RNA_log2cpm.RDS")

Filt_RMG0_RNA_fc <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc.RDS")
Filt_RMG0_RNA_log2cpm <-readRDS("data/QC/concat/RNA_log2cpm_RMG0.RDS")

Cor_Filt_RMG0_RNA_log2cpm <- readRDS("data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm.RDS")
Cor_metadata <- readRDS("data/QC/concat/Cor_RNA_metadata.RDS")
ann_colors <- readRDS("data/QC/concat/ann_colors.RDS")

RNA_Metadata_No4 <- readRDS("data/QC/concat/RNA_Metatdata_No4.RDS")
Filt_RMG0_RNA_fc_NoD4 <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD4.RDS")
Filt_RMG0_RNA_log2cpm_NoD4 <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD4.RDS")

Cor_metadata_No4 <- readRDS("data/QC/Cor_metadata_No4.RDS")
Cor_Filt_RMG0_RNA_log2cpm_NoD4 <- readRDS("data/QC/Cor_Filt_RMG0_RNA_log2cpm_NoD4.RDS")
ann_colors_No4 <- readRDS("data/QC/ann_colors_no4.RDS")
RNA_Metadata_NoD4_NoRep <- readRDS("data/DGE/Trajectory/RNA_Metadata_NoD4_NoRep.RDS")

Cor_metadata_No5 <-readRDS("data/QC/concat/Cor_metadata_No5.RDS")
Cor_Filt_RMG0_RNA_log2cpm_NoD5 <-readRDS("data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD5.RDS")
ann_colors_No5 <-readRDS("data/QC/concat/ann_colors_no5.RDS")
```


```{r Setting_Up_Data, results="hide"}

RNA_Metadata <- read_excel("~/diff_timeline_tes/RNA/RNA_Metadata.xlsx")
counts_table <- read.delim("~/diff_timeline_tes/RNA/rna_concat/featureCounts/all_counts.txt")
marker_genes <- read.delim("~/diff_timeline_tes/RNA/CM_Diff_PurityPanel.txt")

RNA_fc <- counts_table %>%
  filter(Geneid != "#") %>%
  filter(Geneid != "Geneid") %>%
  column_to_rownames("Geneid")

# #Rename column Names to More Useful Info
col_names <- RNA_Metadata$SampleName
colnames(RNA_fc) <- col_names
dim(RNA_fc)

ensembl_ids_unfilt <- rownames(RNA_fc)
entrez_ids_unfilt <- mapIds(org.Hs.eg.db,
                            keys = ensembl_ids_unfilt,
                            column = "ENTREZID",
                            keytype = "ENSEMBL",
                            multiVals = "first")
symbol_ids_unfilt <- mapIds(org.Hs.eg.db,
                            keys = ensembl_ids_unfilt,
                            column = "SYMBOL",
                            keytype = "ENSEMBL",
                            multiVals = "first")

RNA_fc_df <- as.data.frame(RNA_fc)
RNA_fc_df <- RNA_fc_df %>%
  rownames_to_column(var = "Ensemble") %>%
  dplyr::mutate(
    Entrez_ID = entrez_ids_unfilt,
    Symbol    = symbol_ids_unfilt
  ) %>%
  dplyr::select(
    Ensemble,        # 1st column
    Entrez_ID,       # 2nd column
    Symbol,          # 3rd column
    everything()     # rest unchanged
  )

rn <- rownames(RNA_fc)

RNA_fc <- as.data.frame(
  lapply(RNA_fc, function(x) as.numeric(as.character(x)))
)

rownames(RNA_fc) <- rn

# saveRDS(RNA_fc,"data/QC/concat/RNA_fc.RDS")
# saveRDS(RNA_fc_df,"data/Raw_Data/concat/RNA_fc_df.RDS")
# saveRDS(RNA_Metadata,"data/Raw_Data/concat/RNA_Metadata.RDS")
# saveRDS(marker_genes,"data/Raw_Data/concat/marker_genes.RDS")
```

```{r RNASeq_Statistics_data}
total_reads_df <- RNA_fc %>%
  as.data.frame() %>%
  mutate(Gene = rownames(.)) %>%
  dplyr::select(-Gene) %>%
  summarise(across(everything(), \(x) sum(x, na.rm = TRUE))) %>%
  pivot_longer(
    cols = everything(),
    names_to = "Sample",
    values_to = "Total_Counts"
  ) %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))

day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")

total_reads_df <- total_reads_df %>%
  mutate(
    Timepoint = factor(Timepoint, levels = day_levels, ordered = TRUE),

    # force species order: chimp first, human second
    Species = factor(Species, levels = c("C", "H")),

    Individual_Color = ann_colors$individual_cor[Individual]
  ) %>%
  arrange(Species, Individual, Timepoint) %>%
  mutate(Sample = factor(Sample, levels = Sample))
```

```{r RNASeq_perSample_graph, fig.height=6,fig.width=12}
library(ggplot2)

ggplot(total_reads_df, aes(x = Sample, y = Total_Reads, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Total Reads per Sample",
    x = "Individual",
    y = "Total Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Sample, y = Mapped_Reads, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Mapped Reads per Sample",
    x = "Individual",
    y = "Mapped Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Sample, y = Percent_Mapped, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Percent Mapping per Sample",
    x = "Individual",
    y = "Percent Mapping",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Sample, y = Usable_Fragments, fill = Timepoint)) +
  geom_col() +
  geom_text(aes(label = Individual, color = Individual), 
            y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "top") +
  labs(
    title = "Usable Fragments per Sample",
    x = "Individual",
    y = "Number Fragments",
    fill = "Timepoint",
    color = "Individual"
  )

```
```{r RNASeq_perSpecies_graph, fig.height=6,fig.width=12}
ggplot(total_reads_df, aes(x = Species, y = Total_Reads)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Total Reads per Species",
    x = "Species",
    y = "Total_Reads",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Species, y = Mapped_Reads)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Mapped Reads per Species",
    x = "Species",
    y = "Mapped_Reads",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Species, y = Percent_Mapped)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Percent of Reads Mapped per Species",
    x = "Species",
    y = "Percent of reads Mapping",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Species, y = Usable_Fragments)) +
  geom_boxplot(fill = "#CCCCCC", alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +
  scale_color_manual(values = ann_colors$individual_cor) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "top") +
  labs(
    title = "Usable Fragments per Species",
    x = "Species",
    y = "Number of Fragments",
    color = "Individual"
  )
  
```

```{r RNASeq_perDaybySpecies_graph, fig.height=6,fig.width=12}

ggplot(total_reads_df, aes(x = Timepoint, y = Total_Reads)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Total Reads per Day by Species",
    x = "Day",
    y = "Total Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Timepoint, y = Mapped_Reads)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Mapped Reads per Day by Species",
    x = "Day",
    y = "Mapped Reads",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Timepoint, y = Percent_Mapped)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Percent of Reads Mapping per Day by Species",
    x = "Day",
    y = "Percent_Mapped",
    fill = "Timepoint",
    color = "Individual"
  )

ggplot(total_reads_df, aes(x = Timepoint, y = Usable_Fragments)) +
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +
  scale_fill_manual(values = ann_colors$timepoint_cor) +
  scale_color_manual(values = ann_colors$individual_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Usable Fragments per Day by Species",
    x = "Day",
    y = "Number of Fragments",
    fill = "Timepoint",
    color = "Individual"
  )
```

```{r RNASeq_perIndividualbySpecies_graph, fig.height=6,fig.width=12}
ggplot(total_reads_df, aes(x = Individual, y = Total_Reads)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Total Reads per Individual by Species",
    x = "Individual",
    y = "Total Reads",
    fill = "Individual",
    color = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Individual, y = Mapped_Reads)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Mapped Reads per Individual by Species",
    x = "Individual",
    y = "Mapped Reads",
    fill = "Individual",
    color = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Individual, y = Percent_Mapped)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Percentage of Mapped Reads per Individual by Species",
    x = "Individual",
    y = "Percentage of Mapped Reads",
    fill = "Individual",
    color = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Individual, y = Usable_Fragments)) +
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +
  facet_wrap(~Species, scales = "free_x") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "top") +
  labs(
    title = "Usable Fragments per Individual by Species",
    x = "Individual",
    y = "Number of Fragments",
    fill = "Individual",
    color = "Timepoint"
  )
```

```{r RNASeq_Purities,results="hide"}
# -----------------------------
# 1. Prepare long-format data
# -----------------------------
day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")
marker_levels <- c("OCT3/4", "Brachy", "ISL-1", "TNNT-2")

RNA_Metadata_NoRep <- RNA_Metadata %>%
  dplyr::filter(!SampleName %in% c(
    "H20682R_Day0",
    "H20682R_Day2",
    "H20682R_Day5",
    "H20682R_Day30"
  ))

df_long_all <- RNA_Metadata_NoRep %>%
  dplyr::select(Individual,Cond, `OCT3/4`, Brachy, `ISL-1`, `TNNT-2`) %>%
  mutate(
    `OCT3/4` = as.numeric(`OCT3/4`),
    Brachy = as.numeric(Brachy),
    `ISL-1` = as.numeric(`ISL-1`),
    `TNNT-2` = as.numeric(`TNNT-2`),
    Group = ifelse(grepl("^H_", Cond), "H", "C")
  ) %>%
  pivot_longer(
    cols = c(`OCT3/4`, Brachy, `ISL-1`, `TNNT-2`),
    names_to = "Marker",
    values_to = "Percent_Positive"
  ) %>%
  mutate(
    Day = gsub(".*_(Day\\d+)$", "\\1", Cond),
    Day = factor(Day, levels = day_levels, ordered = TRUE),
    Marker = factor(Marker, levels = marker_levels, ordered = TRUE)
  )

# -----------------------------
# 2. Compute summary with SEM
# -----------------------------
summary_df <- df_long_all %>%
  group_by(Marker, Day, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD = sd(Percent_Positive, na.rm = TRUE),
    N = sum(!is.na(Percent_Positive)),
    SEM = SD / sqrt(N),
    .groups = "drop"
  )
```

```{r RNASeq_Purities_graph, fig.height=6,fig.width=12}
# -----------------------------
# 3. Plot lines over time with SEM error bars
# -----------------------------
library(dplyr)
library(scales)

ggplot(summary_df,
       aes(x = Day, y = Mean,
           linetype = Group,
           group = Group)) +

  # Individual points
  geom_point(
    data = df_long_all,
    aes(
      x = Day,
      y = Percent_Positive,
      color = Individual,
      shape = Group
    ),
    size = 2.5,
    alpha = 0.9,
    position = position_jitter(width = 0.08, height = 0)
  ) +

  # Mean line (black, texture = species)
  geom_line(
    linewidth = 0.5,
    color = "black"
  ) +

  # Mean point (black)
  geom_point(
    size = 0.5,
    color = "black"
  ) +

  # Error bars (black)
  geom_errorbar(
    aes(ymin = Mean - SD, ymax = Mean + SD),
    width = 0.2,
    color = "black"
  ) +

  facet_wrap(~ Marker, nrow = 1) +

  # species as line texture
  scale_linetype_manual(
    values = c(
      "H" = "solid",
      "C" = "dashed"
    ),
    name = "Species"
  ) +

  # species as shape
  scale_shape_manual(
    values = c(
      "H" = 17,  # triangle
      "C" = 16   # circle
    ),
    name = "Species"
  ) +

  # individual colors from your manual palette
  scale_color_manual(
    values = ann_colors$individual_cor,
    name = "Individual"
  ) +

  # Use coord_cartesian instead of scale_y_continuous to avoid dropped points
  coord_cartesian(ylim = c(0, 100)) +

  labs(
    title = "Mean Percent Positive Across Timepoints for Each Marker",
    x = "Day",
    y = "Mean Percent Positive (%)",
    caption = "Color = individual, shape/line = species, error bars = SD"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    plot.caption = element_text(hjust = 0, face = "italic", size = 10)
  )
```

```{r RNASeq_Purities_No4,results="hide"}
# -----------------------------
# 1. Prepare long-format data
# -----------------------------
day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")
marker_levels <- c("OCT3/4", "Brachy", "ISL-1", "TNNT-2")

RNA_Metadata_NoD4_NoRep <- RNA_Metadata %>%
  dplyr::filter(Timepoint != "Day4") %>%
  dplyr::filter(!SampleName %in% c(
    "H20682R_Day0",
    "H20682R_Day2",
    "H20682R_Day5",
    "H20682R_Day30"
  ))

df_long_No4 <- RNA_Metadata_NoD4_NoRep %>%
  dplyr::select(Individual,Cond, `OCT3/4`, Brachy, `ISL-1`, `TNNT-2`) %>%
  mutate(
    `OCT3/4` = as.numeric(`OCT3/4`),
    Brachy = as.numeric(Brachy),
    `ISL-1` = as.numeric(`ISL-1`),
    `TNNT-2` = as.numeric(`TNNT-2`),
    Group = ifelse(grepl("^H_", Cond), "H", "C")
  ) %>%
  pivot_longer(
    cols = c(`OCT3/4`, Brachy, `ISL-1`, `TNNT-2`),
    names_to = "Marker",
    values_to = "Percent_Positive"
  ) %>%
  mutate(
    Day = gsub(".*_(Day\\d+)$", "\\1", Cond),
    Day = factor(Day, levels = day_levels, ordered = TRUE),
    Marker = factor(Marker, levels = marker_levels, ordered = TRUE)
  )

# -----------------------------
# 2. Compute summary with SEM
# -----------------------------
summary_df_No4 <- df_long_No4 %>%
  group_by(Marker, Day, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD = sd(Percent_Positive, na.rm = TRUE),
    N = sum(!is.na(Percent_Positive)),
    SEM = SD / sqrt(N),
    .groups = "drop"
  )
```


```{r RNASeq_Purities_graph_No4_graph, fig.height=6,fig.width=12}
# -----------------------------
# 3. Plot lines over time with SEM error bars
# -----------------------------
library(dplyr)
library(scales)

ggplot(summary_df_No4,
       aes(x = Day, y = Mean,
           linetype = Group,
           group = Group)) +

  # Individual points
  geom_point(
    data = df_long_No4,
    aes(
      x = Day,
      y = Percent_Positive,
      color = Individual,
      shape = Group
    ),
    size = 2.5,
    alpha = 0.9,
    position = position_jitter(width = 0.08, height = 0)
  ) +

  # Mean line (black, texture = species)
  geom_line(
    linewidth = 0.5,
    color = "black"
  ) +

  # Mean point (black)
  geom_point(
    size = 0.5,
    color = "black"
  ) +

  # Error bars (black)
  geom_errorbar(
    aes(ymin = Mean - SD, ymax = Mean + SD),
    width = 0.2,
    color = "black"
  ) +

  facet_wrap(~ Marker, nrow = 1) +

  # species as line texture
  scale_linetype_manual(
    values = c(
      "H" = "solid",
      "C" = "dashed"
    ),
    name = "Species"
  ) +

  # species as shape
  scale_shape_manual(
    values = c(
      "H" = 17,  # triangle
      "C" = 16   # circle
    ),
    name = "Species"
  ) +

  # individual colors from your manual palette
  scale_color_manual(
    values = ann_colors$individual_cor,
    name = "Individual"
  ) +

  # Use coord_cartesian instead of scale_y_continuous to avoid dropped points
  coord_cartesian(ylim = c(0, 100)) +

  labs(
    title = "Mean Percent Positive Across Timepoints for Each Marker",
    x = "Day",
    y = "Mean Percent Positive (%)",
    caption = "Color = individual, shape/line = species, error bars = SD"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    plot.caption = element_text(hjust = 0, face = "italic", size = 10)
  )
```

```{r RNASeq_Purities_No5,results="hide"}
# -----------------------------
# 1. Prepare long-format data
# -----------------------------
day_levels <- c("Day0","Day2","Day4","Day5","Day15","Day30")
marker_levels <- c("OCT3/4", "Brachy", "ISL-1", "TNNT-2")

RNA_Metadata_NoD5_NoRep <- RNA_Metadata %>%
  dplyr::filter(Timepoint != "Day5") %>%
  dplyr::filter(!SampleName %in% c(
    "H20682R_Day0",
    "H20682R_Day2",
    "H20682R_Day5",
    "H20682R_Day30"
  ))

df_long_No5 <- RNA_Metadata_NoD5_NoRep %>%
  dplyr::select(Individual,Cond, `OCT3/4`, Brachy, `ISL-1`, `TNNT-2`) %>%
  mutate(
    `OCT3/4` = as.numeric(`OCT3/4`),
    Brachy = as.numeric(Brachy),
    `ISL-1` = as.numeric(`ISL-1`),
    `TNNT-2` = as.numeric(`TNNT-2`),
    Group = ifelse(grepl("^H_", Cond), "H", "C")
  ) %>%
  pivot_longer(
    cols = c(`OCT3/4`, Brachy, `ISL-1`, `TNNT-2`),
    names_to = "Marker",
    values_to = "Percent_Positive"
  ) %>%
  mutate(
    Day = gsub(".*_(Day\\d+)$", "\\1", Cond),
    Day = factor(Day, levels = day_levels, ordered = TRUE),
    Marker = factor(Marker, levels = marker_levels, ordered = TRUE)
  )

# -----------------------------
# 2. Compute summary with SEM
# -----------------------------
summary_df_No5 <- df_long_No5 %>%
  group_by(Marker, Day, Group) %>%
  summarise(
    Mean = mean(Percent_Positive, na.rm = TRUE),
    SD = sd(Percent_Positive, na.rm = TRUE),
    N = sum(!is.na(Percent_Positive)),
    SEM = SD / sqrt(N),
    .groups = "drop"
  )
```

```{r RNASeq_Purities_graph_No5_graph, fig.height=6,fig.width=12}
# -----------------------------
# 3. Plot lines over time with SEM error bars
# -----------------------------
library(dplyr)
library(scales)

ggplot(summary_df_No5,
       aes(x = Day, y = Mean,
           linetype = Group,
           group = Group)) +

  # Individual points
  geom_point(
    data = df_long_No5,
    aes(
      x = Day,
      y = Percent_Positive,
      color = Individual,
      shape = Group
    ),
    size = 2.5,
    alpha = 0.9,
    position = position_jitter(width = 0.08, height = 0)
  ) +

  # Mean line (black, texture = species)
  geom_line(
    linewidth = 0.5,
    color = "black"
  ) +

  # Mean point (black)
  geom_point(
    size = 0.5,
    color = "black"
  ) +

  # Error bars (black)
  geom_errorbar(
    aes(ymin = Mean - SD, ymax = Mean + SD),
    width = 0.2,
    color = "black"
  ) +

  facet_wrap(~ Marker, nrow = 1) +

  # species as line texture
  scale_linetype_manual(
    values = c(
      "H" = "solid",
      "C" = "dashed"
    ),
    name = "Species"
  ) +

  # species as shape
  scale_shape_manual(
    values = c(
      "H" = 17,  # triangle
      "C" = 16   # circle
    ),
    name = "Species"
  ) +

  # individual colors from your manual palette
  scale_color_manual(
    values = ann_colors$individual_cor,
    name = "Individual"
  ) +

  # Use coord_cartesian instead of scale_y_continuous to avoid dropped points
  coord_cartesian(ylim = c(0, 100)) +

  labs(
    title = "Mean Percent Positive Across Timepoints for Each Marker",
    x = "Day",
    y = "Mean Percent Positive (%)",
    caption = "Color = individual, shape/line = species, error bars = SD"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    plot.caption = element_text(hjust = 0, face = "italic", size = 10)
  )
```

```{r RNASeq_FeatureCounts_Box_Unfiltered, fig.height=6,fig.width=12}
#####Unfiltered####
RNA_log2cpm <- cpm(RNA_fc, log = TRUE)

hist(RNA_log2cpm,  main = "Histogram of all counts (unfiltered)",
     xlab =expression("Log"[2]*" counts-per-million"), col =4 )

boxplot(RNA_log2cpm, main = "Boxplots of log cpm per sample
          (unfiltered)", xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_names),  # positions (one per sample)
     labels = col_names,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.6)        # shrink label size
# saveRDS(RNA_log2cpm,"data/QC/concat/RNA_log2cpm.RDS")
```



```{r RNASeq_FeatureCounts_RMG0, fig.height=6,fig.width=12}
#####RowMu>0####
row_means <- rowMeans(RNA_log2cpm)
Filt_RMG0_RNA_fc <- RNA_fc[row_means >0,]

# saveRDS(Filt_RMG0_RNA_fc,"data/QC/concat/Filt_RMG0_RNA_fc.RDS")

Filt_RMG0_RNA_log2cpm <- cpm(Filt_RMG0_RNA_fc,log=TRUE)

# saveRDS(Filt_RMG0_RNA_log2cpm,"data/QC/concat/Filt_RMG0_RNA_log2cpm.RDS")

hist(Filt_RMG0_RNA_log2cpm, main = "Histogram of filtered counts using rowMeans > 0 method",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

```

```{r RNASeq_FeatureCounts_Box_RMG0, fig.height=6,fig.width=12}
boxplot(Filt_RMG0_RNA_log2cpm, main = "Boxplots of log cpm per sample (RowMeans>0)",xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_names),  # positions (one per sample)
     labels = col_names,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.6)        # shrink label size

```

```{r RNASeq_Counts_graph, fig.height=6,fig.width=12}
library(ggplot2)
library(dplyr)

# Define ordered day factor
day_levels <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

total_reads_df <- total_reads_df %>%
  mutate(
    # Order Timepoint for bars
    Timepoint = factor(Timepoint, levels = day_levels, ordered = TRUE),
    
    # Individual text color
    Individual_Color = ann_colors$individual_cor[Individual]
  ) %>%
  # Order Sample for x-axis: first by Individual, then by Day
  arrange(Individual, Timepoint) %>%
  mutate(Sample = factor(Sample, levels = Sample))  # preserve order in ggplot

# Plot
ggplot(total_reads_df, aes(x = Sample, y = Total_Counts, fill = Timepoint)) +
  
  # Bars colored by Timepoint
  geom_col() +

  # Annotate Individual names under bars, colored by individual
  geom_text(
    aes(label = Individual, color = Individual_Color),
    y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3
  ) +

  # Manual Timepoint colors
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Use exact color for individual labels
  scale_color_identity() +

  # Facet by Species if desired
  facet_grid(~Species, scales = "free_x", space = "free_x") +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_blank(),  # hide default X labels
    axis.ticks.x = element_blank(),
    legend.position = "top"
  ) +

  labs(
    title = "Counts per Sample",
    x = "Individual (bars grouped by individual, ordered by day)",
    y = "Total Counts",
    fill = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Species, y = Total_Counts)) +
  
  # Boxplot for each species
  geom_boxplot(aes(fill = Species), alpha = 0.3, outlier.shape = NA) + 
  
  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Optional: species fill colors (light grey / black)
  scale_fill_manual(values = c("H" = "#17171717", "C" = "#17171717")) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top"
  ) +

  labs(
    title = "Counts per Species",
    x = "Species",
    y = "Total Counts",
    color = "Individual",
    fill = "Species"
  )


ggplot(total_reads_df, aes(x = Timepoint, y = Total_Counts)) +
  
  # Boxplot per day
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +

  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Use timepoint colors for boxplots
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Separate x-axis by species
  facet_wrap(~Species, scales = "free_x") +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Counts per Day by Species",
    x = "Day",
    y = "Total Counts",
    color = "Individual",
    fill = "Timepoint"
  )


# Plot
ggplot(total_reads_df, aes(x = Individual, y = Total_Counts)) +
  
  # Boxplots colored by individual
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +

  # Overlay points colored by Timepoint
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +

  # Use manual colors
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +

  # Facet by species
  facet_wrap(~Species, scales = "free_x", nrow = 1) +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Counts per Individual by Species",
    x = "Individual",
    y = "Total Counts",
    fill = "Individual",
    color = "Timepoint"
  )
```

```{r RNASeq_TotalReads_dataset}
library(tidyverse)

total_reads_df <- RNA_fc %>%
  as.data.frame() %>%
  mutate(Gene = rownames(.)) %>%
  dplyr::select(-Gene) %>%
  summarise(across(everything(), \(x) sum(x, na.rm = TRUE))) %>%
  pivot_longer(
    cols = everything(),
    names_to = "Sample",
    values_to = "Total_Reads"
  ) %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))
```

```{r RNASeq_TotalReads_graph, fig.height=6,fig.width=12}
library(ggplot2)
library(dplyr)

# Define ordered day factor
day_levels <- c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")

total_reads_df <- total_reads_df %>%
  mutate(
    # Order Timepoint for bars
    Timepoint = factor(Timepoint, levels = day_levels, ordered = TRUE),
    
    # Individual text color
    Individual_Color = ann_colors$individual_cor[Individual]
  ) %>%
  # Order Sample for x-axis: first by Individual, then by Day
  arrange(Individual, Timepoint) %>%
  mutate(Sample = factor(Sample, levels = Sample))  # preserve order in ggplot

# Plot
ggplot(total_reads_df, aes(x = Sample, y = Total_Reads.x, fill = Timepoint)) +
  
  # Bars colored by Timepoint
  geom_col() +

  # Annotate Individual names under bars, colored by individual
  geom_text(
    aes(label = Individual, color = Individual_Color),
    y = 0, angle = 90, hjust = 1, vjust = 0.5, size = 3
  ) +

  # Manual Timepoint colors
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Use exact color for individual labels
  scale_color_identity() +

  # Facet by Species if desired
  facet_grid(~Species, scales = "free_x", space = "free_x") +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_blank(),  # hide default X labels
    axis.ticks.x = element_blank(),
    legend.position = "top"
  ) +

  labs(
    title = "Total Reads per Sample",
    x = "Individual (bars grouped by individual, ordered by day)",
    y = "Total Reads",
    fill = "Timepoint"
  )

ggplot(total_reads_df, aes(x = Species, y = Total_Reads.x)) +
  
  # Boxplot for each species
  geom_boxplot(aes(fill = Species), alpha = 0.3, outlier.shape = NA) + 
  
  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.2, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Optional: species fill colors (light grey / black)
  scale_fill_manual(values = c("H" = "#17171717", "C" = "#17171717")) +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top"
  ) +

  labs(
    title = "Total Reads per Species",
    x = "Species",
    y = "Total Reads",
    color = "Individual",
    fill = "Species"
  )


ggplot(total_reads_df, aes(x = Timepoint, y = Total_Reads.x)) +
  
  # Boxplot per day
  geom_boxplot(aes(fill = Timepoint), alpha = 0.3, outlier.shape = NA) +

  # Overlay individual points colored by individual
  geom_jitter(aes(color = Individual), width = 0.15, size = 3) +

  # Use individual colors
  scale_color_manual(values = ann_colors$individual_cor) +

  # Use timepoint colors for boxplots
  scale_fill_manual(values = ann_colors$timepoint_cor) +

  # Separate x-axis by species
  facet_wrap(~Species, scales = "free_x") +

  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Total Reads per Day by Species",
    x = "Day",
    y = "Total Reads",
    color = "Individual",
    fill = "Timepoint"
  )


# Plot
ggplot(total_reads_df, aes(x = Individual, y = Total_Reads.x)) +
  
  # Boxplots colored by individual
  geom_boxplot(aes(fill = Individual), alpha = 0.3, outlier.shape = NA) +

  # Overlay points colored by Timepoint
  geom_jitter(aes(color = Timepoint), width = 0.2, size = 3) +

  # Use manual colors
  scale_fill_manual(values = ann_colors$individual_cor) +
  scale_color_manual(values = ann_colors$timepoint_cor) +

  # Facet by species
  facet_wrap(~Species, scales = "free_x", nrow = 1) +

  # Theme
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +

  labs(
    title = "Total Reads per Individual by Species",
    x = "Individual",
    y = "Total Reads",
    fill = "Individual",
    color = "Timepoint"
  )
```



```{r RNASeq_FeatureCounts_Cor_RMG0}
######Cor_HeatMap####
Cor_Filt_RMG0_RNA_log2cpm <- cor(Filt_RMG0_RNA_log2cpm, method = "spearman")
individual <- RNA_Metadata$Individual
species <- RNA_Metadata$Species
timepoint <- RNA_Metadata$Timepoint
timepoint <- factor(timepoint,levels = c("Day0","Day2","Day4","Day5","Day15","Day30"))
Cor_metadata <- data.frame(
  sample_cor = colnames(Filt_RMG0_RNA_log2cpm),
  species_cor = species,
  timepoint_cor = timepoint,
  individual_cor = individual
)


ann_colors <- list(
  timepoint_cor = c(
    "Day0" = "#883268",   # Purple
    "Day2" = "#3E7274",  # blue
    "Day4" = "#5AAA464D",  # light green
    "Day5" = "#94C47D",  # Green
    "Day15" = "#C03830",  # red
    "Day30" = "#830C05"  # dark red
  ),
  species_cor = c(
    "H" = "black",  # black
    "C" = "white"   # white
  ),
  individual_cor = c(
    H1 = "#091638", #Blue-Green Darkest
    H2 = "#11185B",
    H3 = "#0F2C71",
    H4 = "#0D568F",
    H4R = "#0D568F",
    H5 = "#1D8296",
    H6 = "#46A389",
    H7 = "#9DD484", #Blue-Green Lightest
    C1 = "#340702", #Brown-Orange darkest
    C2 = "#5D0B02",
    C3 = "#951302",
    C4 = "#D32804",
    C5 = "#F74019",
    C6 = "#FA7A38",
    C7 = "#FCC598"
    
  )
)
rownames(Cor_metadata) <- Cor_metadata$sample_cor

# saveRDS(Cor_Filt_RMG0_RNA_log2cpm, "data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm.RDS")
# saveRDS(Cor_metadata, "data/QC/concat/Cor_RNA_metadata.RDS")
# saveRDS(ann_colors,"data/QC/concat/ann_colors.RDS")

```

```{r RNASeq_FeatureCounts_HeatMap_RMG0,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation \n(Spearman-log2CPM-RowMeans>0)")
)
```

```{r RNASeq_FeatureCounts_RMG0_No4}

####Subset####
RNA_Metadata_No4 <- RNA_Metadata %>% 
 filter(Timepoint != "Day4")

RNA_fc_NoD4 <- RNA_fc %>% 
  dplyr::select(-ends_with("_Day4"))

RNA_log2cpm_NoD4 <- cpm(RNA_fc_NoD4,log=TRUE)
dim(RNA_log2cpm_NoD4)
dim(RNA_fc)
row_means_NoD4 <- rowMeans(RNA_log2cpm_NoD4)
Filt_RMG0_RNA_fc_NoD4 <- RNA_fc_NoD4[row_means_NoD4 >0,]
dim(Filt_RMG0_RNA_fc_NoD4)
Filt_RMG0_RNA_log2cpm_NoD4 <- cpm(Filt_RMG0_RNA_fc_NoD4,log=TRUE)

# saveRDS(RNA_Metadata_No4,"data/QC/concat/RNA_Metatdata_No4.RDS")
# saveRDS(Filt_RMG0_RNA_fc_NoD4,"data/QC/concat/Filt_RMG0_RNA_fc_NoD4.RDS")
# saveRDS(Filt_RMG0_RNA_log2cpm_NoD4, "data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD4.RDS")

```

```{r rRNASeq_FeatureCounts_Cor_RMG0_No4}
######Cor_HeatMap####
Cor_Filt_RMG0_RNA_log2cpm_NoD4 <- cor(Filt_RMG0_RNA_log2cpm_NoD4, method = "spearman")

Cor_metadata_No4 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day4")

ann_colors_No4 <- ann_colors
ann_colors_No4$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day4"
]

# saveRDS(Cor_metadata_No4, "data/QC/concat/Cor_metadata_No4.RDS")
# saveRDS(Cor_Filt_RMG0_RNA_log2cpm_NoD4, "data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD4.RDS")
# saveRDS(ann_colors_No4,"data/QC/concat/ann_colors_no4.RDS")
```


```{r rRNASeq_FeatureCounts_HeatMap_RMG0_No4,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm_NoD4,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No4[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2CPM-RowMeans>0-NoDay4)")
)
```
```{r RNASeq_FeatureCounts_RMG0_No5}

####Subset####
RNA_Metadata_No5 <- RNA_Metadata %>% 
 filter(Timepoint != "Day5")

RNA_fc_NoD5 <- RNA_fc %>% 
  dplyr::select(-ends_with("_Day5"))

RNA_log2cpm_NoD5 <- cpm(RNA_fc_NoD5,log=TRUE)
dim(RNA_log2cpm_NoD5)
dim(RNA_fc)
row_means_NoD5 <- rowMeans(RNA_log2cpm_NoD5)
Filt_RMG0_RNA_fc_NoD5 <- RNA_fc_NoD5[row_means_NoD5 >0,]
dim(Filt_RMG0_RNA_fc_NoD5)
Filt_RMG0_RNA_log2cpm_NoD5 <- cpm(Filt_RMG0_RNA_fc_NoD5,log=TRUE)

# saveRDS(RNA_Metadata_No5,"data/QC/concat/RNA_Metatdata_No5.RDS")
# saveRDS(Filt_RMG0_RNA_fc_NoD5,"data/QC/concat/Filt_RMG0_RNA_fc_NoD5.RDS")
# saveRDS(Filt_RMG0_RNA_log2cpm_NoD5, "data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD5.RDS")

```

```{r rRNASeq_FeatureCounts_Cor_RMG0_No5}
######Cor_HeatMap####
Cor_Filt_RMG0_RNA_log2cpm_NoD5 <- cor(Filt_RMG0_RNA_log2cpm_NoD5, method = "spearman")

Cor_metadata_No5 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day5")

ann_colors_No5 <- ann_colors
ann_colors_No5$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day5"
]

# saveRDS(Cor_metadata_No5, "data/QC/concat/Cor_metadata_No5.RDS")
# saveRDS(Cor_Filt_RMG0_RNA_log2cpm_NoD5, "data/QC/concat/Cor_Filt_RMG0_RNA_log2cpm_NoD5.RDS")
# saveRDS(ann_colors_No5,"data/QC/concat/ann_colors_no5.RDS")
```


```{r rRNASeq_FeatureCounts_HeatMap_RMG0_No5,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_RNA_log2cpm_NoD5,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No5[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No5,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2CPM-RowMeans>0-NoDay5)")
)
```


```{r RNASeq_MarkerGenes_dataset, fig.height=6,fig.width=12}
markers <- marker_genes$Ensembl.ID

log2cpm_long <- RNA_log2cpm %>%
  as.data.frame() %>%
  rownames_to_column("Ensembl.ID") %>%
  filter(Ensembl.ID %in% markers) %>% 
  pivot_longer(
    cols = -Ensembl.ID,
    names_to = "Sample",
    values_to = "log2CPM"
  )

log2cpm_long <- log2cpm_long %>%
  left_join(RNA_Metadata, by = c("Sample" = "SampleName"))

log2cpm_long <- log2cpm_long %>%
  left_join(marker_genes, by = "Ensembl.ID")

log2cpm_long$Timepoint <- factor(
  log2cpm_long$Timepoint,
  levels = c("Day0", "Day2", "Day4", "Day5", "Day15", "Day30")
)

log2cpm_long_NoR <- log2cpm_long %>% 
  filter(Individual != "H4R")

library(dplyr)

mean_df <- log2cpm_long_NoR %>%
  group_by(Stage, Timepoint, Species) %>%
  summarise(
    mean_log2CPM = mean(log2CPM),
    .groups = "drop"
  )

log2cpm_long_NoR$Stage <- factor(
  log2cpm_long_NoR$Stage,
  levels = c(
    "Pluripotency",
    "Mesoderm",
    "CardiacMesoderm",
    "CardiacProgenitors",
    "EarlyCardiomyocytes",
    "MatureCardiomyocytes"
  )
)
```

```{r RNASeq_MarkerGenes_graph, fig.height=12,fig.width=12}
library(ggplot2)

ggplot(log2cpm_long_NoR, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
    aes(fill = Stage),
    alpha = 0.3,
    outlier.shape = NA
  ) +

  geom_line(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated, fig.height=12,fig.width=12}
library(ggplot2)

ggplot(log2cpm_long_NoR, aes(
  x = Timepoint,
  y = log2CPM
)) +

  geom_boxplot(
  aes(fill = Species, group = interaction(Timepoint, Species)),
  alpha = 0.3,
  outlier.shape = NA,
  position = position_dodge(width = 0.8)
  ) +
  
    scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      group = interaction(Stage, Species),
      linetype = Species
    ),
    color = "black",
    linewidth = 1.2
  ) +

  geom_point(
    data = mean_df,
    aes(
      x = Timepoint,
      y = mean_log2CPM,
      shape = Species
    ),
    color = "black",
    size = 2
  ) +

  scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  scale_shape_manual(values = c(
    C = 16,
    H = 17
  )) +

  facet_wrap(~ factor(Stage, levels = levels(log2cpm_long_NoR$Stage))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_pluri, fig.height=12,fig.width=12}
pluri_genes <- log2cpm_long_NoR %>%
  filter(Stage == "Pluripotency")

ggplot(pluri_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
     geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 3,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r RNASeq_MarkerGenes_graph_species_separated_meso, fig.height=12,fig.width=12}
meso_genes <- log2cpm_long_NoR %>%
  filter(Stage == "Mesoderm")

ggplot(meso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +

    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardmeso, fig.height=12,fig.width=12}
cardmeso_genes <- log2cpm_long_NoR %>%
  filter(Stage == "CardiacMesoderm")

ggplot(cardmeso_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardprog, fig.height=12,fig.width=12}
cardprog_genes <- log2cpm_long_NoR %>%
  filter(Stage == "CardiacProgenitors")

ggplot(cardprog_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_cardearly, fig.height=12,fig.width=12}
cardearly_genes <- log2cpm_long_NoR %>%
  filter(Stage == "EarlyCardiomyocytes")

ggplot(cardearly_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +
  
      scale_fill_manual(values = ann_colors$species_cor) +
  
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+

  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r RNASeq_MarkerGenes_graph_species_separated_cardlate, fig.height=12,fig.width=12}
cardlate_genes <- log2cpm_long_NoR %>%
  filter(Stage == "MatureCardiomyocytes")

ggplot(cardlate_genes, aes(x = Timepoint, y = log2CPM)) +

  geom_boxplot(
    aes(fill = Species, group = interaction(Timepoint, Species)),
    position = position_dodge(width = 0.8),
    alpha = 0.3,
    outlier.shape = NA
  ) +

  scale_fill_manual(values = ann_colors$species_cor) +
  
    geom_jitter(
  aes(color = Individual),
  position = position_jitterdodge(
    jitter.width = 0.15,
    dodge.width = 0.8
  ),
  size = 1,
  alpha = 0.6
) +
  
  scale_color_manual(values = ann_colors$individual_cor)+
  
  geom_line(
    stat = "summary",
    fun = mean,
    aes(group = Species, linetype = Species),
    position = position_dodge(width = 0.8),
    linewidth = 1
  ) +
  
    scale_linetype_manual(values = c(
    C = "dotted",
    H = "solid"
  )) +

  geom_point(
    stat = "summary",
    fun = mean,
    aes(shape = Species),
    position = position_dodge(width = 0.8),
    size = 2
  ) +

  facet_wrap(~ Gene, scales = "free_y") +

  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r RNASeq_MarkerGenes_graph_species_separated_checks, fig.height=12,fig.width=12}
counts_table_genes <- unique(counts_table$Geneid)
Expressed_Genes <- unique(TopTable_RNA_All$Gene)
marker_genes_ortho <- marker_genes %>% 
  filter(Ensembl.ID %in% counts_table_genes)
marker_genes_ortho_expressed <- marker_genes_ortho %>% 
  filter(Ensembl.ID %in% Expressed_Genes)
```

```{r Updating Website, eval = FALSE}

# git -> commit all changes
# git -> push
wflow_publish("analysis/RNA_CorrelationHeatMap_Ensemble.Rmd")

```


