---
title: "RNA_DGE_Interactions"
output: html_document
date: "2026-03-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{r Setting the Enviroment}

#loading libraries
library("tidyverse")
library("readxl")
library("readr")
library("ggrepel")
library("ggfortify")
library("patchwork")
library("eulerr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("ggVennDiagram")
library("ggrastr")
library("edgeR")
library("limma")
library("ggsignif")
library("dplyr")
library("purrr")
library("ggplot2")
library("tidyr")




#Loading R Objects Other WorkflowR
RNA_fc <- readRDS("data/QC/concat/RNA_fc.RDS")
RNA_log2cpm <- readRDS("data/QC/concat/RNA_log2cpm.RDS")

Filt_RMG0_RNA_fc <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc.RDS")
Filt_RMG0_RNA_log2cpm <-readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm.RDS")

Filt_RMG0_RNA_fc_NoD4 <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD4.RDS")
Filt_RMG0_RNA_log2cpm_NoD4 <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD4.RDS")

Filt_RMG0_RNA_fc_NoD5 <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD5.RDS")
Filt_RMG0_RNA_log2cpm_NoD5 <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD5.RDS")

RNA_Metadata <- readRDS("data/Raw_Data/concat/RNA_Metadata.RDS")
RNA_Metadata_NoD4 <- readRDS("data/QC/concat/RNA_Metatdata_No4.RDS")
RNA_Metadata_NoD5 <- readRDS("data/QC/concat/RNA_Metatdata_No5.RDS")

Filt_RMG0_RNA_fc_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_PerDay.RDS")
Filt_RMG0_RNA_log2cpm_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_PerDay.RDS")

Filt_RMG0_RNA_fc_NoD4_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD4_PerDay.RDS")
Filt_RMG0_RNA_log2cpm_NoD4_PerDay<- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD4_PerDay.RDS")

Filt_RMG0_RNA_fc_NoD5_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_fc_NoD5_PerDay.RDS")
Filt_RMG0_RNA_log2cpm_NoD5_PerDay <- readRDS("data/QC/concat/Filt_RMG0_RNA_log2cpm_NoD5_PerDay.RDS")

Filt_logcpm_G1_SpTp_RNA_fc <-readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_fc.RDS")
Filt_logcpm_G1_SpTp_RNA_log2cpm <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_log2cpm.RDS")
Filt_logcpm_G1_SpTp_RNA_fc_No4<- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_fc_No4.RDS")
Filt_logcpm_G1_SpTp_RNA_log2cpm_No4 <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_log2cpm_No4.RDS")
Filt_logcpm_G1_SpTp_RNA_fc_No5 <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_fc_No5.RDS")
Filt_logcpm_G1_SpTp_RNA_log2cpm_No5 <- readRDS("data/QC/concat/Filt_logcpm_G1_SpTp_RNA_log2cpm_No5.RDS")

Filt_FilterByExpression_RNA_fc <- readRDS("data/QC/concat/Filt_FilterByExpression_RNA_fc.RDS")
Filt_FilterByExpression_RNA_log2cpm <- readRDS("data/QC/concat/Filt_FilterByExpression_RNA_log2cpm.RDS")
Filt_FilterByExpression_RNA_fc_No5 <- readRDS("data/QC/concat/Filt_FilterByExpression_RNA_fc_No5.RDS")
Filt_FilterByExpression_RNA_log2cpm_No5<- readRDS("data/QC/concat/Filt_FilterByExpression_RNA_log2cpm_No5.RDS")
Filt_FilterByExpression_RNA_fc_No4 <- readRDS("data/QC/concat/Filt_FilterByExpression_RNA_fc_No4.RDS")
Filt_FilterByExpression_RNA_log2cpm_No4<- readRDS("data/QC/concat/Filt_FilterByExpression_RNA_log2cpm_No4.RDS")


#Loading R Objects from this WorflowR
dge_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/dge_lcpm1_4SpTp.RDS")
design_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/design_lcpm1_4SpTp.RDS")
v1_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/v1_lcpm1_4SpTp.RDS")
fit_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/fit_lcpm1_4SpTp.RDS")
fit2_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/fit2_lcpm1_4SpTp.RDS")
TopTable_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans/All/TopTable_lcpm1_4SpTp.RDS")
Comparison_names_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans/All/Comparison_names_lcpm1_4SpTp.RDS")
RNA_sets_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/RNA_sets_lcpm1_4SpTp.RDS")

Trajectory_Directions_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Trajectory_Directions_lcpm1_4SpTp.RDS")
Trajectory_go_results_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Trajectory_go_results_lcpm1_4SpTp.RDS")

Interaction_Directions_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Interaction_Directions_lcpm1_4SpTp.RDS")
Interaction_go_results_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Interaction_go_results_lcpm1_4SpTp.RDS")

Species_Directions_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Species_Directions_lcpm1_4SpTp.RDS")
Species_go_results_lcpm1_4SpTp <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Species_go_results_lcpm1_4SpTp.RDS")

# dge_RMGO_All <- readRDS("data/DGE/Species/concat/RowMeans/All/dge_RMGO_All.RDS")
# design_int_RMG0_All <- readRDS("data/DGE/Species/concat//RowMeans/All/design_int_RMG0_All.RDS")
# v1_RMG0_All <- readRDS("data/DGE/Species/concat/RowMeans/All/v1_RMG0_All.RDS")
# fit_RMG0_All <- readRDS("data/DGE/Species/concat/RowMeans/All/fit_RMG0_All.RDS")
# fit2_RMG0_All <- readRDS("data/DGE/Species/concat/RowMeans/All/fit2_RMG0_All.RDS")
# TopTable_RNA_All_RMGO_All <- readRDS("data/DGE/Species/concat/RowMeans/All/TopTable_RNA_All_RMGO_All.RDS")
# Comparison_names_RMGO_All <- readRDS("data/DGE/Species/concat/RowMeans/All/Comparison_names_RNA_All_RMGO_All.RDS")
# RNA_sets_RMG0_All <- readRDS("data/DGE/Species/concat/RowMeans/All/RNA_sets_RMG0_All.RDS")
# TopTable_RNA_Inter_Inter_RMG0_All <- readRDS("data/DGE/Species/concat/RowMeans/All/TopTable_RNA_Inter_RMG0_Al.RDS")
# Interaction_Directions_All <- readRDS("data/DGE/Species/concat/RowMeans/All/Interaction_Directions_All.RDS")
# 
# EnrichGo_Traj02_All <- readRDS("data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj02_All.RDS")
# EnrichGo_Traj24_All <- readRDS("data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj24_All.RDS")
# EnrichGo_Traj45_All <- readRDS("data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj45_All.RDS")
# EnrichGo_Traj515_All <- readRDS("data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj515_All.RDS")
# EnrichGo_Traj1530_All <- readRDS("data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj1530_All.RDS")
# 
# dge_RMGO_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/dge_RMGO_PerDay_All.RDS")
# design_int_RMG0_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/design_int_RMG0_All.RDS")
# v1_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/v1_RMG0_PerDay_All.RDS")
# fit_RMG0_PerDay_All <-readRDS("data/DGE/Species/concat/RowMeans_PerDay/fit_RMG0_PerDay_All.RDS")
# fit2_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/fit2_RMG0_PerDay_All.RDS")
# TopTable_RNA_All_RMGO_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans/All/TopTable_RNA_All_RMGO_PerDay_All.RDS")
# Comparison_names_RMGO_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans/All/Comparison_names_RNA_All_RMGO_PerDay_All.RDS")
# RNA_sets_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/RNA_sets_RMG0_PerDay_All.RDS")
# TopTable_RNA_Inter_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/TopTable_RNA_Traj_RMG0_PerDay_All.RDS")
# Interaction_Directions_RMG0_PerDay_All <-readRDS("data/DGE/Species/concat/RowMeans_PerDay/Interaction_Directions_RMG0_PerDay_All.RDS")
# Interaction_go_results_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Interaction_go_results_RMG0_PerDay_All.RDS")
# Trajectory_Directions_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/Trajectory_Directions_RMG0_PerDay_All.RDS")
# HTrajectory_Directions_RMG0_PerDay_All <- readRDS("data/DGE/Species/concat/RowMeans_PerDay/HTrajectory_Directions_RMG0_PerDay_All.RDS")

```

```{r Volcano_Plot_Function,Result="Hide",warning=FALSE, include = FALSE}
generate_volcano_plot <- function(toptable, title) {
  
  # #check for entrezid 
  # if(!"Entrez_ID" %in% colnames(toptable)) stop("Entrez_ID col not present")
  # 
  #make significance labels
  
  toptable <- toptable %>% 
    mutate(Significance = case_when(
      logFC > 0 & adj.P.Val < 0.05 ~ "Upregulated",
      logFC < 0 & adj.P.Val < 0.05 ~ "Downregulated",
      TRUE  ~ "Not Significant"
    ))
  
  #factor significance
  toptable$Significance <- factor(
    toptable$Significance, 
    levels = c("Upregulated", 
               "Not Significant", 
               "Downregulated")
  )
  
  #count genes in each category
  upgenes <- sum(toptable$Significance == "Upregulated")
  nsgenes <- sum(toptable$Significance == "Not Significant")
  downgenes <- sum(toptable$Significance == "Downregulated")
  
  
  #labels for legend
  legend_lab <- c(
    paste0("Upregulated: ", upgenes),
    paste0("Not Significant: ", nsgenes),
    paste0("Downregulated: ", downgenes)
  )
  
  #colors 
  color_map <- c("Upregulated" = "blue",
                 "Not Significant" = "grey30",
                 "Downregulated" = "red")
  
  #generate volcano plots
  p <- ggplot(toptable, aes(x = logFC, 
                            y = -log10(P.Value),
                            color = Significance)) +
    geom_point_rast(alpha = 0.8, size = 3) +
    scale_color_manual(values = color_map, 
                       labels = legend_lab,
                       breaks = c("Upregulated",
                                  "Not Significant", 
                                  "Downregulated"))  +
    xlim(-20,20) +
    labs(title = title, 
         x = expression("log"[2]*"FC"),
         y = expression("-log"[10]*"p-value")) +
    # theme_custom() +
    theme(legend.position = "right")
  
  return(p)
}


```

```{r FC_Plot_Function_sig, include = FALSE}

plot_cluster_fc_sig <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530","C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # ✅ Skip if no data
  if (nrow(df) == 0) {
    message(cluster_name, ": no data — skipping")
    return(NULL)
  }

  # ✅ Skip if only one comparison present
  if (length(unique(df$Comparisons)) < 2) {
    message(cluster_name, ": only one comparison — skipping stats")
    return(NULL)
  }

  # Stats
  kw <- kruskal.test(logFC ~ Comparisons, data = df)

  pw_kw <- pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH"
  )

  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    coord_cartesian(ylim = c(-2, 2)) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)
}

```

```{r FC_Plot_Function_sig_No4, include = FALSE}
plot_cluster_fc_sig_No4 <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day25","H_Day515","H_Day1530","C_Day02","C_Day25","C_Day515","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # Global test across comparisons
  kw <- kruskal.test(logFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    coord_cartesian(ylim = c(-2, 2)) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}
```

```{r FC_Plot_Function_sig_No5, include = FALSE}
plot_cluster_fc_sig_No5 <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day24","H_Day415","H_Day1530","C_Day02","C_Day24","C_Day415","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # Global test across comparisons
  kw <- kruskal.test(logFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$logFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = logFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    coord_cartesian(ylim = c(-2, 2)) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}
```

```{r AbsFC_Plot_Function_sig, include = FALSE}

plot_cluster_absfc_sig <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530","C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")

  # ✅ Skip if no data
  if (nrow(df) == 0) {
    message(cluster_name, ": no data — skipping")
    return(NULL)
  }

  # ✅ Skip if only one comparison present
  if (length(unique(df$Comparisons)) < 2) {
    message(cluster_name, ": only one comparison — skipping stats")
    return(NULL)
  }

  # Stats
  kw <- kruskal.test(logFC ~ Comparisons, data = df)

  pw_kw <- pairwise.wilcox.test(
    df$absfc,
    df$Comparisons,
    p.adjust.method = "BH"
  )

  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = absfc)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("logFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA FC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
    coord_cartesian(ylim = c(0, 2)) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)
}
```

```{r AbsFC_Plot_Function_sig_No4, include = FALSE}
plot_cluster_absfc_sig_No4 <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day25","H_Day515","H_Day1530","C_Day02","C_Day25","C_Day515","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")
  
  # Global test across comparisons
  kw <- kruskal.test(AbsFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$AbsFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("AbslogFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA AbsFC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
  coord_cartesian(ylim = c(0, 2)) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}
```

```{r AbsFC_Plot_Function_sig_No5, include = FALSE}
plot_cluster_absfc_sig_No5 <- function(gene_vector, cluster_name, top_table) {

  df <- top_table %>%
    dplyr::filter(Gene %in% gene_vector) %>%
    mutate(Comparisons = factor(Comparisons, levels = c(
      "H_Day02","H_Day24","H_Day415","H_Day1530","C_Day02","C_Day24","C_Day415","C_Day1530"
    )))

  cat(cluster_name, ":", nrow(df), "rows,",
      length(unique(df$Gene)), "unique genes\n")
  
  # Global test across comparisons
  kw <- kruskal.test(AbsFC ~ Comparisons, data = df)
  
  pw_kw <-pairwise.wilcox.test(
    df$AbsFC,
    df$Comparisons,
    p.adjust.method = "BH")
  
  print(pw_kw)

  p <- ggplot(df, aes(x = Comparisons, y = AbsFC)) +
    geom_boxplot(aes(fill = Comparisons)) +
    theme_bw() +
    xlab(" ") +
    ylab("AbslogFC") +
    ggtitle(
      paste0(
        cluster_name,
        " RNA AbsFC Comparisons\nKruskal–Wallis p = ",
        signif(kw$p.value, 3)
      )
    ) +
  coord_cartesian(ylim = c(0, 2)) +
    theme(
      plot.title = element_text(size = rel(1.3), hjust = 0.5),
      axis.title = element_text(size = 15),
      axis.text.x = element_text(size = 8, angle = 15)
    )

  return(p)


}
```

```{r get_directional_genes, include = FALSE}

get_fc_directions <- function(traj_label, coef_name, comparison_label,
                              top_table_all, fit_obj, p_cutoff = 0.05) {

  # ---------------------------
  # DE genes (interaction model)
  # ---------------------------
  tt <- topTable(fit_obj, coef = coef_name, number = Inf)

sig_tt <- tt %>%
  dplyr::filter(adj.P.Val < p_cutoff) %>%
  tibble::rownames_to_column("Gene") %>%
  dplyr::distinct(Gene, .keep_all = TRUE)

  # ---------------------------
  # trajectory FC data
  # ---------------------------
  df_fc <- top_table_all %>%
    dplyr::filter(
      Comparisons %in% c(
        paste0("H_", comparison_label),
        paste0("C_", comparison_label)
      )
    )

  df_dir <- df_fc %>%
    dplyr::mutate(Species = ifelse(grepl("^H_", Comparisons), "H", "C")) %>%
    dplyr::group_by(Gene, Species) %>%
    dplyr::summarise(logFC = mean(logFC, na.rm = TRUE), .groups = "drop") %>%
    tidyr::pivot_wider(names_from = Species, values_from = logFC) %>%
    dplyr::filter(!is.na(H), !is.na(C)) %>%
    dplyr::distinct(Gene, .keep_all = TRUE)

  # ---------------------------
  # HARD FILTER: keep only DE genes
  # ---------------------------
  df_combo <- df_dir %>%
  dplyr::inner_join(sig_tt, by = "Gene") %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      H > 0 & C < 0 ~ "H_pos_C_neg",
      H < 0 & C > 0 ~ "H_neg_C_pos",
      H > 0 & C > 0 ~ "Both_pos",
      H < 0 & C < 0 ~ "Both_neg",
      TRUE ~ "Other"
    ),
    direction_group = dplyr::case_when(
      H * C > 0 ~ "Same_direction",      # same sign
      H * C < 0 ~ "Opposite_direction",  # opposite sign
      TRUE ~ "Other"
    )
  )

  # ---------------------------
  # output
  # ---------------------------
list(
  all = df_combo,
  H_pos_C_neg = dplyr::filter(df_combo, direction == "H_pos_C_neg"),
  H_neg_C_pos = dplyr::filter(df_combo, direction == "H_neg_C_pos"),
  Both_pos = dplyr::filter(df_combo, direction == "Both_pos"),
  Both_neg = dplyr::filter(df_combo, direction == "Both_neg"),

  Same_direction = dplyr::filter(df_combo, direction_group == "Same_direction"),
  Opposite_direction = dplyr::filter(df_combo, direction_group == "Opposite_direction"),

  Other = dplyr::filter(df_combo, direction == "Other"),
  n_sig = nrow(sig_tt)
)
}
```

```{r get_directional_genes, include = FALSE}

get_fc_directions_HvC <- function(traj_label, coef_name, comparison_label,
                                 top_table_all, fit_obj, p_cutoff = 0.05) {

  # ---------------------------
  # DE genes
  # ---------------------------
  tt <- topTable(fit_obj, coef = coef_name, number = Inf)

  sig_tt <- tt %>%
    dplyr::filter(adj.P.Val < p_cutoff) %>%
    tibble::rownames_to_column("Gene") %>%
    dplyr::distinct(Gene, .keep_all = TRUE)

  # ---------------------------
  # HvC FC data
  # ---------------------------
  df_fc <- top_table_all %>%
    dplyr::filter(Comparisons == comparison_label) %>%
    dplyr::distinct(Gene, .keep_all = TRUE)

  # ---------------------------
  # classify direction
  # ---------------------------
  df_combo <- df_fc %>%
  dplyr::inner_join(sig_tt, by = "Gene") %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      logFC.x > 0 ~ "Human_higher",
      logFC.x < 0 ~ "Chimp_higher",
      TRUE ~ "No_difference"
    ),
    magnitude = abs(logFC.x)
  )

  # ---------------------------
  # output
  # ---------------------------
  list(
    all = df_combo,
    Human_higher = dplyr::filter(df_combo, direction == "Human_higher"),
    Chimp_higher = dplyr::filter(df_combo, direction == "Chimp_higher"),
    n_sig = nrow(sig_tt)
  )
}
```

```{r}
Enrich_Go_sets <- function(gene_sets, v) {

  library(clusterProfiler)
  library(org.Hs.eg.db)
  library(dplyr)

  # -----------------------------
  # Universe (FIXED)
  # -----------------------------
  background_genes <- rownames(v$E) %>%
    sub("\\..*", "", .)

  # -----------------------------
  # GO helper
  # -----------------------------
  run_go <- function(genes) {

    genes <- unique(sub("\\..*", "", genes))

    if (length(genes) < 10) return(NULL)

    ego <- enrichGO(
      gene          = genes,
      universe      = background_genes,
      OrgDb         = org.Hs.eg.db,
      keyType       = "ENSEMBL",
      ont           = "BP",
      readable      = TRUE
    )

    if (is.null(ego)) return(NULL)

    as.data.frame(ego)
  }

  # -----------------------------
  # Run for each gene set
  # -----------------------------
  results <- lapply(gene_sets, function(df) {
    if (is.null(df) || nrow(df) == 0) return(NULL)
    run_go(df$Gene)
  })

  return(results)
}
```

####Unfiltered

```{r RNASeq_DGE_Differential_Data}
RNA_Metadata_NoRep <- RNA_Metadata %>%
  filter(!grepl("R$",Individual))

RNA_fc_NoRep <- RNA_fc %>%
  dplyr::select(-(contains("R")))

RNA_Metadata_NoRep$dgelist <- c(rep(c("Human_Day0","Human_Day2","Human_Day4","Human_Day5","Human_Day15","Human_Day30","Chimp_Day0","Chimp_Day2","Chimp_Day4","Chimp_Day5","Chimp_Day15","Chimp_Day30"),7))

#create DGEList object
dge_RNA_fc_NoRep <- DGEList(counts = RNA_fc_NoRep)
dge_RNA_fc_NoRep$samples$group <- factor(RNA_Metadata_NoRep$dgelist)
dge_RNA_fc_NoRep <- calcNormFactors(dge_RNA_fc_NoRep, method = "TMM")
dge_RNA_fc_NoRep$samples

dim(dge_RNA_fc_NoRep)
# saveRDS(dge_RNA_fc_NoRep, "data/DGE/Species/concat/RowMeans_PerDay/ddge_RNA_fc_NoRep.RDS")
dge_RNA_fc_NoRep$samples

```

```{r RNASeq_DGE_Differential_Data_Model}
RNA_Metadata_NoRep$Species <- factor(
  RNA_Metadata_NoRep$Species,
  levels = c("C", "H")   # Chimp baseline
)

RNA_Metadata_NoRep$Timepoint <- factor(
  RNA_Metadata_NoRep$Timepoint,
  levels = c("Day0","Day2","Day4","Day5","Day15","Day30")
)

design_int_RNA_fc_NoRep <- model.matrix(~ Species * Timepoint,
                           data = RNA_Metadata_NoRep)

colnames(design_int_RNA_fc_NoRep)
colnames(design_int_RNA_fc_NoRep) <- make.names(colnames(design_int_RNA_fc_NoRep))

# saveRDS(design_int_RMG0_All, "data/DGE/Species/concat/RowMeans_PerDay/design_int_RMG0_All.RDS")
```



```{r RNASeq_DGE_Differential_Data_Model, fig.height=6,fig.width=6}
dge <- dge_RNA_fc_NoRep
design_int <- design_int_RNA_fc_NoRep

# Step 1: voom first
v1 <- voom(dge, design_int, plot = TRUE)

# saveRDS(v1,"data/DGE/Species/concat/RowMeans_PerDay/v1_RMG0_PerDay_All.RDS")

# Step 2: estimate duplicate correlation on voom-transformed data
corfit <- duplicateCorrelation(v1, design_int, block = RNA_Metadata_NoRep$Individual)
corfit.correlation <- corfit$consensus.correlation

# Step 3: voom again including correlation
v2 <- voom(dge, design_int, plot = TRUE,
           block = RNA_Metadata_NoRep$Individual,
           correlation = corfit.correlation)

# Step 4: fit linear model
fit <- lmFit(v2, design_int, block = RNA_Metadata_NoRep$Individual, correlation = corfit.correlation)
fit <- eBayes(fit)

pal <- rainbow(length(unique(RNA_Metadata_NoRep$Timepoint)))
day <- RNA_Metadata_NoRep$Timepoint
plotDensities(v2, col = pal[as.numeric(day)], legend = FALSE)

human_idx <- RNA_Metadata_NoRep$Species == "H"
chimp_idx <- RNA_Metadata_NoRep$Species == "C"

pal <- rainbow(length(unique(RNA_Metadata_NoRep$Timepoint)))

# Human
plotDensities(
  v2[, human_idx],
  col = pal[as.numeric(as.factor(RNA_Metadata_NoRep$Timepoint[human_idx]))],
  main = "",
  legend = FALSE,
  axes = FALSE
)

axis(1)
axis(2)
mtext("log2 CPM", side = 1, line = 2)

title("Human")
  legend(
      "right",
      legend = RNA_Metadata_NoRep$Individual[human_idx],  # or Timepoint, etc.
      col = rainbow(sum(human_idx)),
      lty = 1,
     cex = 0.7
    )

# Chimp
plotDensities(
  v2[, chimp_idx],
  col = pal[as.numeric(as.factor(RNA_Metadata_NoRep$Timepoint[human_idx]))],
  main = "",
  legend = FALSE,
  axes = FALSE
)

axis(1)
axis(2)
mtext("log2 CPM", side = 1, line = 2)

title("Chimp")
  legend(
      "right",
      legend = RNA_Metadata_NoRep$Individual[chimp_idx],  # or Timepoint, etc.
      col = rainbow(sum(chimp_idx)),
      lty = 1,
     cex = 0.7
    )

species_levels <- unique(RNA_Metadata_NoRep$Species)
day_levels <- unique(RNA_Metadata_NoRep$Timepoint)

for (sp in species_levels) {
  for (day in day_levels) {

    idx <- RNA_Metadata_NoRep$Species == sp &
           RNA_Metadata_NoRep$Timepoint == day

    if (sum(idx) > 0) {

      cols <- rainbow(sum(idx))

      plotDensities(
        v2[, idx],
        col = cols,
        main = paste(sp, day),
        legend = FALSE,
        axes = FALSE
      )

      axis(1)
      axis(2)
      mtext("log2 CPM", side = 1, line = 2)

      legend(
        "right",
        legend = RNA_Metadata_NoRep$Individual[idx],
        col = cols,
        lty = 1,
        cex = 0.7
      )
    }
  }
}



# saveRDS(fit, "data/DGE/Species/concat/RowMeans_PerDay/fit_RMG0_PerDay_All.RDS")
```



####RLCPM_G1_4SpTp

```{r RNASeq_DGE_Differential_Data}
counts <- Filt_logcpm_G1_SpTp_RNA_fc
metadata <- RNA_Metadata_NoRep

counts_norep <- counts %>%
  dplyr::select(-(contains("R")))

#create DGEList object
dge <- DGEList(counts = counts_norep)
dge$samples$group <- factor(metadata$dgelist)
dge <- calcNormFactors(dge, method = "TMM")
dge$samples

dim(dge_RMGO_PerDay_All)
dge_RMGO_All$samples

metadata$Species <- factor(
  metadata$Species,
  levels = c("C", "H")   # Chimp baseline
)

 metadata$Timepoint <- factor(
   metadata$Timepoint,
  levels = c("Day0","Day2","Day4","Day5","Day15","Day30")
)

design_int <- model.matrix(~ Species * Timepoint,
                           data =  metadata)

colnames(design_int)
colnames(design_int) <- make.names(colnames(design_int))

# Step 1: voom first
v1 <- voom(dge, design_int, plot = TRUE)

# Step 2: estimate duplicate correlation on voom-transformed data
corfit <- duplicateCorrelation(v1, design_int, block = metadata$Individual)
corfit.correlation <- corfit$consensus.correlation

# Step 3: voom again including correlation
v2 <- voom(dge, design_int, plot = TRUE,
           block = metadata$Individual,
           correlation = corfit.correlation)

# Step 4: fit linear model
fit <- lmFit(v2, design_int, block = metadata$Individual, correlation = corfit.correlation)
fit <- eBayes(fit)

pal <- rainbow(length(unique(metadata$Timepoint)))
day <- metadata$Timepoint
plotDensities(v2, col = pal[as.numeric(day)], legend = FALSE)

human_idx <- metadata$Species == "H"
chimp_idx <- metadata$Species == "C"

pal <- rainbow(length(unique(metadata$Timepoint)))

# Human
plotDensities(
  v2[, human_idx],
  col = pal[as.numeric(as.factor(metadata$Timepoint[human_idx]))],
  main = "",
  legend = FALSE,
  axes = FALSE
)

axis(1)
axis(2)
mtext("log2 CPM", side = 1, line = 2)

title("Human")
  legend(
      "right",
      legend = metadata$Individual[human_idx],  # or Timepoint, etc.
      col = rainbow(sum(human_idx)),
      lty = 1,
     cex = 0.7
    )

# Chimp
plotDensities(
  v2[, chimp_idx],
  col = pal[as.numeric(as.factor(metadata$Timepoint[human_idx]))],
  main = "",
  legend = FALSE,
  axes = FALSE
)

axis(1)
axis(2)
mtext("log2 CPM", side = 1, line = 2)

title("Chimp")
  legend(
      "right",
      legend = metadata$Individual[chimp_idx],  # or Timepoint, etc.
      col = rainbow(sum(chimp_idx)),
      lty = 1,
     cex = 0.7
    )

species_levels <- unique(metadata$Species)
day_levels <- unique(metadata$Timepoint)

for (sp in species_levels) {
  for (day in day_levels) {

    idx <- metadata$Species == sp &
           metadata$Timepoint == day

    if (sum(idx) > 0) {

      cols <- rainbow(sum(idx))

      plotDensities(
        v2[, idx],
        col = cols,
        main = paste(sp, day),
        legend = FALSE,
        axes = FALSE
      )

      axis(1)
      axis(2)
      mtext("log2 CPM", side = 1, line = 2)

      legend(
        "right",
        legend = metadata$Individual[idx],
        col = cols,
        lty = 1,
        cex = 0.7
      )
    }
  }
}


# saveRDS(dge, "data/DGE/Species/concat/RowMeans_PerDay/dge_lcpm1_4SpTp.RDS")
# saveRDS(design_int, "data/DGE/Species/concat/RowMeans_PerDay/design_lcpm1_4SpTp.RDS")
# saveRDS(v1,"data/DGE/Species/concat/RowMeans_PerDay/v1_lcpm1_4SpTp.RDS")
# saveRDS(fit, "data/DGE/Species/concat/RowMeans_PerDay/fit_lcpm1_4SpTp.RDS")
```

```{r RNASeq_DGE_Differential_Data_Model}
fit <- fit_lcpm1_4SpTp
design_int <- design_lcpm1_4SpTp

contrast_matrix <- makeContrasts(

  # Species differences
  HvC_Day0  = SpeciesH,
  HvC_Day2  = SpeciesH + SpeciesH.TimepointDay2,
  HvC_Day4  = SpeciesH + SpeciesH.TimepointDay4,
  HvC_Day5  = SpeciesH + SpeciesH.TimepointDay5,
  HvC_Day15 = SpeciesH + SpeciesH.TimepointDay15,
  HvC_Day30 = SpeciesH + SpeciesH.TimepointDay30,
  
  #Trajectory differences
  H_Day02 = TimepointDay2 + SpeciesH.TimepointDay2,
  H_Day24 = TimepointDay4 + SpeciesH.TimepointDay4 - TimepointDay2 - SpeciesH.TimepointDay2,
  H_Day45 = TimepointDay5 + SpeciesH.TimepointDay5 - TimepointDay4 - SpeciesH.TimepointDay4,
  H_Day515 = TimepointDay15 + SpeciesH.TimepointDay15 - TimepointDay5 - SpeciesH.TimepointDay5,
  H_Day1530 = TimepointDay30 + SpeciesH.TimepointDay30 - TimepointDay15 - SpeciesH.TimepointDay15,
  C_Day02 = TimepointDay2,
  C_Day24 = TimepointDay4 - TimepointDay2,
  C_Day45 = TimepointDay5 - TimepointDay4,
  C_Day515 = TimepointDay15 - TimepointDay5,
  C_Day1530 = TimepointDay30 - TimepointDay15,
  
  # True interaction tests trajectory
  Sig_Sp_inter_Traj02 = SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj24 = SpeciesH.TimepointDay4 - SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj45 = SpeciesH.TimepointDay5 - SpeciesH.TimepointDay4,
  Sig_Sp_inter_Traj515 = SpeciesH.TimepointDay15 - SpeciesH.TimepointDay5,
  Sig_Sp_inter_Traj1530 = SpeciesH.TimepointDay30 - SpeciesH.TimepointDay15,
  
  levels = design_int
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

plotSA(fit2, main = "RNA Model")

results_summary <- decideTests(fit2,
                               adjust.method = "BH",
                               p.value = 0.05)
summary(results_summary)

# saveRDS(fit2, "data/DGE/Species/concat/RowMeans_PerDay/fit2_lcpm1_4SpTp.RDS")
```

```{r RNASeq_DGE_Differential_TopTable}
fit2 <- fit2_lcpm1_4SpTp

#Create Human TopTable. using listapply, then you can pull specific comp using the $
TopTables_RNA_names <- colnames(fit2$coefficients) 

TopTable_RNA_All <- do.call(
  rbind,
  lapply(TopTables_RNA_names,function(ct) {
    
    tt <- topTable(
      fit2,
      coef = ct,
      number = Inf,
      sort.by = "p"
    )
    
    #add identifiers
    tt$Gene <- rownames(tt)
    tt$Comparisons <- ct
    
    tt
  })
)

Comparison_names <- unique(TopTable_RNA_All$Comparisons)

# saveRDS(TopTable_RNA_All, "data/DGE/Species/concat/RowMeans/All/TopTable_lcpm1_4SpTp.RDS")
# saveRDS(Comparison_names, "data/DGE/Species/concat/RowMeans/All/Comparison_names_lcpm1_4SpTp.RDS")

head(TopTable_RNA_All)
```

```{r RNASeq_DGE_Differential_TopTable_VolcancoPlots}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp

# Calculate global axis limits
x_limits <- range(TopTable_RNA_All$logFC, na.rm = TRUE)
y_limits <- range(-log10(TopTable_RNA_All$P.Value), na.rm = TRUE)

plot <- list()

for (n in Comparison_names) {
  data_n <- TopTable_RNA_All %>% 
    dplyr::filter(Comparisons == n)
  
  plot[[n]] <- generate_volcano_plot(data_n, n) +
    ggplot2::xlim(x_limits) +
    ggplot2::ylim(y_limits)
}

# Print plots
for (n in Comparison_names) {
  print(plot[[n]])
}
```

```{r RNASeq_DGE_Differential_TopTable_Subsetting0.05}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp

RNA_sets <- map(
  Comparison_names,
  ~ {
    df <- TopTable_RNA_All %>%
      filter(Comparisons == paste0(.x))

    list(
      DEGs = df %>% filter(adj.P.Val < 0.05),
      NonDEGs = df %>% filter(adj.P.Val >= 0.05)
    )
  }
)


names(RNA_sets) <- paste0(Comparison_names)

# saveRDS(RNA_sets, "data/DGE/Species/concat/RowMeans_PerDay/RNA_sets_lcpm1_4SpTp.RDS")
```

#####Species

```{r RNASeq_DGE_Trajectory_FC, fig.height=6, fig.width=10}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Species <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "HvC_Day0","HvC_Day2","HvC_Day4","HvC_Day5","HvC_Day15",
    "HvC_Day30"
  ))

SpeciesD0_genes <- unique(c(RNA_sets$HvC_Day0$DEGs$Gene))
SpeciesD2_genes <- unique(c(RNA_sets$HvC_Day2$DEGs$Gene))
SpeciesD4_genes <- unique(c(RNA_sets$HvC_Day4$DEGs$Gene))
SpeciesD5_genes <- unique(c(RNA_sets$HvC_Day5$DEGs$Gene))
SpeciesD15_genes <- unique(c(RNA_sets$HvC_Day15$DEGs$Gene))
SpeciesD30_genes <- unique(c(RNA_sets$HvC_Day30$DEGs$Gene))

cluster_lists <- list(
 HvC_Day0  = SpeciesD0_genes,
  HvC_Day2  = SpeciesD2_genes,
  HvC_Day4  = SpeciesD4_genes,
  HvC_Day5  = SpeciesD5_genes,
  HvC_Day15  = SpeciesD15_genes,
 HvC_Day30  = SpeciesD30_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Species)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)

```

```{r RNASeq_DGE_Trajectory_FC}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "HvC_Day0","HvC_Day2","HvC_Day4","HvC_Day5","HvC_Day15",
    "HvC_Day30"
  ))

SpeciesD0_genes <- unique(c(RNA_sets$HvC_Day0$DEGs$Gene))
SpeciesD2_genes <- unique(c(RNA_sets$HvC_Day2$DEGs$Gene))
SpeciesD4_genes <- unique(c(RNA_sets$HvC_Day4$DEGs$Gene))
SpeciesD5_genes <- unique(c(RNA_sets$HvC_Day5$DEGs$Gene))
SpeciesD15_genes <- unique(c(RNA_sets$HvC_Day15$DEGs$Gene))
SpeciesD30_genes <- unique(c(RNA_sets$HvC_Day30$DEGs$Gene))

cluster_lists <- list(
 HvC_Day0  = SpeciesD0_genes,
  HvC_Day2  = SpeciesD2_genes,
  HvC_Day4  = SpeciesD4_genes,
  HvC_Day5  = SpeciesD5_genes,
  HvC_Day15  = SpeciesD15_genes,
 HvC_Day30  = SpeciesD30_genes
)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


# saveRDS(TopTable_RNA_Traj, "data/DGE/Species/concat/RowMeans_PerDay/TopTable_RNA_Traj_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Trajectory_Directionality}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
fit2 <- fit2_lcpm1_4SpTp

traj_info <- list(
  HvC_Day0 = list(coef = "HvC_Day0", comp = "HvC_Day0"),
  HvC_Day2 = list(coef = "HvC_Day2", comp = "HvC_Day2"),
  HvC_Day4 = list(coef = "HvC_Day4", comp = "HvC_Day4"),
  HvC_Day5 = list(coef ="HvC_Day5", comp = "HvC_Day5"),
 HvC_Day15 = list(coef = "HvC_Day15", comp = "HvC_Day15"),
 HvC_Day30 = list(coef = "HvC_Day30", comp = "HvC_Day30")
)

direction_results <- setNames(
  lapply(names(traj_info), function(name) {

    info <- traj_info[[name]]

    get_fc_directions_HvC(
      traj_label = name,
      coef_name = info$coef,
      comparison_label = info$comp,
      top_table_all = TopTable_RNA_All,
      fit_obj = fit2
    )

  }),
  names(traj_info)
)

# saveRDS(direction_results, "data/DGE/Species/concat/RowMeans_PerDay/Species_Directions_lcpm1_4SpTp.RDS")
```

```{r RNASeq_DGE_Trajectory_Directionality_FC}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- Species_Directions_lcpm1_4SpTp

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "HvC_Day0","HvC_Day2","HvC_Day4","HvC_Day5","HvC_Day15",
    "HvC_Day30"
  ))

aa <- unique(RNA_sets$HvC_Day0$all$Gene)
ab <- unique(RNA_sets$HvC_Day0$Human_higher$Gene)
ac <- unique(RNA_sets$HvC_Day0$Chimp_higher$Gene)

ba <- unique(RNA_sets$HvC_Day2$all$Gene)
bb <- unique(RNA_sets$HvC_Day2$Human_higher$Gene)
bc <- unique(RNA_sets$HvC_Day2$Chimp_higher$Gene)

ca <- unique(RNA_sets$HvC_Day4$all$Gene)
cb <- unique(RNA_sets$HvC_Day4$Human_higher$Gene)
cc <- unique(RNA_sets$HvC_Day4$Chimp_higher$Gene)

da <- unique(RNA_sets$HvC_Day5$all$Gene)
db <- unique(RNA_sets$HvC_Day5$Human_higher$Gene)
dc <- unique(RNA_sets$HvC_Day5$Chimp_higher$Gene)

ea <- unique(RNA_sets$HvC_Day15$all$Gene)
eb <- unique(RNA_sets$HvC_Day15$Human_higher$Gene)
ec <- unique(RNA_sets$HvC_Day15$Chimp_higher$Gene)

fa <- unique(RNA_sets$HvC_Day30$all$Gene)
fb <- unique(RNA_sets$HvC_Day30$Human_higher$Gene)
fc <- unique(RNA_sets$HvC_Day30$Chimp_higher$Gene)


cluster_lists <- list(
  HvC_Day0_all = aa,
  HvC_Day0_HumanHigher = ab,
  HvC_Day0_ChimpHigher = ac,
  
  HvC_Day2_all = ba,
  HvC_Day2_HumanHigher = bb,
  HvC_Day2_ChimpHigher = bc,
  
  HvC_Day4_all = ca,
  HvC_Day4_HumanHigher = cb,
  HvC_Day4_ChimpHigher = cc,
  
  HvC_Day5_all = da,
  HvC_Day5_HumanHigher = db,
  HvC_Day5_ChimpHigher = dc,
  
  HvC_Day15_all = ea,
  HvC_Day15_HumanHigher = eb,
  HvC_Day15_ChimpHigher = ec,
  
  HvC_Day30_all = fa,
  HvC_Day30_HumanHigher = fb,
  HvC_Day30_ChimpHigher = fc
)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


```

```{r RNASeq_DGE_Trajectory_EnrichGo}
fit2 <- fit2_lcpm1_4SpTp
v <- v1_lcpm1_4SpTp

all_go_results <- lapply(names(direction_results), function(traj) {

  res <- direction_results[[traj]]

  gene_sets <- list(
    All = res$all,
    Human_higher = res$Human_higher,
    Chimp_higher    = res$Chimp_higher
  )

  go <- Enrich_Go_sets(gene_sets, v)

  return(go)
})

names(all_go_results) <- names(direction_results)


# saveRDS(all_go_results, "data/DGE/Species/concat/RowMeans_PerDay/Species_go_results_lcpm1_4SpTp.RDS")

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day02"
C_comp <- "C_Day02"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day02$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day02$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_4_2}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day24"
C_comp <- "C_Day24"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day24$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day24$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_5_4}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day45"
C_comp <- "C_Day45"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day45$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day45$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_15_5}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day515"
C_comp <- "C_Day515"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day515$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day515$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_30_15}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day1530"
C_comp <- "C_Day1530"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day1530$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day1530$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

#####Trajectory

```{r RNASeq_DGE_Trajectory_FC, fig.height=6, fig.width=10}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Traj02_genes <- unique(c(RNA_sets$H_Day02$DEGs$Gene,RNA_sets$C_Day02$DEGs$Gene))
Traj24_genes <- unique(c(RNA_sets$H_Day24$DEGs$Gene,RNA_sets$C_Day24$DEGs$Gene))
Traj45_genes <- unique(c(RNA_sets$H_Day45$DEGs$Gene,RNA_sets$C_Day45$DEGs$Gene))
Traj515_genes <- unique(c(RNA_sets$H_Day515$DEGs$Gene,RNA_sets$C_Day515$DEGs$Gene))
Traj1530_genes <- unique(c(RNA_sets$H_Day1530$DEGs$Gene,RNA_sets$C_Day1530$DEGs$Gene))

cluster_lists <- list(
 Traj02_genes  = Traj02_genes,
  Traj24_genes  = Traj24_genes,
  Traj45_genes  = Traj45_genes,
  Traj515_genes  = Traj515_genes,
  Traj1530_genes  = Traj1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)

```

```{r RNASeq_DGE_Trajectory_FC}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Traj02_genes <- unique(c(RNA_sets$H_Day02$DEGs$Gene,RNA_sets$C_Day02$DEGs$Gene))
Traj24_genes <- unique(c(RNA_sets$H_Day24$DEGs$Gene,RNA_sets$C_Day24$DEGs$Gene))
Traj45_genes <- unique(c(RNA_sets$H_Day45$DEGs$Gene,RNA_sets$C_Day45$DEGs$Gene))
Traj515_genes <- unique(c(RNA_sets$H_Day515$DEGs$Gene,RNA_sets$C_Day515$DEGs$Gene))
Traj1530_genes <- unique(c(RNA_sets$H_Day1530$DEGs$Gene,RNA_sets$C_Day1530$DEGs$Gene))

cluster_lists <- list(
 Traj02_genes  = Traj02_genes,
  Traj24_genes  = Traj24_genes,
  Traj45_genes  = Traj45_genes,
  Traj515_genes  = Traj515_genes,
  Traj1530_genes  = Traj1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)

```

```{r RNASeq_DGE_Trajectory_Directionality}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
fit2 <- fit2_lcpm1_4SpTp

traj_info <- list(
  Traj02_genes = list(coef = "H_Day02", comp = "Day02"),
  Traj24_genes = list(coef = "H_Day24", comp = "Day24"),
  Traj45_genes = list(coef = "H_Day45", comp = "Day45"),
  Traj515_genes = list(coef ="H_Day515", comp = "Day515"),
 Traj1530_genes = list(coef = "H_Day1530", comp = "Day1530")
)

direction_results <- setNames(
  lapply(names(traj_info), function(name) {

    info <- traj_info[[name]]

    get_fc_directions(
      traj_label = name,
      coef_name = info$coef,
      comparison_label = info$comp,
      top_table_all = TopTable_RNA_All,
      fit_obj = fit2
    )

  }),
  names(traj_info)
)

# saveRDS(direction_results, "data/DGE/Species/concat/RowMeans_PerDay/Trajectory_Directions_lcpm1_4SpTp.RDS")
```

```{r RNASeq_DGE_Trajectory_Directionality_FC}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- Trajectory_Directions_lcpm1_4SpTp

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

aa <- unique(RNA_sets$Traj02_genes$all$Gene)
ab <- unique(RNA_sets$Traj02_genes$H_pos_C_neg$Gene)
ac <- unique(RNA_sets$Traj02_genes$H_neg_C_pos$Gene)
ad <- unique(RNA_sets$Traj02_genes$Both_pos$Gene)
ae <- unique(RNA_sets$Traj02_genes$Both_neg$Gene)
af <- unique(RNA_sets$Traj02_genes$Same_direction$Gene)
ag <- unique(RNA_sets$Traj02_genes$Opposite_direction$Gene)

ba <- unique(RNA_sets$Traj24_genes$all$Gene)
bb <- unique(RNA_sets$Traj24_genes$H_pos_C_neg$Gene)
bc <- unique(RNA_sets$Traj24_genes$H_neg_C_pos$Gene)
bd <- unique(RNA_sets$Traj24_genes$Both_pos$Gene)
be <- unique(RNA_sets$Traj24_genes$Both_neg$Gene)
bf <- unique(RNA_sets$Traj24_genes$Same_direction$Gene)
bg <- unique(RNA_sets$Traj24_genes$Opposite_direction$Gene)


ca <- unique(RNA_sets$Traj45_genes$all$Gene)
cb <- unique(RNA_sets$Traj45_genes$H_pos_C_neg$Gene)
cc <- unique(RNA_sets$Traj45_genes$H_neg_C_pos$Gene)
cd <- unique(RNA_sets$Traj45_genes$Both_pos$Gene)
ce <- unique(RNA_sets$Traj45_genes$Both_neg$Gene)
cf <- unique(RNA_sets$Traj45_genes$Same_direction$Gene)
cg <- unique(RNA_sets$Traj45_genes$Opposite_direction$Gene)

da <- unique(RNA_sets$Traj515_genes$all$Gene)
db <- unique(RNA_sets$Traj515_genes$H_pos_C_neg$Gene)
dc <- unique(RNA_sets$Traj515_genes$H_neg_C_pos$Gene)
dd <- unique(RNA_sets$Traj515_genes$Both_pos$Gene)
de <- unique(RNA_sets$Traj515_genes$Both_neg$Gene)
df <- unique(RNA_sets$Traj515_genes$Both_pos$Gene)
dg <- unique(RNA_sets$Traj515_genes$Both_neg$Gene)

ea <- unique(RNA_sets$Traj1530_genes$all$Gene)
eb <- unique(RNA_sets$Traj1530_genes$H_pos_C_neg$Gene)
ec <- unique(RNA_sets$Traj1530_genes$H_neg_C_pos$Gene)
ed <- unique(RNA_sets$Traj1530_genes$Both_pos$Gene)
ee <- unique(RNA_sets$Traj1530_genes$Both_neg$Gene)
ef <- unique(RNA_sets$Traj1530_genes$Same_direction$Gene)
eg <- unique(RNA_sets$Traj1530_genes$Opposite_direction$Gene)

cluster_lists <- list(
  Traj02_All = aa,
  Traj02_HumanPos = ab,
  Traj02_ChimpPos = ac,
  Traj02_Both_pos = ad,
  Traj02_Both_neg = ae,
  Traj02_Same_direction = af,
  Traj02_Opposite_direction = ag,
  
  Traj24_All = ba,
  Traj24_HumanPos = bb,
  Traj24_ChimpPos = bc,
  Traj24_Both_pos = bd,
  Traj24_Both_neg = be,
  Traj24_Same_direction = bf,
  Traj24_Opposite_direction = bg,
 
  Traj45_All = ca,
  Traj45_HumanPos = cb,
  Traj45_ChimpPos = cc,
  Traj45_Both_pos = cd,
  Traj45_Both_neg = ce,
  Traj45_Same_direction = cf,
  Traj45_Opposite_direction = cg,
 
  Traj515_All = da,
  Traj515_HumanPos = db,
  Traj515_ChimpPos = dc,
  Traj515_Both_pos = dd,
  Traj515_Both_neg = de,
  Traj515_Same_direction = df,
  Traj515_Opposite_direction = dg,
 
  Traj1530_All = ea,
  Traj1530_HumanPos = eb,
  Traj1530_ChimpPos = ec,
  Traj1530_Both_pos = ed,
  Traj1530_Both_neg = ee,
  Traj1530_Same_direction = ef,
  Traj1530_Opposite_direction = eg
)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


```

```{r RNASeq_DGE_Trajectory_EnrichGo}
fit2 <- fit2_lcpm1_4SpTp
v <- v1_lcpm1_4SpTp

all_go_results <- lapply(names(direction_results), function(traj) {

  res <- direction_results[[traj]]

  gene_sets <- list(
    H_pos_C_neg = res$H_pos_C_neg,
    H_neg_C_pos = res$H_neg_C_pos,
    Both_pos    = res$Both_pos,
    Both_neg    = res$Both_neg,
    Same_Direction = res$Same_direction,
    Opposite_Direction = res$Opposite_direction,
    All = res$all
  )

  go <- Enrich_Go_sets(gene_sets, v)

  return(go)
})

names(all_go_results) <- names(direction_results)


# saveRDS(all_go_results, "data/DGE/Species/concat/RowMeans_PerDay/Trajectory_go_results_lcpm1_4SpTp.RDS")

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day02"
C_comp <- "C_Day02"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day02$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day02$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_4_2}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day24"
C_comp <- "C_Day24"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day24$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day24$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_5_4}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day45"
C_comp <- "C_Day45"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day45$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day45$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_15_5}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day515"
C_comp <- "C_Day515"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day515$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day515$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_30_15}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp


H_comp <- "H_Day1530"
C_comp <- "C_Day1530"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest_human <- unique(RNA_sets$H_Day1530$DEGs$Gene)
genes_of_interest_chimp <- unique(RNA_sets$C_Day1530$DEGs$Gene)

df_wide$highlight <- dplyr::case_when(
  df_wide$Gene %in% genes_of_interest_human &
  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Both",

  df_wide$Gene %in% genes_of_interest_human ~ "T-DEG Human Only",

  df_wide$Gene %in% genes_of_interest_chimp ~ "T-DEG Chimp Only",

  TRUE ~ "Other"
)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("T-DEG Human Only" = "red", "T-DEG Chimp Only" = "blue", "T-DEG Both" = "purple", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

#####Interactions

```{r RNASeq_DGE_Interaction_FC}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Inter_02_genes <- unique(RNA_sets$Sig_Sp_inter_Traj02$DEGs$Gene)
Inter_24_genes <- unique(RNA_sets$Sig_Sp_inter_Traj24$DEGs$Gene)
Inter_45_genes <- unique(RNA_sets$Sig_Sp_inter_Traj45$DEGs$Gene)
Inter_515_genes <- unique(RNA_sets$Sig_Sp_inter_Traj515$DEGs$Gene)
Inter_1530_genes <- unique(RNA_sets$Sig_Sp_inter_Traj1530$DEGs$Gene)

cluster_lists <- list(
  Inter_02_genes  = Inter_02_genes,
  Inter_24_genes  = Inter_24_genes,
  Inter_45_genes  = Inter_45_genes,
  Inter_515_genes  = Inter_515_genes,
  Inter_1530_genes  = Inter_1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


saveRDS(TopTable_RNA_Traj, "data/DGE/Species/concat/RowMeans_PerDay/TopTable_RNA_lcpm1_4SpTp.RDS")
```

```{r RNASeq_DGE_Interaction_Directionality}
TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- RNA_sets_lcpm1_4SpTp
fit2 <- fit2_lcpm1_4SpTp

traj_info <- list(
  InterTraj02 = list(coef = "Sig_Sp_inter_Traj02", comp = "Day02"),
  InterTraj24 = list(coef = "Sig_Sp_inter_Traj24", comp = "Day24"),
  InterTraj45 = list(coef = "Sig_Sp_inter_Traj45", comp = "Day45"),
  InterTraj515 = list(coef = "Sig_Sp_inter_Traj515", comp = "Day515"),
  InterTraj1530 = list(coef = "Sig_Sp_inter_Traj1530", comp = "Day1530")
)

direction_results <- setNames(
  lapply(names(traj_info), function(name) {

    info <- traj_info[[name]]

    get_fc_directions(
      traj_label = name,
      coef_name = info$coef,
      comparison_label = info$comp,
      top_table_all = TopTable_RNA_All,
      fit_obj = fit2
    )

  }),
  names(traj_info)
)

# saveRDS(direction_results, "data/DGE/Species/concat/RowMeans_PerDay/Interaction_Directions_lcpm1_4SpTp.RDS")
```

```{r RNASeq_DGE_Interaction_Directionality_FC}

TopTable_RNA_All <- TopTable_lcpm1_4SpTp
Comparison_names <- Comparison_names_lcpm1_4SpTp
RNA_sets <- Interaction_Directions_lcpm1_4SpTp

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

aa <- unique(RNA_sets$InterTraj02$all$Gene)
ab <- unique(RNA_sets$InterTraj02$H_pos_C_neg$Gene)
ac <- unique(RNA_sets$InterTraj02$H_neg_C_pos$Gene)
ad <- unique(RNA_sets$InterTraj02$Both_pos$Gene)
ae <- unique(RNA_sets$InterTraj02$Both_neg$Gene)
af <- unique(RNA_sets$InterTraj02$Same_direction$Gene)
ag <- unique(RNA_sets$InterTraj02$Opposite_direction$Gene)

ba <- unique(RNA_sets$InterTraj24$all$Gene)
bb <- unique(RNA_sets$InterTraj24$H_pos_C_neg$Gene)
bc <- unique(RNA_sets$InterTraj24$H_neg_C_pos$Gene)
bd <- unique(RNA_sets$InterTraj24$Both_pos$Gene)
be <- unique(RNA_sets$InterTraj24$Both_neg$Gene)
bf <- unique(RNA_sets$InterTraj24$Same_direction$Gene)
bg <- unique(RNA_sets$InterTraj24$Opposite_direction$Gene)

ca <- unique(RNA_sets$InterTraj45$all$Gene)
cb <- unique(RNA_sets$InterTraj45$H_pos_C_neg$Gene)
cc <- unique(RNA_sets$InterTraj45$H_neg_C_pos$Gene)
cd <- unique(RNA_sets$InterTraj45$Both_pos$Gene)
ce <- unique(RNA_sets$InterTraj45$Both_neg$Gene)
cf <- unique(RNA_sets$InterTraj45$Same_direction$Gene)
cg <- unique(RNA_sets$InterTraj45$Opposite_direction$Gene)

da <- unique(RNA_sets$InterTraj515$all$Gene)
db <- unique(RNA_sets$InterTraj515$H_pos_C_neg$Gene)
dc <- unique(RNA_sets$InterTraj515$H_neg_C_pos$Gene)
dd <- unique(RNA_sets$InterTraj515$Both_pos$Gene)
de <- unique(RNA_sets$InterTraj515$Both_neg$Gene)
df <- unique(RNA_sets$InterTraj515$Same_direction$Gene)
dg <- unique(RNA_sets$InterTraj515$Opposite_direction$Gene)

ea <- unique(RNA_sets$InterTraj1530$all$Gene)
eb <- unique(RNA_sets$InterTraj1530$H_pos_C_neg$Gene)
ec <- unique(RNA_sets$InterTraj1530$H_neg_C_pos$Gene)
ed <- unique(RNA_sets$InterTraj1530$Both_pos$Gene)
ee <- unique(RNA_sets$InterTraj1530$Both_neg$Gene)
ef <- unique(RNA_sets$InterTraj1530$Same_direction$Gene)
eg <- unique(RNA_sets$InterTraj1530$Opposite_direction$Gene)

cluster_lists <- list(
  Inter02_All = aa,
  Inter02_HumanPos = ab,
  Inter02_ChimpPos = ac,
  Inter02_Both_pos = ad,
  Inter02_Both_neg = ae,
  Inter02_Same_direction = af,
  Inter02_Opposite_direction = ag,
  
  Inter24_All = ba,
  Inter24_HumanPos = bb,
  Inter24_ChimpPos = bc,
  Inter24_Both_pos = bd,
  Inter24_Both_neg = be,
  Inter24_Same_direction = bf,
  Inter24_Opposite_direction = bg,
  
  Inter45_All = ca,
  Inter45_HumanPos = cb,
  Inter45_ChimpPos = cc,
  Inter45_Both_pos = cd,
  Inter45_Both_neg = ce,
  Inter45_Same_direction = cf,
  Inter45_Opposite_direction = cg,
  
  Inter515_All = da,
  Inter515_HumanPos = db,
  Inter515_ChimpPos = dc,
  Inter515_Both_pos = dd,
  Inter515_Both_neg = de,
  Inter515_Same_direction = df,
  Inter515_Opposite_direction = dg,
  
  
  Inter1530_All = ea,
  Inter1530_HumanPos = eb,
  Inter1530_ChimpPos = ec,
  Inter1530_Both_pos = ed,
  Inter1530_Both_neg = ee,
  Inter1530_Same_direction = ef,
  Inter1530_Opposite_direction = eg
  
)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


```

```{r RNASeq_DGE_Interaction_EnrichGo}
fit2 <- fit2_lcpm1_4SpTp
v <- v1_lcpm1_4SpTp

all_go_results <- lapply(names(direction_results), function(traj) {

  res <- direction_results[[traj]]

  gene_sets <- list(
    H_pos_C_neg = res$H_pos_C_neg,
    H_neg_C_pos = res$H_neg_C_pos,
    Both_pos    = res$Both_pos,
    Both_neg    = res$Both_neg,
    Same_direction = res$Same_direction,
    Opposite_direction = res$Opposite_direction,
    All = res$all
  )

  go <- Enrich_Go_sets(gene_sets, v)

  return(go)
})

names(all_go_results) <- names(direction_results)


# saveRDS(all_go_results, "data/DGE/Species/concat/RowMeans_PerDay/Interaction_go_results_lcpm1_4SpTp.RDS")

```


####RMGO_PerDay_All

```{r RNASeq_DGE_Differential_Data}
RNA_Metadata_NoRep <- RNA_Metadata %>%
  filter(!grepl("R$",Individual))

Filt_RMG0_RNA_fc_PerDay_NoRep <- Filt_RMG0_RNA_fc_PerDay %>%
  dplyr::select(-(contains("R")))

RNA_Metadata_NoRep$dgelist <- c(rep(c("Human_Day0","Human_Day2","Human_Day4","Human_Day5","Human_Day15","Human_Day30","Chimp_Day0","Chimp_Day2","Chimp_Day4","Chimp_Day5","Chimp_Day15","Chimp_Day30"),7))

#create DGEList object
dge_RMGO_PerDay_All <- DGEList(counts = Filt_RMG0_RNA_fc_PerDay_NoRep)
dge_RMGO_PerDay_All$samples$group <- factor(RNA_Metadata_NoRep$dgelist)
dge_RMGO_PerDay_All <- calcNormFactors(dge_RMGO_PerDay_All, method = "TMM")
dge_RMGO_PerDay_All$samples

dim(dge_RMGO_PerDay_All)
# saveRDS(dge_RMGO_PerDay_All, "data/DGE/Species/concat/RowMeans_PerDay/dge_RMGO_PerDay_All.RDS")
dge_RMGO_All$samples

```

```{r RNASeq_DGE_Differential_Data_Model}
RNA_Metadata_NoRep$Species <- factor(
  RNA_Metadata_NoRep$Species,
  levels = c("C", "H")   # Chimp baseline
)

RNA_Metadata_NoRep$Timepoint <- factor(
  RNA_Metadata_NoRep$Timepoint,
  levels = c("Day0","Day2","Day4","Day5","Day15","Day30")
)

design_int_RMG0_PerDay_All <- model.matrix(~ Species * Timepoint,
                           data = RNA_Metadata_NoRep)

colnames(design_int_RMG0_PerDay_All)
colnames(design_int_RMG0_PerDay_All) <- make.names(colnames(design_int_RMG0_PerDay_All))

# saveRDS(design_int_RMG0_All, "data/DGE/Species/concat/RowMeans_PerDay/design_int_RMG0_All.RDS")
```

```{r RNASeq_DGE_Differential_Data_Model}
dge <- dge_RMGO_PerDay_All
design_int <- design_int_RMG0_PerDay_All

# Step 1: voom first
v1 <- voom(dge, design_int, plot = TRUE)

# saveRDS(v1,"data/DGE/Species/concat/RowMeans_PerDay/v1_RMG0_PerDay_All.RDS")

# Step 2: estimate duplicate correlation on voom-transformed data
corfit <- duplicateCorrelation(v1, design_int, block = RNA_Metadata_NoRep$Individual)
corfit.correlation <- corfit$consensus.correlation

# Step 3: voom again including correlation
v2 <- voom(dge, design_int, plot = TRUE,
           block = RNA_Metadata_NoRep$Individual,
           correlation = corfit.correlation)

# Step 4: fit linear model
fit <- lmFit(v2, design_int, block = RNA_Metadata_NoRep$Individual, correlation = corfit.correlation)
fit <- eBayes(fit)

pal <- rainbow(length(unique(RNA_Metadata_NoRep$Timepoint)))
day <- RNA_Metadata_NoRep$Timepoint

plotDensities(v2, col = pal[as.numeric(day)], legend = FALSE)

# saveRDS(fit, "data/DGE/Species/concat/RowMeans_PerDay/fit_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Differential_Data_Model}
fit <- fit_RMG0_PerDay_All
design_int <- design_int_RMG0_PerDay_All

contrast_matrix <- makeContrasts(

  # Species differences
  HvC_Day0  = SpeciesH,
  HvC_Day2  = SpeciesH + SpeciesH.TimepointDay2,
  HvC_Day4  = SpeciesH + SpeciesH.TimepointDay4,
  HvC_Day5  = SpeciesH + SpeciesH.TimepointDay5,
  HvC_Day15 = SpeciesH + SpeciesH.TimepointDay15,
  HvC_Day30 = SpeciesH + SpeciesH.TimepointDay30,
  
  #Trajectory differences
  H_Day02 = TimepointDay2 + SpeciesH.TimepointDay2,
  H_Day24 = TimepointDay4 + SpeciesH.TimepointDay4 - TimepointDay2 - SpeciesH.TimepointDay2,
  H_Day45 = TimepointDay5 + SpeciesH.TimepointDay5 - TimepointDay4 - SpeciesH.TimepointDay4,
  H_Day515 = TimepointDay15 + SpeciesH.TimepointDay15 - TimepointDay5 - SpeciesH.TimepointDay5,
  H_Day1530 = TimepointDay30 + SpeciesH.TimepointDay30 - TimepointDay15 - SpeciesH.TimepointDay15,
  C_Day02 = TimepointDay2,
  C_Day24 = TimepointDay4 - TimepointDay2,
  C_Day45 = TimepointDay5 - TimepointDay4,
  C_Day515 = TimepointDay15 - TimepointDay5,
  C_Day1530 = TimepointDay30 - TimepointDay15,
  
  # True interaction tests trajectory
  Sig_Sp_inter_Traj02 = SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj24 = SpeciesH.TimepointDay4 - SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj45 = SpeciesH.TimepointDay5 - SpeciesH.TimepointDay4,
  Sig_Sp_inter_Traj515 = SpeciesH.TimepointDay15 - SpeciesH.TimepointDay5,
  Sig_Sp_inter_Traj1530 = SpeciesH.TimepointDay30 - SpeciesH.TimepointDay15,
  
  levels = design_int
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

plotSA(fit2, main = "RNA Model")

results_summary <- decideTests(fit2,
                               adjust.method = "BH",
                               p.value = 0.05)
summary(results_summary)

# saveRDS(fit2, "data/DGE/Species/concat/RowMeans_PerDay/fit2_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Differential_TopTable}
fit2 <- fit2_RMG0_PerDay_All

#Create Human TopTable. using listapply, then you can pull specific comp using the $
TopTables_RNA_names <- colnames(fit2$coefficients) 

TopTable_RNA_All <- do.call(
  rbind,
  lapply(TopTables_RNA_names,function(ct) {
    
    tt <- topTable(
      fit2,
      coef = ct,
      number = Inf,
      sort.by = "p"
    )
    
    #add identifiers
    tt$Gene <- rownames(tt)
    tt$Comparisons <- ct
    
    tt
  })
)

Comparison_names <- unique(TopTable_RNA_All$Comparisons)

# saveRDS(TopTable_RNA_All, "data/DGE/Species/concat/RowMeans/All/TopTable_RNA_All_RMGO_PerDay_All.RDS")
# saveRDS(Comparison_names, "data/DGE/Species/concat/RowMeans/All/Comparison_names_RNA_All_RMGO_PerDay_All.RDS")

head(TopTable_RNA_All)
```

```{r RNASeq_DGE_Differential_TopTable_VolcancoPlots}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All

# Calculate global axis limits
x_limits <- range(TopTable_RNA_All$logFC, na.rm = TRUE)
y_limits <- range(-log10(TopTable_RNA_All$P.Value), na.rm = TRUE)

plot <- list()

for (n in Comparison_names) {
  data_n <- TopTable_RNA_All %>% 
    dplyr::filter(Comparisons == n)
  
  plot[[n]] <- generate_volcano_plot(data_n, n) +
    ggplot2::xlim(x_limits) +
    ggplot2::ylim(y_limits)
}

# Print plots
for (n in Comparison_names) {
  print(plot[[n]])
}
```

```{r RNASeq_DGE_Differential_TopTable_Subsetting0.05}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All

RNA_sets <- map(
  Comparison_names,
  ~ {
    df <- TopTable_RNA_All %>%
      filter(Comparisons == paste0(.x))

    list(
      DEGs = df %>% filter(adj.P.Val < 0.05),
      NonDEGs = df %>% filter(adj.P.Val >= 0.05)
    )
  }
)


names(RNA_sets) <- paste0(Comparison_names)

# saveRDS(RNA_sets, "data/DGE/Species/concat/RowMeans_PerDay/RNA_sets_RMG0_PerDay_All.RDS")
```

#####Trajectory

```{r RNASeq_DGE_Trajectory_FC}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All
RNA_sets <- RNA_sets_RMG0_PerDay_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Traj02_genes <- unique(c(RNA_sets$H_Day02$DEGs$Gene,RNA_sets$C_Day02$DEGs$Gene))
Traj24_genes <- unique(c(RNA_sets$H_Day24$DEGs$Gene,RNA_sets$C_Day24$DEGs$Gene))
Traj45_genes <- unique(c(RNA_sets$H_Day45$DEGs$Gene,RNA_sets$C_Day45$DEGs$Gene))
Traj515_genes <- unique(c(RNA_sets$H_Day515$DEGs$Gene,RNA_sets$C_Day515$DEGs$Gene))
Traj1530_genes <- unique(c(RNA_sets$H_Day1530$DEGs$Gene,RNA_sets$C_Day1530$DEGs$Gene))

cluster_lists <- list(
 Traj02_genes  = Traj02_genes,
  Traj24_genes  = Traj24_genes,
  Traj45_genes  = Traj45_genes,
  Traj515_genes  = Traj515_genes,
  Traj1530_genes  = Traj1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


# saveRDS(TopTable_RNA_Traj, "data/DGE/Species/concat/RowMeans_PerDay/TopTable_RNA_Traj_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Trajectory_FC}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All
RNA_sets <- RNA_sets_RMG0_PerDay_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Traj02_genes <- unique(c(RNA_sets$H_Day02$DEGs$Gene,RNA_sets$C_Day02$DEGs$Gene))
Traj24_genes <- unique(c(RNA_sets$H_Day24$DEGs$Gene,RNA_sets$C_Day24$DEGs$Gene))
Traj45_genes <- unique(c(RNA_sets$H_Day45$DEGs$Gene,RNA_sets$C_Day45$DEGs$Gene))
Traj515_genes <- unique(c(RNA_sets$H_Day515$DEGs$Gene,RNA_sets$C_Day515$DEGs$Gene))
Traj1530_genes <- unique(c(RNA_sets$H_Day1530$DEGs$Gene,RNA_sets$C_Day1530$DEGs$Gene))

cluster_lists <- list(
 Traj02_genes  = Traj02_genes,
  Traj24_genes  = Traj24_genes,
  Traj45_genes  = Traj45_genes,
  Traj515_genes  = Traj515_genes,
  Traj1530_genes  = Traj1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


# saveRDS(TopTable_RNA_Traj, "data/DGE/Species/concat/RowMeans_PerDay/TopTable_RNA_Traj_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Trajectory_Directionality}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
fit2 <- fit2_RMG0_PerDay_All

traj_info <- list(
  Traj02_genes = list(coef = "H_Day02", comp = "Day02"),
  Traj24_genes = list(coef = "H_Day24", comp = "Day24"),
  Traj45_genes = list(coef = "H_Day45", comp = "Day45"),
  Traj515_genes = list(coef ="H_Day515", comp = "Day515"),
 Traj1530_genes = list(coef = "H_Day1530", comp = "Day1530")
)

direction_results <- setNames(
  lapply(names(traj_info), function(name) {

    info <- traj_info[[name]]

    get_fc_directions(
      traj_label = name,
      coef_name = info$coef,
      comparison_label = info$comp,
      top_table_all = TopTable_RNA_All,
      fit_obj = fit2
    )

  }),
  names(traj_info)
)

# saveRDS(direction_results, "data/DGE/Species/concat/RowMeans_PerDay/HTrajectory_Directions_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Trajectory_Directionality_FC}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All
RNA_sets <- HTrajectory_Directions_RMG0_PerDay_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

aa <- unique(RNA_sets$Traj02_genes$all$Gene)
ab <- unique(RNA_sets$Traj02_genes$H_pos_C_neg$Gene)
ac <- unique(RNA_sets$Traj02_genes$H_neg_C_pos$Gene)
ad <- unique(RNA_sets$Traj02_genes$Both_pos$Gene)
ae <- unique(RNA_sets$Traj02_genes$Both_neg$Gene)

ba <- unique(RNA_sets$Traj24_genes$all$Gene)
bb <- unique(RNA_sets$Traj24_genes$H_pos_C_neg$Gene)
bc <- unique(RNA_sets$Traj24_genes$H_neg_C_pos$Gene)
bd <- unique(RNA_sets$Traj24_genes$Both_pos$Gene)
be <- unique(RNA_sets$Traj24_genes$Both_neg$Gene)

ca <- unique(RNA_sets$Traj45_genes$all$Gene)
cb <- unique(RNA_sets$Traj45_genes$H_pos_C_neg$Gene)
cc <- unique(RNA_sets$Traj45_genes$H_neg_C_pos$Gene)
cd <- unique(RNA_sets$Traj45_genes$Both_pos$Gene)
ce <- unique(RNA_sets$Traj45_genes$Both_neg$Gene)

da <- unique(RNA_sets$Traj515_genes$all$Gene)
db <- unique(RNA_sets$Traj515_genes$H_pos_C_neg$Gene)
dc <- unique(RNA_sets$Traj515_genes$H_neg_C_pos$Gene)
dd <- unique(RNA_sets$Traj515_genes$Both_pos$Gene)
de <- unique(RNA_sets$Traj515_genes$Both_neg$Gene)

ea <- unique(RNA_sets$Traj1530_genes$all$Gene)
eb <- unique(RNA_sets$Traj1530_genes$H_pos_C_neg$Gene)
ec <- unique(RNA_sets$Traj1530_genes$H_neg_C_pos$Gene)
ed <- unique(RNA_sets$Traj1530_genes$Both_pos$Gene)
ee <- unique(RNA_sets$Traj1530_genes$Both_neg$Gene)

cluster_lists <- list(
  Inter02_All = aa,
  Inter02_HumanPos = ab,
  Inter02_ChimpPos = ac,
  Inter02_Both_pos = ad,
  Inter02_Both_neg = ae,
  Inter24_All = ba,
  Inter24_HumanPos = bb,
  Inter24_ChimpPos = bc,
  Inter24_Both_pos = bd,
  Inter24_Both_neg = be,
  Inter45_All = ca,
  Inter45_HumanPos = cb,
  Inter45_ChimpPos = cc,
  Inter45_Both_pos = cd,
  Inter45_Both_neg = ce,
  Inter515_All = da,
  Inter515_HumanPos = db,
  Inter515_ChimpPos = dc,
  Inter515_Both_pos = dd,
  Inter515_Both_neg = de,
  Inter1530_All = ea,
  Inter1530_HumanPos = eb,
  Inter1530_ChimpPos = ec,
  Inter1530_Both_pos = ed,
  Inter1530_Both_neg = ee
)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Traj)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


```

```{r RNASeq_DGE_Trajectory_EnrichGo}
fit2 <- fit2_RMG0_PerDay_All
v <- v1_RMG0_PerDay_All

all_go_results <- lapply(names(direction_results), function(traj) {

  res <- direction_results[[traj]]

  gene_sets <- list(
    H_pos_C_neg = res$H_pos_C_neg,
    H_neg_C_pos = res$H_neg_C_pos,
    Both_pos    = res$Both_pos,
    Both_neg    = res$Both_neg,
    All = res$all
  )

  go <- Enrich_Go_sets(gene_sets, v)

  return(go)
})

names(all_go_results) <- names(direction_results)


# saveRDS(all_go_results, "data/DGE/Species/concat/RowMeans_PerDay/Trajectory_go_results_RMG0_PerDay_All.RDS")

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
H_comp <- "H_Day02"
C_comp <- "C_Day02"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest <- RNA_sets_RMG0_PerDay_All$Sig_Sp_inter_Traj02$DEGs$Gene

df_wide$highlight <- ifelse(df_wide$Gene %in% genes_of_interest,
                           "Interaction DEG", "Other")

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("Interaction DEG" = "red", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```


```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
H_comp <- "H_Day24"
C_comp <- "C_Day24"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest <- RNA_sets_RMG0_PerDay_All$Sig_Sp_inter_Traj24$DEGs$Gene

df_wide$highlight <- ifelse(df_wide$Gene %in% genes_of_interest,
                           "Interaction DEG", "Other")

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("Interaction DEG" = "red", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
H_comp <- "H_Day515"
C_comp <- "C_Day515"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest <- RNA_sets_RMG0_PerDay_All$Sig_Sp_inter_Traj515$DEGs$Gene

df_wide$highlight <- ifelse(df_wide$Gene %in% genes_of_interest,
                           "Interaction DEG", "Other")

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("Interaction DEG" = "red", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
H_comp <- "H_Day1530"
C_comp <- "C_Day1530"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)


genes_of_interest <- RNA_sets_RMG0_PerDay_All$Sig_Sp_inter_Traj1530$DEGs$Gene

df_wide$highlight <- ifelse(df_wide$Gene %in% genes_of_interest,
                           "Interaction DEG", "Other")

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]], color = highlight)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("Interaction DEG" = "red", "Other" = "grey70")) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = min(df_wide[[H_comp]], na.rm = TRUE),
    y = max(df_wide[[C_comp]], na.rm = TRUE),
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 0,
    vjust = 1
  ) +
  coord_cartesian(xlim = x_limits, ylim = y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp),
    color = "Gene Set"
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
H_comp <- "H_Day45"
C_comp <- "C_Day45"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  xlim(x_limits) +
  ylim(y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )
```





#####Interactions

```{r RNASeq_DGE_Interaction_FC}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All
RNA_sets <- RNA_sets_RMG0_PerDay_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Inter_02_genes <- unique(RNA_sets$Sig_Sp_inter_Traj02$DEGs$Gene)
Inter_24_genes <- unique(RNA_sets$Sig_Sp_inter_Traj24$DEGs$Gene)
Inter_45_genes <- unique(RNA_sets$Sig_Sp_inter_Traj45$DEGs$Gene)
Inter_515_genes <- unique(RNA_sets$Sig_Sp_inter_Traj515$DEGs$Gene)
Inter_1530_genes <- unique(RNA_sets$Sig_Sp_inter_Traj1530$DEGs$Gene)

cluster_lists <- list(
  Inter_02_genes  = Inter_02_genes,
  Inter_24_genes  = Inter_24_genes,
  Inter_45_genes  = Inter_45_genes,
  Inter_515_genes  = Inter_515_genes,
  Inter_1530_genes  = Inter_1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Inter)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Inter)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


# saveRDS(TopTable_RNA_Traj, "data/DGE/Species/concat/RowMeans_PerDay/TopTable_RNA_Traj_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Interaction_Directionality}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
fit2 <- fit2_RMG0_PerDay_All

traj_info <- list(
  InterTraj02 = list(coef = "Sig_Sp_inter_Traj02", comp = "Day02"),
  InterTraj24 = list(coef = "Sig_Sp_inter_Traj24", comp = "Day24"),
  InterTraj45 = list(coef = "Sig_Sp_inter_Traj45", comp = "Day45"),
  InterTraj515 = list(coef = "Sig_Sp_inter_Traj515", comp = "Day515"),
  InterTraj1530 = list(coef = "Sig_Sp_inter_Traj1530", comp = "Day1530")
)

direction_results <- setNames(
  lapply(names(traj_info), function(name) {

    info <- traj_info[[name]]

    get_fc_directions(
      traj_label = name,
      coef_name = info$coef,
      comparison_label = info$comp,
      top_table_all = TopTable_RNA_All,
      fit_obj = fit2
    )

  }),
  names(traj_info)
)

# saveRDS(direction_results, "data/DGE/Species/concat/RowMeans_PerDay/Interaction_Directions_RMG0_PerDay_All.RDS")
```

```{r RNASeq_DGE_Interaction_Directionality_FC}

TopTable_RNA_Traj<- TopTable_RNA_Traj_RMG0_PerDay_All
TopTable_RNA_All <- TopTable_RNA_All_RMGO_PerDay_All
Comparison_names <- Comparison_names_RMGO_PerDay_All
RNA_sets <- Interaction_Directions_RMG0_PerDay_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Traj <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

aa <- unique(RNA_sets$InterTraj02$all$Gene)
ab <- unique(RNA_sets$InterTraj02$H_pos_C_neg$Gene)
ac <- unique(RNA_sets$InterTraj02$H_neg_C_pos$Gene)
ad <- unique(RNA_sets$InterTraj02$Both_pos$Gene)
ae <- unique(RNA_sets$InterTraj02$Both_neg$Gene)

ba <- unique(RNA_sets$InterTraj24$all$Gene)
bb <- unique(RNA_sets$InterTraj24$H_pos_C_neg$Gene)
bc <- unique(RNA_sets$InterTraj24$H_neg_C_pos$Gene)
bd <- unique(RNA_sets$InterTraj24$Both_pos$Gene)
be <- unique(RNA_sets$InterTraj24$Both_neg$Gene)

ca <- unique(RNA_sets$InterTraj45$all$Gene)
cb <- unique(RNA_sets$InterTraj45$H_pos_C_neg$Gene)
cc <- unique(RNA_sets$InterTraj45$H_neg_C_pos$Gene)
cd <- unique(RNA_sets$InterTraj45$Both_pos$Gene)
ce <- unique(RNA_sets$InterTraj45$Both_neg$Gene)

da <- unique(RNA_sets$InterTraj515$all$Gene)
db <- unique(RNA_sets$InterTraj515$H_pos_C_neg$Gene)
dc <- unique(RNA_sets$InterTraj515$H_neg_C_pos$Gene)
dd <- unique(RNA_sets$InterTraj515$Both_pos$Gene)
de <- unique(RNA_sets$InterTraj515$Both_neg$Gene)

ea <- unique(RNA_sets$InterTraj1530$all$Gene)
eb <- unique(RNA_sets$InterTraj1530$H_pos_C_neg$Gene)
ec <- unique(RNA_sets$InterTraj1530$H_neg_C_pos$Gene)
ed <- unique(RNA_sets$InterTraj1530$Both_pos$Gene)
ee <- unique(RNA_sets$InterTraj1530$Both_neg$Gene)

cluster_lists <- list(
  Inter02_All = aa,
  Inter02_HumanPos = ab,
  Inter02_ChimpPos = ac,
  Inter02_Both_pos = ad,
  Inter02_Both_neg = ae,
  Inter24_All = ba,
  Inter24_HumanPos = bb,
  Inter24_ChimpPos = bc,
  Inter24_Both_pos = bd,
  Inter24_Both_neg = be,
  Inter45_All = ca,
  Inter45_HumanPos = cb,
  Inter45_ChimpPos = cc,
  Inter45_Both_pos = cd,
  Inter45_Both_neg = ce,
  Inter515_All = da,
  Inter515_HumanPos = db,
  Inter515_ChimpPos = dc,
  Inter515_Both_pos = dd,
  Inter515_Both_neg = de,
  Inter1530_All = ea,
  Inter1530_HumanPos = eb,
  Inter1530_ChimpPos = ec,
  Inter1530_Both_pos = ed,
  Inter1530_Both_neg = ee
)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Inter)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


```

```{r RNASeq_DGE_Interaction_EnrichGo}
fit2 <- fit2_RMG0_PerDay_All
v <- v1_RMG0_PerDay_All

all_go_results <- lapply(names(direction_results), function(traj) {

  res <- direction_results[[traj]]

  gene_sets <- list(
    H_pos_C_neg = res$H_pos_C_neg,
    H_neg_C_pos = res$H_neg_C_pos,
    Both_pos    = res$Both_pos,
    Both_neg    = res$Both_neg,
    All = res$all
  )

  go <- Enrich_Go_sets(gene_sets, v)

  return(go)
})

names(all_go_results) <- names(direction_results)


# saveRDS(all_go_results, "data/DGE/Species/concat/RowMeans_PerDay/Interaction_go_results_RMG0_PerDay_All.RDS")

```

####RMGO_NoD4

```{r RNASeq_DGE_Trajectory_Data}
RNA_Metadata_NoD4_NoRep <- RNA_Metadata_NoD4 %>%
  filter(!grepl("R$",Individual))

Filt_RMG0_RNA_fc_NoD4_NoRep <- Filt_RMG0_RNA_fc_NoD4 %>%
  dplyr::select(-(contains("R")))

RNA_Metadata_NoD4_NoRep$dgelist <- c(rep(c("Human_Day0","Human_Day2","Human_Day5","Human_Day15","Human_Day30","Chimp_Day0","Chimp_Day2","Chimp_Day5","Chimp_Day15","Chimp_Day30"),7))

#create DGEList object
dge <- DGEList(counts = Filt_RMG0_RNA_fc_NoD4_NoRep)
dge$samples$group <- factor(RNA_Metadata_NoD4_NoRep$dgelist)
dge <- calcNormFactors(dge, method = "TMM")
dge$samples

# dim(dge)
saveRDS(dge, "data/DGE/Species/concat/RNA_dge_matrix.RDS")
# dge$samples

```



```{r RNASeq_DGE_Trajectory_Data_Model}
RNA_Metadata_NoD4_NoRep$Species <- factor(
  RNA_Metadata_NoD4_NoRep$Species,
  levels = c("C", "H")   # Chimp baseline
)

RNA_Metadata_NoD4_NoRep$Timepoint <- factor(
  RNA_Metadata_NoD4_NoRep$Timepoint,
  levels = c("Day0","Day2","Day5","Day15","Day30")
)

design_int <- model.matrix(~ Species * Timepoint,
                           data = RNA_Metadata_NoD4_NoRep)

colnames(design_int)
colnames(design_int) <- make.names(colnames(design_int))

# saveRDS(design_int, "data/DGE/Species/concat/design_int.RDS")
```


```{r RNASeq_DGE_Trajectory_Data_Model}
# Step 1: voom first
v1 <- voom(dge, design_int, plot = TRUE)

# Step 2: estimate duplicate correlation on voom-transformed data
corfit <- duplicateCorrelation(v1, design_int, block = RNA_Metadata_NoD4_NoRep$Individual)
corfit.correlation <- corfit$consensus.correlation

# Step 3: voom again including correlation
v2 <- voom(dge, design_int, plot = TRUE,
           block = RNA_Metadata_NoD4_NoRep$Individual,
           correlation = corfit.correlation)

# Step 4: fit linear model
fit <- lmFit(v2, design_int, block = RNA_Metadata_NoD4_NoRep$Individual, correlation = corfit.correlation)
fit <- eBayes(fit)

pal <- rainbow(length(unique(RNA_Metadata_NoD4_NoRep$Timepoint)))
day <- RNA_Metadata_NoD4_NoRep$Timepoint

plotDensities(v2, col = pal[as.numeric(day)], legend = FALSE)

# saveRDS(fit, "data/DGE/Species/concat/fit.RDS")
```


```{r RNASeq_DGE_Trajectory_Data_Model}
contrast_matrix <- makeContrasts(

  # Species differences
  HvC_Day0  = SpeciesH,
  HvC_Day2  = SpeciesH + SpeciesH.TimepointDay2,
  HvC_Day5  = SpeciesH + SpeciesH.TimepointDay5,
  HvC_Day15 = SpeciesH + SpeciesH.TimepointDay15,
  HvC_Day30 = SpeciesH + SpeciesH.TimepointDay30,
  
  #Trajectory differences
  H_Day02 = TimepointDay2 + SpeciesH.TimepointDay2,
  H_Day25 = TimepointDay5 + SpeciesH.TimepointDay5 - TimepointDay2 - SpeciesH.TimepointDay2,
  H_Day515 = TimepointDay15 + SpeciesH.TimepointDay15 - TimepointDay5 - SpeciesH.TimepointDay5,
  H_Day1530 = TimepointDay30 + SpeciesH.TimepointDay30 - TimepointDay15 - SpeciesH.TimepointDay15,
  C_Day02 = TimepointDay2,
  C_Day25 = TimepointDay5 - TimepointDay2,
  C_Day515 = TimepointDay15 - TimepointDay5,
  C_Day1530 = TimepointDay30 - TimepointDay15,
  
  # True interaction tests trajectory
  Sig_Sp_inter_Traj02 = SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj25 = SpeciesH.TimepointDay5 - SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj515 = SpeciesH.TimepointDay15 - SpeciesH.TimepointDay5,
  Sig_Sp_inter_Traj1530 = SpeciesH.TimepointDay30 - SpeciesH.TimepointDay15,
  
  levels = design_int
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

plotSA(fit2, main = "RNA Model")

results_summary <- decideTests(fit2,
                               adjust.method = "BH",
                               p.value = 0.05)
summary(results_summary)

# saveRDS(fit2, "data/DGE/Species/concat/fit2.RDS")
```


```{r RNASeq_DGE_Trajectory_TopTable}
#Create Human TopTable. using listapply, then you can pull specific comp using the $
TopTables_RNA_names <- colnames(fit2$coefficients) 

# colnames(fit2$coefficients)

TopTable_RNA_All <- do.call(
  rbind,
  lapply(TopTables_RNA_names,function(ct) {
    
    tt <- topTable(
      fit2,
      coef = ct,
      number = Inf,
      sort.by = "p"
    )
    
    #add identifiers
    tt$Gene <- rownames(tt)
    tt$Comparisons <- ct
    
    tt
  })
)

Comparison_names <- unique(TopTable_RNA_All$Comparisons)

# saveRDS(TopTable_RNA_All, "data/DGE/Species/concat/TopTable_RNA_All.RDS")
# saveRDS(Comparison_names, "data/DGE/Species/concat/Comparison_names.RDS")

head(TopTable_RNA_All)
```



```{r RNASeq_DGE_Trajectory_TopTable_VolcancoPlots}

# Calculate global axis limits
x_limits <- range(TopTable_RNA_All$logFC, na.rm = TRUE)
y_limits <- range(-log10(TopTable_RNA_All$P.Value), na.rm = TRUE)

plot <- list()

for (n in Comparison_names) {
  data_n <- TopTable_RNA_All %>% 
    dplyr::filter(Comparisons == n)
  
  plot[[n]] <- generate_volcano_plot(data_n, n) +
    ggplot2::xlim(x_limits) +
    ggplot2::ylim(y_limits)
}

# Print plots
for (n in Comparison_names) {
  print(plot[[n]])
}
```
```{r RNASeq_DGE_Trajectory_TopTable_Subsetting0.05}
RNA_sets <- map(
  Comparison_names,
  ~ {
    df <- TopTable_RNA_All %>%
      filter(Comparisons == paste0(.x))

    list(
      DEGs = df %>% filter(adj.P.Val < 0.05),
      NonDEGs = df %>% filter(adj.P.Val >= 0.05)
    )
  }
)


names(RNA_sets) <- paste0(Comparison_names)

# saveRDS(RNA_sets, "data/DGE/Species/concat/RNA_sets.RDS")
```

```{r}

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_02_genes <- unique(RNA_sets$Sig_Sp_inter_Traj02$DEGs$Gene)
Inter_25_genes <- unique(RNA_sets$Sig_Sp_inter_Traj25$DEGs$Gene)
Inter_515_genes <- unique(RNA_sets$Sig_Sp_inter_Traj515$DEGs$Gene)
Inter_1530_genes <- unique(RNA_sets$Sig_Sp_inter_Traj1530$DEGs$Gene)

cluster_lists <- list(
  Inter_02_genes  = Inter_02_genes,
  Inter_25_genes  = Inter_25_genes,
  Inter_515_genes  = Inter_515_genes,
  Inter_1530_genes  = Inter_1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)
```


```{r}
TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_02_genes <- unique(RNA_sets$Sig_Sp_inter_Traj02$DEGs$Gene)
Inter_25_genes <- unique(RNA_sets$Sig_Sp_inter_Traj25$DEGs$Gene)
Inter_515_genes <- unique(RNA_sets$Sig_Sp_inter_Traj515$DEGs$Gene)
Inter_1530_genes <- unique(RNA_sets$Sig_Sp_inter_Traj1530$DEGs$Gene)

cluster_lists <- list(
  Inter_02_genes  = Inter_02_genes,
  Inter_25_genes  = Inter_25_genes,
  Inter_515_genes  = Inter_515_genes,
  Inter_1530_genes  = Inter_1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)

```

```{r RNASeq_DGE_Interactions_Day2, fig.width = 20, fig.height= 30}
int_Traj2 <- topTable(fit2, coef="Sig_Sp_inter_Traj02",number=Inf)
top_int_Traj2 <- topTable(fit2, coef="Sig_Sp_inter_Traj02", number=200)
top_genes <- rownames(top_int_Traj2)

int_Traj2 <- topTable(fit2, coef="Sig_Sp_inter_Traj02",number=Inf)
sig_int_Traj2 <- top_int_Traj2[int_Traj2$adj.P.Val < 0.05, ]
sig_genes <- rownames(sig_int_Traj2)

library(dplyr)
library(tidyr)

expr_mat <- v2$E[top_genes, ]  # expression for top genes

plot_df <- as.data.frame(t(expr_mat))
plot_df$Sample <- rownames(plot_df)

plot_df <- cbind(plot_df, RNA_Metadata_NoD4_NoRep)

# Make time numeric for ordering
plot_df$Time <- factor(plot_df$Cond,
                       levels=c("H_Day0","H_Day2","H_Day5","H_Day15","H_Day30",
                                "C_Day0","C_Day2","C_Day5","C_Day15","C_Day30"))

library(ggplot2)

gene_to_plot <- top_genes[1]

ggplot(plot_df,
       aes(x=Cond,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Trajectory:", gene_to_plot),
       y="log2 CPM")

plot_df$TimeOnly <- gsub("H_|C_", "", plot_df$Cond)
plot_df$TimeOnly <- factor(plot_df$TimeOnly,
                           levels=c("Day0","Day2","Day5","Day15","Day30"))

ggplot(plot_df,
       aes(x=TimeOnly,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Interaction trajectory:", gene_to_plot),
       x="Time",
       y="log2 CPM")

plot_long <- plot_df %>%
  pivot_longer(cols=all_of(top_genes),
               names_to="Gene",
               values_to="Expression")

ggplot(plot_long,
       aes(x=TimeOnly,
           y=Expression,
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line") +
  stat_summary(fun=mean, geom="point") +
  facet_wrap(~Gene, scales="free_y") +
  theme_classic()

print(rownames(top_int_Traj2))


```

```{r}
int_Traj2 <- topTable(fit2, coef="Sig_Sp_inter_Traj02", number=Inf)

sig_int_Traj2 <- int_Traj2 %>%
  dplyr::filter(adj.P.Val < 0.05)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

df_dir_02 <- TopTable_RNA_All_TrajectoryFC %>%
  
  filter(Comparisons %in% c("H_Day02", "C_Day02")) %>%
  
  mutate(Species = ifelse(grepl("^H_", Comparisons), "H", "C")) %>%
  
  group_by(Gene, Species) %>%
  summarise(logFC = mean(logFC, na.rm = TRUE), .groups = "drop") %>%
  
  pivot_wider(names_from = Species, values_from = logFC) %>%
  
  filter(!is.na(H), !is.na(C)) %>%
  
  filter(H * C < 0)

sig_int_Traj2$Gene <- rownames(sig_int_Traj2)


df_dir_02_combo <- df_dir_02 %>%
  inner_join(sig_int_Traj2, by = "Gene") %>%
  mutate(
    direction = case_when(
      H > C ~ "Human_increasing",
      C > H ~ "Chimp_increasing",
      TRUE ~ NA_character_
    )
  )

df_dir_02_human <- df_dir_02_combo %>%
  filter(direction == "Human_increasing")

df_dir_02_chimp <- df_dir_02_combo %>%
  filter(direction == "Chimp_increasing")
```

```{r}
TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_02_genes <- unique(RNA_sets$Sig_Sp_inter_Traj02$DEGs$Gene)
df_dir_02_combo_genes <- unique(df_dir_02_combo$Gene)
df_dir_02_human_genes <- unique(df_dir_02_human$Gene)
df_dir_02_chimp_genes <- unique(df_dir_02_chimp$Gene)

cluster_lists <- list(
  Inter_02_genes  = Inter_02_genes,
  df_dir_02_combo_genes  = df_dir_02_combo_genes,
  df_dir_02_human_genes  = df_dir_02_human_genes,
  df_dir_02_chimp_genes  = df_dir_02_chimp_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)

```


```{r}
int_Traj5 <- topTable(fit2, coef="Sig_Sp_inter_Traj25", number=Inf)

sig_int_Traj5 <- int_Traj5 %>%
  dplyr::filter(adj.P.Val < 0.05)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

df_dir_25 <- TopTable_RNA_All_TrajectoryFC %>%
  
  filter(Comparisons %in% c("H_Day25", "C_Day25")) %>%
  
  mutate(Species = ifelse(grepl("^H_", Comparisons), "H", "C")) %>%
  
  group_by(Gene, Species) %>%
  summarise(logFC = mean(logFC, na.rm = TRUE), .groups = "drop") %>%
  
  pivot_wider(names_from = Species, values_from = logFC) %>%
  
  filter(!is.na(H), !is.na(C)) %>%
  
  filter(H * C < 0)

sig_int_Traj5$Gene <- rownames(sig_int_Traj5)


df_dir_25_combo <- df_dir_25 %>%
  inner_join(sig_int_Traj5, by = "Gene") %>%
  mutate(
    direction = case_when(
      H > C ~ "Human_increasing",
      C > H ~ "Chimp_increasing",
      TRUE ~ NA_character_
    )
  )

df_dir_25_human <- df_dir_25_combo %>%
  filter(direction == "Human_increasing")

df_dir_25_chimp <- df_dir_25_combo %>%
  filter(direction == "Chimp_increasing")
```


```{r}
TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_25_genes <- unique(RNA_sets$Sig_Sp_inter_Traj25$DEGs$Gene)
df_dir_25_combo_genes <- unique(df_dir_25_combo$Gene)
df_dir_25_human_genes <- unique(df_dir_25_human$Gene)
df_dir_25_chimp_genes <- unique(df_dir_25_chimp$Gene)

cluster_lists <- list(
  Inter_25_genes  = Inter_25_genes,
  df_dir_25_combo_genes  = df_dir_25_combo_genes,
  df_dir_25_human_genes  = df_dir_25_human_genes,
  df_dir_25_chimp_genes  = df_dir_25_chimp_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)

```

```{r}
int_Traj2 <- topTable(fit2, coef="Sig_Sp_inter_Traj02", number=Inf)

sig_int_Traj2 <- int_Traj2 %>%
  dplyr::filter(adj.P.Val < 0.05)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

df_dir_02 <- TopTable_RNA_All_TrajectoryFC %>%
  
  filter(Comparisons %in% c("H_Day02", "C_Day02")) %>%
  
  mutate(Species = ifelse(grepl("^H_", Comparisons), "H", "C")) %>%
  
  group_by(Gene, Species) %>%
  summarise(logFC = mean(logFC, na.rm = TRUE), .groups = "drop") %>%
  
  pivot_wider(names_from = Species, values_from = logFC) %>%
  
  filter(!is.na(H), !is.na(C)) %>%
  
  filter(H * C < 0)

sig_int_Traj2$Gene <- rownames(sig_int_Traj2)


df_dir_02_combo <- df_dir_02 %>%
  inner_join(sig_int_Traj2, by = "Gene") %>%
  mutate(
    direction = case_when(
      H > C ~ "Human_increasing",
      C > H ~ "Chimp_increasing",
      TRUE ~ NA_character_
    )
  )

df_dir_02_human <- df_dir_02_combo %>%
  filter(direction == "Human_increasing")

df_dir_02_chimp <- df_dir_02_combo %>%
  filter(direction == "Chimp_increasing")
```

```{r}
TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_25_genes <- unique(RNA_sets$Sig_Sp_inter_Traj25$DEGs$Gene)
df_dir_25_combo_genes <- unique(df_dir_25_combo$Gene)
df_dir_25_human_genes <- unique(df_dir_25_human$Gene)
df_dir_25_chimp_genes <- unique(df_dir_25_chimp$Gene)

cluster_lists <- list(
  Inter_25_genes  = Inter_25_genes,
  df_dir_25_combo_genes  = df_dir_25_combo_genes,
  df_dir_25_human_genes  = df_dir_25_human_genes,
  df_dir_25_chimp_genes  = df_dir_25_chimp_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)
```

```{r}
int_Traj15 <- topTable(fit2, coef="Sig_Sp_inter_Traj515", number=Inf)

sig_int_Traj15 <- int_Traj15 %>%
  dplyr::filter(adj.P.Val < 0.05)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

df_dir_515 <- TopTable_RNA_All_TrajectoryFC %>%
  
  filter(Comparisons %in% c("H_Day515", "C_Day515")) %>%
  
  mutate(Species = ifelse(grepl("^H_", Comparisons), "H", "C")) %>%
  
  group_by(Gene, Species) %>%
  summarise(logFC = mean(logFC, na.rm = TRUE), .groups = "drop") %>%
  
  pivot_wider(names_from = Species, values_from = logFC) %>%
  
  filter(!is.na(H), !is.na(C)) %>%
  
  filter(H * C < 0)

sig_int_Traj15$Gene <- rownames(sig_int_Traj15)


df_dir_515_combo <- df_dir_515 %>%
  inner_join(sig_int_Traj15, by = "Gene") %>%
  mutate(
    direction = case_when(
      H > C ~ "Human_increasing",
      C > H ~ "Chimp_increasing",
      TRUE ~ NA_character_
    )
  )

df_dir_515_human <- df_dir_515_combo %>%
  filter(direction == "Human_increasing")

df_dir_515_chimp <- df_dir_515_combo %>%
  filter(direction == "Chimp_increasing")
```

```{r}
TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_515_genes <- unique(RNA_sets$Sig_Sp_inter_Traj515$DEGs$Gene)
df_dir_515_combo_genes <- unique(df_dir_515_combo$Gene)
df_dir_515_human_genes <- unique(df_dir_515_human$Gene)
df_dir_515_chimp_genes <- unique(df_dir_515_chimp$Gene)

cluster_lists <- list(
  Inter_515_genes  = Inter_515_genes,
  df_dir_515_combo_genes  = df_dir_515_combo_genes,
  df_dir_515_human_genes  = df_dir_515_human_genes,
  df_dir_515_chimp_genes  = df_dir_515_chimp_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)
```

```{r}
int_Traj30 <- topTable(fit2, coef="Sig_Sp_inter_Traj1530", number=Inf)

sig_int_Traj30 <- int_Traj30 %>%
  dplyr::filter(adj.P.Val < 0.05)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

df_dir_1530 <- TopTable_RNA_All_TrajectoryFC %>%
  
  filter(Comparisons %in% c("H_Day1530", "C_Day1530")) %>%
  
  mutate(Species = ifelse(grepl("^H_", Comparisons), "H", "C")) %>%
  
  group_by(Gene, Species) %>%
  summarise(logFC = mean(logFC, na.rm = TRUE), .groups = "drop") %>%
  
  pivot_wider(names_from = Species, values_from = logFC) %>%
  
  filter(!is.na(H), !is.na(C)) %>%
  
  filter(H * C < 0)

sig_int_Traj30$Gene <- rownames(sig_int_Traj30)


df_dir_1530_combo <- df_dir_1530 %>%
  inner_join(sig_int_Traj30, by = "Gene") %>%
  mutate(
    direction = case_when(
      H > C ~ "Human_increasing",
      C > H ~ "Chimp_increasing",
      TRUE ~ NA_character_
    )
  )

df_dir_1530_human <- df_dir_1530_combo %>%
  filter(direction == "Human_increasing")

df_dir_1530_chimp <- df_dir_1530_combo %>%
  filter(direction == "Chimp_increasing")
```

```{r}
TopTable_RNA_All$AbsFC <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_All_TrajectoryFC <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day25","H_Day515","H_Day1530",
    "C_Day02","C_Day25","C_Day515","C_Day1530"
  ))

Inter_1530_genes <- unique(RNA_sets$Sig_Sp_inter_Traj1530$DEGs$Gene)
df_dir_1530_combo_genes <- unique(df_dir_1530_combo$Gene)
df_dir_1530_human_genes <- unique(df_dir_1530_human$Gene)
df_dir_1530_chimp_genes <- unique(df_dir_1530_chimp$Gene)

cluster_lists <- list(
  Inter_1530_genes  = Inter_1530_genes,
  df_dir_1530_combo_genes  = df_dir_1530_combo_genes,
  df_dir_1530_human_genes  = df_dir_1530_human_genes,
  df_dir_1530_chimp_genes  = df_dir_1530_chimp_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_All_TrajectoryFC)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)
```


```{r }

make_cardiac_table <- function(fit, coef_name) {

  library(limma)
  library(dplyr)
  library(tibble)
  library(clusterProfiler)
  library(org.Hs.eg.db)
  library(AnnotationDbi)

  # -----------------------------
  # 1. Differential expression
  # -----------------------------
  de <- topTable(fit, coef = coef_name, number = Inf) %>%
    rownames_to_column("ENSEMBL") %>%
    mutate(ENSEMBL = sub("\\..*", "", ENSEMBL))

  # -----------------------------
  # 2. Add gene symbols (HGNC)
  # -----------------------------
  symbol_map <- AnnotationDbi::select(
    org.Hs.eg.db,
    keys = unique(de$ENSEMBL),
    keytype = "ENSEMBL",
    columns = c("SYMBOL")
  )

  de <- de %>%
    left_join(symbol_map, by = "ENSEMBL")

  # Fill missing symbols safely
  de$SYMBOL[is.na(de$SYMBOL)] <- de$ENSEMBL[is.na(de$SYMBOL)]

  # -----------------------------
  # 3. Filter genes for GO input (QC step)
  # -----------------------------
  sig_genes <- de %>%
    filter(adj.P.Val < 0.05 & abs(logFC) > 0.5) %>%
    pull(ENSEMBL)

  if (length(sig_genes) < 10) {
    warning("Too few significant genes for GO enrichment")
  }

  # -----------------------------
  # 4. GO enrichment
  # -----------------------------
  background_genes <- de$ENSEMBL
  
  ego <- enrichGO(
  gene     = sig_genes,
  universe = background_genes,
  OrgDb    = org.Hs.eg.db,
  keyType  = "ENSEMBL",
  ont      = "BP",
  readable = FALSE
)

ego_df <- as.data.frame(ego)

heart_regex <- paste(
  "heart|cardiac|cardiovascular|myocard|sarcomere|myofibril|contraction|conduction|circulation|ventricular|atrial|septum|valve|calcium",
  sep = ""
)

cardiac_go <- ego_df %>%
  filter(grepl(heart_regex, Description, ignore.case = TRUE))

cardiac_genes <- cardiac_go %>%
  tidyr::separate_rows(geneID, sep = "/") %>%
  mutate(geneID = sub("\\..*", "", geneID)) %>%
  distinct(geneID) %>%
  pull(geneID)

  # -----------------------------
  # 6. Score genes
  # -----------------------------
  de <- de %>%
    mutate(score = ifelse(ENSEMBL %in% cardiac_genes, 1, 0))

  # -----------------------------
  # 7. Cardiac category system
  # -----------------------------
  de <- de %>%
    mutate(category = case_when(
      score == 1 & adj.P.Val < 0.05 & abs(logFC) > 1 ~ "Strong cardiac",
      score == 1 & (adj.P.Val < 0.05 | abs(logFC) > 0.5) ~ "Moderate cardiac",
      score == 1 ~ "Weak cardiac",
      TRUE ~ "None"
    ))

gene_go_map <- cardiac_go %>%
  dplyr::select(Description, geneID) %>%
  tidyr::separate_rows(geneID, sep = "/") %>%
  group_by(geneID) %>%
  summarise(GO_terms = paste(unique(Description), collapse = "; "), .groups = "drop")

de <- de %>%
  mutate(score_rank = -log10(pmax(adj.P.Val, 1e-300)) * abs(logFC)) %>%
  arrange(desc(score_rank)) %>%
  mutate(Rank = row_number())

  # -----------------------------
  # 8. Ranking (biological relevance score)
  # -----------------------------
  de <- de %>%
    mutate(score_rank = -log10(pmax(adj.P.Val, 1e-300)) * abs(logFC)) %>%
    arrange(desc(score_rank)) %>%
    mutate(Rank = row_number())

  # -----------------------------
  # 9. Final table (NOW INCLUDES SYMBOL)
  # -----------------------------
  final_table <- de %>%
    dplyr::select(Rank, ENSEMBL, SYMBOL, logFC, adj.P.Val, category)

final_table <- de %>%
  dplyr::select(Rank, ENSEMBL, SYMBOL, logFC, adj.P.Val, category) %>%
  left_join(gene_go_map, by = c("ENSEMBL" = "geneID"))

  # -----------------------------
  # 10. QC summary
  # -----------------------------
  qc <- list(
    n_sig_genes = length(sig_genes),
    n_go_terms = nrow(ego_df),
    n_cardiac_terms = nrow(cardiac_go),
    n_cardiac_genes = length(cardiac_genes)
  )

  # -----------------------------
  # 11. Return everything
  # -----------------------------
  return(list(
    table = final_table,
    go = ego_df,
    cardiac_go = cardiac_go,
    cardiac_genes = cardiac_genes,
    ego = ego,
    qc = qc
  ))
}
```

```{r}
resH02 <- make_cardiac_table(fit2, "H_Day02")

final_tableH02 <- resH02$table
go_tableH02 <- resH02$go
cardiac_goH02 <- resH02$cardiac_go

enriched_termsH02 <- go_tableH02 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsH02 <- cardiac_goH02

final_tableH02_StrongCardiac <- final_tableH02 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableH02_StrongCardiac, "data/DGE/final_tableH02_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resH25 <- make_cardiac_table(fit2, "H_Day25")

final_tableH25 <- resH25$table
go_tableH25 <- resH25$go
cardiac_goH25 <- resH25$cardiac_go

enriched_termsH25 <- go_tableH25 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsH25 <- cardiac_goH25

final_tableH25_StrongCardiac <- final_tableH25 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableH25_StrongCardiac, "data/DGE/final_tableH25_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resH515 <- make_cardiac_table(fit2, "H_Day515")

final_tableH515 <- resH515$table
go_tableH515 <- resH515$go
cardiac_goH515 <- resH515$cardiac_go

enriched_termsH515 <- go_tableH515 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsH515 <- cardiac_goH515

final_tableH515_StrongCardiac <- final_tableH515 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableH515_StrongCardiac, "data/DGE/final_tableH515_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resH1530 <- make_cardiac_table(fit2, "H_Day1530")

final_tableH1530 <- resH1530$table
go_tableH1530 <- resH1530$go
cardiac_goH1530 <- resH1530$cardiac_go

enriched_termsH1530 <- go_tableH1530 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsH1530 <- cardiac_goH1530

final_tableH1530_StrongCardiac <- final_tableH1530 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableH1530_StrongCardiac, "data/DGE/final_tableH1530_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resC02 <- make_cardiac_table(fit2, "C_Day02")

final_tableC02 <- resC02$table
go_tableC02 <- resC02$go
cardiac_goC02 <- resC02$cardiac_go

enriched_termsC02 <- go_tableC02 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsC02 <- cardiac_goC02

final_tableC02_StrongCardiac <- final_tableC02 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableC02_StrongCardiac, "data/DGE/final_tableC02_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resC25 <- make_cardiac_table(fit2, "C_Day25")

final_tableC25 <- resC25$table
go_tableC25 <- resC25$go
cardiac_goC25 <- resC25$cardiac_go

enriched_termsC25 <- go_tableC25 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsC25 <- cardiac_goC25

final_tableC25_StrongCardiac <- final_tableC25 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableC25_StrongCardiac, "data/DGE/final_tableC25_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resC515 <- make_cardiac_table(fit2, "C_Day515")

final_tableC515 <- resC515$table
go_tableC515 <- resC515$go
cardiac_goC515 <- resC515$cardiac_go

enriched_termsC515 <- go_tableC515 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsC515 <- cardiac_goC515

final_tableC515_StrongCardiac <- final_tableC515 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableC515_StrongCardiac, "data/DGE/final_tableC515_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resC1530 <- make_cardiac_table(fit2, "C_Day1530")

final_tableC1530 <- resC1530$table
go_tableC1530 <- resC1530$go
cardiac_goC1530 <- resC1530$cardiac_go

enriched_termsC1530 <- go_tableC1530 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsC1530 <- cardiac_goC1530

final_tableC1530_StrongCardiac <- final_tableC1530 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableC1530_StrongCardiac, "data/DGE/final_tableC1530_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resHvC0 <- make_cardiac_table(fit2, "HvC_Day0")

final_tableHvC0 <- resHvC0$table
go_tableHvC0 <- resHvC0$go
cardiac_goHvC0 <- resHvC0$cardiac_go

enriched_termsHvC0 <- go_tableHvC0 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsHvC0 <- cardiac_goHvC0

final_tableHvC0_StrongCardiac <- final_tableHvC0 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableHvC0_StrongCardiac, "data/DGE/final_tableHvC0_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resHvC2 <- make_cardiac_table(fit2, "HvC_Day2")

final_tableHvC2 <- resHvC2$table
go_tableHvC2 <- resHvC2$go
cardiac_goHvC2 <- resHvC2$cardiac_go

enriched_termsHvC2 <- go_tableHvC2 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsHvC2 <- cardiac_goHvC2

final_tableHvC2_StrongCardiac <- final_tableHvC2 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableHvC2_StrongCardiac, "data/DGE/final_tableHvC2_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resHvC5 <- make_cardiac_table(fit2, "HvC_Day5")

final_tableHvC5 <- resHvC5$table
go_tableHvC5 <- resHvC5$go
cardiac_goHvC5 <- resHvC5$cardiac_go

enriched_termsHvC5 <- go_tableHvC5 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsHvC5 <- cardiac_goHvC5

final_tableHvC5_StrongCardiac <- final_tableHvC5 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableHvC5_StrongCardiac, "data/DGE/final_tableHvC5_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resHvC15 <- make_cardiac_table(fit2, "HvC_Day15")

final_tableHvC15 <- resHvC15$table
go_tableHvC15 <- resHvC15$go
cardiac_goHvC15 <- resHvC15$cardiac_go

enriched_termsHvC15 <- go_tableHvC15 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsHvC15 <- cardiac_goHvC15

final_tableHvC15_StrongCardiac <- final_tableHvC15 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableHvC15_StrongCardiac, "data/DGE/final_tableHvC15_StrongCardiac.csv", row.names = FALSE)
```

```{r}
resHvC30 <- make_cardiac_table(fit2, "HvC_Day30")

final_tableHvC30 <- resHvC30$table
go_tableHvC30 <- resHvC30$go
cardiac_goHvC30 <- resHvC30$cardiac_go

enriched_termsHvC30 <- go_tableHvC30 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_termsHvC30 <- cardiac_goHvC30

final_tableHvC30_StrongCardiac <- final_tableHvC30 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_tableHvC30_StrongCardiac, "data/DGE/final_tableHvC30_StrongCardiac.csv", row.names = FALSE)
```

```{r}
res02 <- make_cardiac_table(fit2, "Sig_Sp_inter_Traj02")

final_table02 <- res02$table
go_table02 <- res02$go
cardiac_go02 <- res02$cardiac_go

enriched_terms02 <- go_table02 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_terms02 <- cardiac_go02

final_table02_StrongCardiac <- final_table02 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_table02_StrongCardiac, "data/DGE/final_table02_StrongCardiac.csv", row.names = FALSE)
```

```{r}
res25 <- make_cardiac_table(fit2, "Sig_Sp_inter_Traj25")

final_table25 <- res25$table
go_table25 <- res25$go
cardiac_go25 <- res25$cardiac_go

enriched_terms25 <- go_table25 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_terms25 <- cardiac_go25

final_table25_StrongCardiac <- final_table25 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_table25_StrongCardiac, "data/DGE/final_table25_StrongCardiac.csv", row.names = FALSE)
```

```{r}
res515 <- make_cardiac_table(fit2, "Sig_Sp_inter_Traj515")

final_table515 <- res515$table
go_table515 <- res515$go
cardiac_go515 <- res515$cardiac_go

enriched_terms515 <- go_table515 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_terms515 <- cardiac_go515

final_table515_StrongCardiac <- final_table515 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_table515_StrongCardiac, "data/DGE/final_table515_StrongCardiac.csv", row.names = FALSE)
```

```{r}
res1530 <- make_cardiac_table(fit2, "Sig_Sp_inter_Traj1530")

final_table1530 <- res1530$table
go_table1530 <- res1530$go
cardiac_go1530 <- res1530$cardiac_go

enriched_terms1530 <- go_table1530 %>%
  filter(p.adjust < 0.05) %>%
  arrange(p.adjust)

cardiac_terms1530 <- cardiac_go1530

final_table1530_StrongCardiac <- final_table1530 %>% 
  filter(category == 'Strong cardiac')

write.csv(final_table1530_StrongCardiac, "data/DGE/final_table1530_StrongCardiac.csv", row.names = FALSE)
```

```{r}
Sig_sp_int_15_30_Table <- make_cardiac_table(
  fit = fit2,
  coef_name = "Sig_Sp_inter_Traj1530",
  mapping = mapping,
  cardiac_go = cardiac_go
)

Sig_sp_int_15_30_Table_StrongCardiac <- Sig_sp_int_15_30_Table %>% 
  filter(category == 'Strong cardiac')
```

```{r}
background_genes <- unique(TopTable_RNA_All$Gene)
sig_genes <- df_dir_02_human$Gene  

  ego <- enrichGO(
  gene     = sig_genes,
  universe = background_genes,
  OrgDb    = org.Hs.eg.db,
  keyType  = "ENSEMBL",
  ont      = "BP",
  readable = FALSE
)

go_table_Int02_HumanUp <- as.data.frame(ego)
```

```{r}
background_genes <- unique(TopTable_RNA_All$Gene)
sig_genes <- df_dir_02_chimp$Gene  

  ego <- enrichGO(
  gene     = sig_genes,
  universe = background_genes,
  OrgDb    = org.Hs.eg.db,
  keyType  = "ENSEMBL",
  ont      = "BP",
  readable = FALSE
)

go_table_Int02_ChimpUp <- as.data.frame(ego)
```


```{r}
# # BiocManager::install("biomaRt", update = TRUE, ask = FALSE)
# library(biomaRt)
# 
# base <- sig_int_Traj2 %>%
#   rownames_to_column("ENSEMBL")
# 
# mart <- useEnsembl(
#   biomart = "genes",
#   dataset = "hsapiens_gene_ensembl",
#   mirror = "useast"
# )
# 
# mapping <- getBM(
#   attributes = c("ensembl_gene_id", "hgnc_symbol"),
#   filters = "ensembl_gene_id",
#   values = base,
#   mart = mart
# )
# 
# mapping <- mapping %>%
#   filter(hgnc_symbol != "") %>%
#   distinct(ensembl_gene_id, .keep_all = TRUE)
# 
# results_annot <- merge(sig_int_Traj2, mapping,
#                        by.x = "row.names",
#                        by.y = "ensembl_gene_id",
#                        all.x = TRUE)
# 
# colnames(results_annot)[1] <- "ENSEMBL"
# 
# library(clusterProfiler)
# library(org.Hs.eg.db)
# 
# ego <- enrichGO(
#   gene          = mapping$ensembl_gene_id,
#   OrgDb         = org.Hs.eg.db,
#   keyType       = "ENSEMBL",
#   ont           = "BP",
#   readable      = TRUE
# )
# 
# go_table <- ego@result
# 
# cardiac_go <- go_table[
#   grepl("heart|cardiac|cardiovascular|circulatory", 
#         go_table$Description, ignore.case = TRUE),
# ]
# 
# cardiac_genes <- unique(unlist(strsplit(cardiac_go$geneID, "/")))
# 
# results_annot$cardiac_category <- ifelse(
#   results_annot$hgnc_symbol %in% cardiac_genes,
#   "Cardiac-related",
#   "None"
# )
# 
# results_annot$score <- ifelse(results_annot$hgnc_symbol %in% cardiac_genes, 1, 0)
# 
# results_annot$category <- case_when(
#   
#   !is.na(results_annot$adj.P.Val) &
#   !is.na(results_annot$logFC) &
#   results_annot$score == 1 &
#   results_annot$adj.P.Val < 0.05 &
#   abs(results_annot$logFC) > 1 ~ "Strong cardiac",
#   
#   results_annot$score == 1 &
#   (results_annot$adj.P.Val < 0.05 |
#    abs(results_annot$logFC) > 0.5) ~ "Moderate cardiac",
#   
#   results_annot$score == 1 ~ "Weak cardiac",
#   
#   TRUE ~ "None"
# )
# 
# mapping <- mapping %>%
#   dplyr::rename(ENSEMBL = ensembl_gene_id)
# 
# final_table <- sig_int_Traj2 %>%
#   tibble::rownames_to_column("ENSEMBL") %>%
#   
#   # join gene symbols
#   left_join(mapping, by = "ENSEMBL") %>%
#   
#   # join limma-based annotations (your category lives here)
#   left_join(results_annot %>% 
#               dplyr::select(ENSEMBL, category),
#             by = "ENSEMBL") %>%
#   
#   dplyr::select(ENSEMBL, hgnc_symbol, logFC, adj.P.Val, category)
# 
# results_annot %>%
#   filter(category == "Strong cardiac") %>%
#   pull(ENSEMBL)

```

```{r RNASeq_DGE_Interactions_Day5, fig.width = 15, fig.height= 10}
int_Traj5 <- topTable(fit2, coef="Sig_Sp_inter_Traj25")
top_int_Traj5 <- topTable(fit2, coef="Sig_Sp_inter_Traj25", number=20)
top_genes <- rownames(top_int_Traj5)

library(dplyr)
library(tidyr)

expr_mat <- v2$E[top_genes, ]  # expression for top genes

plot_df <- as.data.frame(t(expr_mat))
plot_df$Sample <- rownames(plot_df)

plot_df <- cbind(plot_df, RNA_Metadata_NoD4_NoRep)

# Make time numeric for ordering
plot_df$Time <- factor(plot_df$Cond,
                       levels=c("H_Day0","H_Day2","H_Day5","H_Day15","H_Day30",
                                "C_Day0","C_Day2","C_Day5","C_Day15","C_Day30"))

library(ggplot2)

gene_to_plot <- top_genes[1]

ggplot(plot_df,
       aes(x=Cond,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Trajectory:", gene_to_plot),
       y="log2 CPM")

plot_df$TimeOnly <- gsub("H_|C_", "", plot_df$Cond)
plot_df$TimeOnly <- factor(plot_df$TimeOnly,
                           levels=c("Day0","Day2","Day5","Day15","Day30"))

ggplot(plot_df,
       aes(x=TimeOnly,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Interaction trajectory:", gene_to_plot),
       x="Time",
       y="log2 CPM")

plot_long <- plot_df %>%
  pivot_longer(cols=all_of(top_genes),
               names_to="Gene",
               values_to="Expression")

ggplot(plot_long,
       aes(x=TimeOnly,
           y=Expression,
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line") +
  stat_summary(fun=mean, geom="point") +
  facet_wrap(~Gene, scales="free_y") +
  theme_classic()
```

```{r RNASeq_DGE_Interactions_Day15, fig.width = 15, fig.height= 10}
int_Traj15 <- topTable(fit2, coef="Sig_Sp_inter_Traj515")
top_int_Traj15 <- topTable(fit2, coef="Sig_Sp_inter_Traj515", number=20)
top_genes <- rownames(top_int_Traj15)

library(dplyr)
library(tidyr)

expr_mat <- v2$E[top_genes, ]  # expression for top genes

plot_df <- as.data.frame(t(expr_mat))
plot_df$Sample <- rownames(plot_df)

plot_df <- cbind(plot_df, RNA_Metadata_NoD4_NoRep)

# Make time numeric for ordering
plot_df$Time <- factor(plot_df$Cond,
                       levels=c("H_Day0","H_Day2","H_Day5","H_Day15","H_Day30",
                                "C_Day0","C_Day2","C_Day5","C_Day15","C_Day30"))

library(ggplot2)

gene_to_plot <- top_genes[1]

ggplot(plot_df,
       aes(x=Cond,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Trajectory:", gene_to_plot),
       y="log2 CPM")

plot_df$TimeOnly <- gsub("H_|C_", "", plot_df$Cond)
plot_df$TimeOnly <- factor(plot_df$TimeOnly,
                           levels=c("Day0","Day2","Day5","Day15","Day30"))

ggplot(plot_df,
       aes(x=TimeOnly,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Interaction trajectory:", gene_to_plot),
       x="Time",
       y="log2 CPM")

plot_long <- plot_df %>%
  pivot_longer(cols=all_of(top_genes),
               names_to="Gene",
               values_to="Expression")

ggplot(plot_long,
       aes(x=TimeOnly,
           y=Expression,
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line") +
  stat_summary(fun=mean, geom="point") +
  facet_wrap(~Gene, scales="free_y") +
  theme_classic()
```

```{r RNASeq_DGE_Interactions_Day30, fig.width = 15, fig.height= 10}
int_Traj30 <- topTable(fit2, coef="Sig_Sp_inter_Traj1530")
top_int_Traj30 <- topTable(fit2, coef="Sig_Sp_inter_Traj1530", number=20)
top_genes <- rownames(top_int_Traj30)

library(dplyr)
library(tidyr)

expr_mat <- v2$E[top_genes, ]  # expression for top genes

plot_df <- as.data.frame(t(expr_mat))
plot_df$Sample <- rownames(plot_df)

plot_df <- cbind(plot_df, RNA_Metadata_NoD4_NoRep)

# Make time numeric for ordering
plot_df$Time <- factor(plot_df$Cond,
                       levels=c("H_Day0","H_Day2","H_Day5","H_Day15","H_Day30",
                                "C_Day0","C_Day2","C_Day5","C_Day15","C_Day30"))

library(ggplot2)

gene_to_plot <- top_genes[1]

ggplot(plot_df,
       aes(x=Cond,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Trajectory:", gene_to_plot),
       y="log2 CPM")

plot_df$TimeOnly <- gsub("H_|C_", "", plot_df$Cond)
plot_df$TimeOnly <- factor(plot_df$TimeOnly,
                           levels=c("Day0","Day2","Day5","Day15","Day30"))

ggplot(plot_df,
       aes(x=TimeOnly,
           y=.data[[gene_to_plot]],
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line", size=1.2) +
  stat_summary(fun=mean, geom="point", size=3) +
  theme_classic() +
  labs(title=paste("Interaction trajectory:", gene_to_plot),
       x="Time",
       y="log2 CPM")
plot_long <- plot_df %>%
  pivot_longer(cols=all_of(top_genes),
               names_to="Gene",
               values_to="Expression")

ggplot(plot_long,
       aes(x=TimeOnly,
           y=Expression,
           color=Species,
           group=Species)) +
  stat_summary(fun=mean, geom="line") +
  stat_summary(fun=mean, geom="point") +
  facet_wrap(~Gene, scales="free_y") +
  theme_classic()
```

```{r RNASeq_DGE_Interactions_Overlaps, fig.width = 15, fig.height= 10}

# Make a copy to be safe
chdgene_table_copy <- chdgene_table
# 
# # Check
# colnames(chdgene_table_copy)
# 
# #ENSEMBL ID
# all_ensembl_ids <- unique(TopTable_RNA_All$Gene)
# 
# ensembl <- useMart(
#   "ensembl",
#   dataset = "hsapiens_gene_ensembl"
# )
# 
# ensembl_to_hgnc <- getBM(
#   attributes = c("ensembl_gene_id", "hgnc_symbol"),
#   filters = "ensembl_gene_id",
#   values = all_ensembl_ids,
#   mart = ensembl
# ) %>%
#   filter(hgnc_symbol != "") %>%
#   distinct()
# 
# saveRDS(
#   ensembl_to_hgnc,
#   "data/DGE/Species/Ensembl_to_HGNC_mapping.RDS"
# )

ensembl_to_hgnc <- readRDS("data/DGE/Species/Ensembl_to_HGNC_mapping.RDS")

# Loop through my data sets to overlap
known_genes <- chdgene_table_copy$Gene

CHD_overlap_results <- list()

for (day in names(RNA_sets)) {

  message("Processing ", day)

  DEG_Set <- unique(RNA_sets[[day]]$DEGs$Gene)
  Non_DEG_Set <- unique(RNA_sets[[day]]$NonDEGs$Gene)

  # ---- DEG overlaps ----
  DEG_Overlaps_symbols <- ensembl_to_hgnc$ensembl_gene_id[
    ensembl_to_hgnc$ensembl_gene_id %in% DEG_Set &
    ensembl_to_hgnc$hgnc_symbol %in% known_genes 
  ]

  # ---- Non-DEG overlaps ----
  Non_DEG_Overlaps_symbols <- ensembl_to_hgnc$ensembl_gene_id[
    ensembl_to_hgnc$ensembl_gene_id %in% Non_DEG_Set &
    ensembl_to_hgnc$hgnc_symbol %in% known_genes
  ]

  CHD_overlap_results[[day]] <- list(
    DEG_CHD_Genes = unique(DEG_Overlaps_symbols),
    NonDEG_CHD_Genes = unique(Non_DEG_Overlaps_symbols)
  )

  saveRDS(
    unique(DEG_Overlaps_symbols),
    paste0("data/DGE/Species/", day, "_DEG_CHDGenes.RDS")
  )

  saveRDS(
    unique(Non_DEG_Overlaps_symbols),
    paste0("data/DGE/Species/", day, "_NonDEG_CHDGenes.RDS")
  )
}

```


```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
H_comp <- "H_Day02"
C_comp <- "C_Day02"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  xlim(x_limits) +
  ylim(y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
H_comp <- "H_Day25"
C_comp <- "C_Day25"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  xlim(x_limits) +
  ylim(y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )


```


```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
H_comp <- "H_Day515"
C_comp <- "C_Day515"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  xlim(x_limits) +
  ylim(y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )

```

```{r RNASeq_DGE_Clusters_FC_Quadrants_2_0}
H_comp <- "H_Day1530"
C_comp <- "C_Day1530"

df_wide <- TopTable_RNA_All %>%
  filter(Comparisons %in% c(H_comp, C_comp)) %>%
  dplyr::select(Gene, Comparisons, logFC) %>%
  group_by(Gene, Comparisons) %>%
  summarize(logFC = mean(logFC), .groups = "drop") %>%
  pivot_wider(names_from = Comparisons, values_from = logFC) %>%
  filter(!is.na(.data[[H_comp]]), !is.na(.data[[C_comp]]))

# head(df_wide)
# nrow(df_wide)

fit <- lm(df_wide[[C_comp]] ~ df_wide[[H_comp]])
summary(fit)

r2 <- summary(fit)$r.squared
pval <- summary(fit)$coefficients[2, "Pr(>|t|)"]

# r2
# pval

format(pval, scientific = TRUE, digits = 3)

library(ggplot2)

x_pos <- max(df_wide[[H_comp]]) * 0.95      # right side
x_neg <- min(df_wide[[H_comp]]) * 0.5      # left side

y_pos <- max(df_wide[[C_comp]]) * 0.95

# Optional: make axes symmetric around 0 for a nicer visual
max_val <- max(abs(c(x_limits, y_limits)))
x_limits <- c(-15, 15)
y_limits <- c(-15, 15)

# Plot
ggplot(df_wide, aes(x = .data[[H_comp]], y = .data[[C_comp]])) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  annotate(
    "text",
    x = x_neg,
    y = y_pos,
    label = paste0(
      "R² = ", round(r2, 3),
      "\np = ", format(pval, scientific = TRUE, digits = 3)
    ),
    hjust = 1,
    vjust = 1
  ) +
  xlim(x_limits) +
  ylim(y_limits) +
  theme_bw() +
  labs(
    x = H_comp,
    y = C_comp,
    title = paste0(H_comp, " vs ", C_comp)
  )
```


####RMGO_All

```{r RNASeq_DGE_Trajectory_Data}
RNA_Metadata_NoRep <- RNA_Metadata %>%
  filter(!grepl("R$",Individual))

Filt_RMG0_RNA_fc_NoRep <- Filt_RMG0_RNA_fc %>%
  dplyr::select(-(contains("R")))

RNA_Metadata_NoRep$dgelist <- c(rep(c("Human_Day0","Human_Day2","Human_Day4","Human_Day5","Human_Day15","Human_Day30","Chimp_Day0","Chimp_Day2","Chimp_Day4","Chimp_Day5","Chimp_Day15","Chimp_Day30"),7))

#create DGEList object
dge_RMGO_All <- DGEList(counts = Filt_RMG0_RNA_fc_NoRep)
dge_RMGO_All$samples$group <- factor(RNA_Metadata_NoRep$dgelist)
dge_RMGO_All <- calcNormFactors(dge_RMGO_All, method = "TMM")
dge_RMGO_All$samples

dim(dge_RMGO_All)
# saveRDS(dge_RMGO_All, "data/DGE/Species/concat/RowMeans/All/dge_RMGO_All.RDS")
dge_RMGO_All$samples

```

```{r RNASeq_DGE_Trajectory_Data_Model}
RNA_Metadata_NoRep$Species <- factor(
  RNA_Metadata_NoRep$Species,
  levels = c("C", "H")   # Chimp baseline
)

RNA_Metadata_NoRep$Timepoint <- factor(
  RNA_Metadata_NoRep$Timepoint,
  levels = c("Day0","Day2","Day4","Day5","Day15","Day30")
)

design_int_RMG0_All <- model.matrix(~ Species * Timepoint,
                           data = RNA_Metadata_NoRep)

colnames(design_int_RMG0_All)
colnames(design_int_RMG0_All) <- make.names(colnames(design_int_RMG0_All))

# saveRDS(design_int_RMG0_All, "data/DGE/Species/concat/RowMeans/All/design_int_RMG0_All.RDS")
```

```{r RNASeq_DGE_Trajectory_Data_Model}
dge <- dge_RMGO_All
design_int <- design_int_RMG0_All

# Step 1: voom first
v1 <- voom(dge, design_int, plot = TRUE)

# saveRDS(v1,"data/DGE/Species/concat/RowMeans/All/v1_RMG0_All.RDS")

# Step 2: estimate duplicate correlation on voom-transformed data
corfit <- duplicateCorrelation(v1, design_int, block = RNA_Metadata_NoRep$Individual)
corfit.correlation <- corfit$consensus.correlation

# Step 3: voom again including correlation
v2 <- voom(dge, design_int, plot = TRUE,
           block = RNA_Metadata_NoRep$Individual,
           correlation = corfit.correlation)

# Step 4: fit linear model
fit <- lmFit(v2, design_int, block = RNA_Metadata_NoRep$Individual, correlation = corfit.correlation)
fit <- eBayes(fit)

pal <- rainbow(length(unique(RNA_Metadata_NoRep$Timepoint)))
day <- RNA_Metadata_NoRep$Timepoint

plotDensities(v2, col = pal[as.numeric(day)], legend = FALSE)

# saveRDS(fit, "data/DGE/Species/concat/RowMeans/All/fit_RMG0_All.RDS")
```

```{r RNASeq_DGE_Trajectory_Data_Model}
fit <- fit_RMG0_All
design_int <- design_int_RMG0_All

contrast_matrix <- makeContrasts(

  # Species differences
  HvC_Day0  = SpeciesH,
  HvC_Day2  = SpeciesH + SpeciesH.TimepointDay2,
  HvC_Day4  = SpeciesH + SpeciesH.TimepointDay4,
  HvC_Day5  = SpeciesH + SpeciesH.TimepointDay5,
  HvC_Day15 = SpeciesH + SpeciesH.TimepointDay15,
  HvC_Day30 = SpeciesH + SpeciesH.TimepointDay30,
  
  #Trajectory differences
  H_Day02 = TimepointDay2 + SpeciesH.TimepointDay2,
  H_Day24 = TimepointDay4 + SpeciesH.TimepointDay4 - TimepointDay2 - SpeciesH.TimepointDay2,
  H_Day45 = TimepointDay5 + SpeciesH.TimepointDay5 - TimepointDay4 - SpeciesH.TimepointDay4,
  H_Day515 = TimepointDay15 + SpeciesH.TimepointDay15 - TimepointDay5 - SpeciesH.TimepointDay5,
  H_Day1530 = TimepointDay30 + SpeciesH.TimepointDay30 - TimepointDay15 - SpeciesH.TimepointDay15,
  C_Day02 = TimepointDay2,
  C_Day24 = TimepointDay4 - TimepointDay2,
  C_Day45 = TimepointDay5 - TimepointDay4,
  C_Day515 = TimepointDay15 - TimepointDay5,
  C_Day1530 = TimepointDay30 - TimepointDay15,
  
  # True interaction tests trajectory
  Sig_Sp_inter_Traj02 = SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj24 = SpeciesH.TimepointDay4 - SpeciesH.TimepointDay2,
  Sig_Sp_inter_Traj45 = SpeciesH.TimepointDay5 - SpeciesH.TimepointDay4,
  Sig_Sp_inter_Traj515 = SpeciesH.TimepointDay15 - SpeciesH.TimepointDay5,
  Sig_Sp_inter_Traj1530 = SpeciesH.TimepointDay30 - SpeciesH.TimepointDay15,
  
  levels = design_int
)

fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

plotSA(fit2, main = "RNA Model")

results_summary <- decideTests(fit2,
                               adjust.method = "BH",
                               p.value = 0.05)
summary(results_summary)

# saveRDS(fit2, "data/DGE/Species/concat/RowMeans/All/fit2_RMG0_All.RDS")
```

```{r RNASeq_DGE_Trajectory_TopTable}
fit2 <- fit2_RMG0_All

#Create Human TopTable. using listapply, then you can pull specific comp using the $
TopTables_RNA_names <- colnames(fit2$coefficients) 

TopTable_RNA_All <- do.call(
  rbind,
  lapply(TopTables_RNA_names,function(ct) {
    
    tt <- topTable(
      fit2,
      coef = ct,
      number = Inf,
      sort.by = "p"
    )
    
    #add identifiers
    tt$Gene <- rownames(tt)
    tt$Comparisons <- ct
    
    tt
  })
)

Comparison_names <- unique(TopTable_RNA_All$Comparisons)

# saveRDS(TopTable_RNA_All, "data/DGE/Species/concat/RowMeans/All/TopTable_RNA_All_RMGO_All.RDS")
# saveRDS(Comparison_names, "data/DGE/Species/concat/RowMeans/All/Comparison_names_RNA_All_RMGO_All.RDS")

head(TopTable_RNA_All)
```

```{r RNASeq_DGE_Trajectory_TopTable_VolcancoPlots}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_All
Comparison_names <- Comparison_names_RMGO_All

# Calculate global axis limits
x_limits <- range(TopTable_RNA_All$logFC, na.rm = TRUE)
y_limits <- range(-log10(TopTable_RNA_All$P.Value), na.rm = TRUE)

plot <- list()

for (n in Comparison_names) {
  data_n <- TopTable_RNA_All %>% 
    dplyr::filter(Comparisons == n)
  
  plot[[n]] <- generate_volcano_plot(data_n, n) +
    ggplot2::xlim(x_limits) +
    ggplot2::ylim(y_limits)
}

# Print plots
for (n in Comparison_names) {
  print(plot[[n]])
}
```

```{r RNASeq_DGE_Trajectory_TopTable_Subsetting0.05}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_All
Comparison_names <- Comparison_names_RMGO_All

RNA_sets <- map(
  Comparison_names,
  ~ {
    df <- TopTable_RNA_All %>%
      filter(Comparisons == paste0(.x))

    list(
      DEGs = df %>% filter(adj.P.Val < 0.05),
      NonDEGs = df %>% filter(adj.P.Val >= 0.05)
    )
  }
)


names(RNA_sets) <- paste0(Comparison_names)

# saveRDS(RNA_sets, "data/DGE/Species/concat/RowMeans/All/RNA_sets_RMG0_All.RDS")
```

```{r}

TopTable_RNA_All <- TopTable_RNA_All_RMGO_All
Comparison_names <- Comparison_names_RMGO_All
RNA_sets <- RNA_sets_RMG0_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Inter <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

Inter_02_genes <- unique(RNA_sets$Sig_Sp_inter_Traj02$DEGs$Gene)
Inter_24_genes <- unique(RNA_sets$Sig_Sp_inter_Traj24$DEGs$Gene)
Inter_45_genes <- unique(RNA_sets$Sig_Sp_inter_Traj45$DEGs$Gene)
Inter_515_genes <- unique(RNA_sets$Sig_Sp_inter_Traj515$DEGs$Gene)
Inter_1530_genes <- unique(RNA_sets$Sig_Sp_inter_Traj1530$DEGs$Gene)

cluster_lists <- list(
  Inter_02_genes  = Inter_02_genes,
  Inter_24_genes  = Inter_24_genes,
  Inter_45_genes  = Inter_45_genes,
  Inter_515_genes  = Inter_515_genes,
  Inter_1530_genes  = Inter_1530_genes
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Inter)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_absfc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Inter)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


# saveRDS(TopTable_RNA_Inter, "data/DGE/Species/concat/RowMeans/All/TopTable_RNA_Inter_RMG0_Al.RDS")
```

```{r}
TopTable_RNA_All <- TopTable_RNA_All_RMGO_All
fit2 <- fit2_RMG0_All

traj_info <- list(
  Traj02 = list(coef = "Sig_Sp_inter_Traj02", comp = "Day02"),
  Traj24 = list(coef = "Sig_Sp_inter_Traj24", comp = "Day24"),
  Traj45 = list(coef = "Sig_Sp_inter_Traj45", comp = "Day45"),
  Traj515 = list(coef = "Sig_Sp_inter_Traj515", comp = "Day515"),
  Traj1530 = list(coef = "Sig_Sp_inter_Traj1530", comp = "Day1530")
)

direction_results <- setNames(
  lapply(names(traj_info), function(name) {

    info <- traj_info[[name]]

    get_fc_directions(
      traj_label = name,
      coef_name = info$coef,
      comparison_label = info$comp,
      top_table_all = TopTable_RNA_All,
      fit_obj = fit2
    )

  }),
  names(traj_info)
)

# saveRDS(direction_results, "data/DGE/Species/concat/RowMeans/All/Interaction_Directions_All.RDS")
```

```{r}


TopTable_RNA_All <- TopTable_RNA_All_RMGO_All
Comparison_names <- Comparison_names_RMGO_All
RNA_sets <- Interaction_Directions_All

TopTable_RNA_All$absfc <- abs(TopTable_RNA_All$logFC)

TopTable_RNA_Inter <- TopTable_RNA_All %>% 
  filter(Comparisons %in% c(
    "H_Day02","H_Day24","H_Day45","H_Day515","H_Day1530",
    "C_Day02","C_Day24","C_Day45","C_Day515","C_Day1530"
  ))

a <- unique(RNA_sets$Traj02$all$Gene)
b <- unique(RNA_sets$Traj02$H_pos_C_neg$Gene)
c <- unique(RNA_sets$Traj02$H_neg_C_pos$Gene)
d <- unique(RNA_sets$Traj02$same$Gene)
e <- unique(RNA_sets$Traj24$all$Gene)
f <- unique(RNA_sets$Traj24$H_pos_C_neg$Gene)
g <- unique(RNA_sets$Traj24$H_neg_C_pos$Gene)
h <- unique(RNA_sets$Traj24$same$Gene)
i <- unique(RNA_sets$Traj45$all$Gene)
j <- unique(RNA_sets$Traj45$H_pos_C_neg$Gene)
k <- unique(RNA_sets$Traj45$H_neg_C_pos$Gene)
l <- unique(RNA_sets$Traj45$same$Gene)
m <- unique(RNA_sets$Traj515$all$Gene)
n <- unique(RNA_sets$Traj515$H_pos_C_neg$Gene)
o <- unique(RNA_sets$Traj515$H_neg_C_pos$Gene)
p <- unique(RNA_sets$Traj515$same$Gene)
q <- unique(RNA_sets$Traj1530$all$Gene)
r <- unique(RNA_sets$Traj1530$H_pos_C_neg$Gene)
s <- unique(RNA_sets$Traj1530$H_neg_C_pos$Gene)
t <- unique(RNA_sets$Traj1530$same$Gene)

cluster_lists <- list(
  Inter02_All = a,
  Inter02_HumanPos = b,
  Inter02_ChimpPos = c,
  Inter02_Same = d,
  Inter24_All = e,
  Inter24_HumanPos = f,
  Inter24_ChimpPos = g,
  Inter24_Same = h,
  Inter45_All = j,
  Inter45_HumanPos = j,
  Inter45_ChimpPos = k,
  Inter45_Same = l,
  Inter515_All = m,
  Inter515_HumanPos = n,
  Inter515_ChimpPos = o,
  Inter515_Same = p,
  Inter1530_All = q,
  Inter1530_HuamnPos = r,
  Inter1530_ChimpPos = s,
  Inter1530_Same = t
  
)

cluster_plots <- lapply(names(cluster_lists), function(clust_name) {
  plot_cluster_fc_sig(cluster_lists[[clust_name]], clust_name, TopTable_RNA_Inter)
})
names(cluster_plots) <- names(cluster_lists)

for (p in cluster_plots) print(p)


```

```{r}
fit2 <- fit2_RMG0_All
v <- v1_RMG0_All

EnrichGo_Traj02 <- Enrich_Go(fit2, "Sig_Sp_inter_Traj02", v)

EnrichGo_Traj24 <- Enrich_Go(fit2, "Sig_Sp_inter_Traj24", v)

EnrichGo_Traj45 <- Enrich_Go(fit2, "Sig_Sp_inter_Traj45", v)

EnrichGo_Traj515 <- Enrich_Go(fit2, "Sig_Sp_inter_Traj515", v)

EnrichGo_Traj1530 <- Enrich_Go(fit2, "Sig_Sp_inter_Traj1530", v)


saveRDS(EnrichGo_Traj02, "data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj02_All.RDS")
saveRDS(EnrichGo_Traj24, "data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj24_All.RDS")
saveRDS(EnrichGo_Traj45, "data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj45_All.RDS")
saveRDS(EnrichGo_Traj515, "data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj515_All.RDS")
saveRDS(EnrichGo_Traj1530, "data/DGE/Species/concat/RowMeans/All/EnrichGo_Traj1530_All.RDS")
```


```{r Updating Website, eval = FALSE, fig.height=10, fig.width=10}

Trajectory_go_results_lcpm1_4SpTp$Traj45_genes$Both_neg


# git -> commit all changes
# git -> push
# wflow_publish("analysis/RNA_DGE_Interactions_RMG0.Rmd")

```

