---
title: "RNA_RUV Corrections"
output: html_document
date: "2026-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Setting_Up_Enviroment, results="hide"}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")

# BiocManager::install("SummarizedExperiment")

RNA_fc_df <- readRDS("data/Raw_Data/RNA_fc_df.RDS")
RNA_Metadata <- readRDS("data/Raw_Data/RNA_Metadata.RDS")
RNA_Metadata_No4 <- readRDS("data/QC/RNA_Metatdata_No4.RDS")
Filt_RMG0_RNA_fc_NoD4 <- readRDS("data/QC/Filt_RMG0_RNA_fc_NoD4.RDS")
Filt_RMG0_RNA_log2cpm_NoD4 <- readRDS("data/QC/Filt_RMG0_RNA_log2cpm_NoD4.RDS")
ann_colors_No4 <- readRDS("data/QC/ann_colors_no4.RDS")

RUV_filt_counts <- readRDS( "data/RUV/RUV_filt_counts.RDS")
annot <- readRDS("data/RUV/annot_RUV.RDS")
set <- readRDS("data/RUV/SummarizedExperiment.RDS")
scIdx <- readRDS("data/RUV/scIdx.RDS")

prcomp_res_log2_k1 <- readRDS("data/RUV/prcomp_res_log2_k1.RDS")
annot_prcomp_res_k1 <- readRDS("data/RUV/annot_prcomp_res_k1.RDS")

prcomp_res_log2_k2 <- readRDS("data/prcomp_res_log2_k2.RDS")
annot_prcomp_res_k2 <- readRDS("data/annot_prcomp_res_k2.RDS")

prcomp_res_log2_k3 <- readRDS("data/RUV/prcomp_res_log2_k3.RDS")
annot_prcomp_res_k3 <- readRDS("data/RUV/annot_prcomp_res_k3.RDS")

```


```{r RNA_RUV}
filt_gene_list <- rownames(Filt_RMG0_RNA_fc)
#14838

length(filt_gene_list)


# in order to make this match with annot later down the line, change the col names for counts_raw_matrix to match final_sample_names in annot

# i'll also want to make sure I keep the replicate for this set

RNA_Metadata_No4_RUV <- RNA_Metadata_No4

Filt_RMG0_RNA_fc_RUV <- Filt_RMG0_RNA_fc_NoD4
colnames(Filt_RMG0_RNA_fc_RUV) <- RNA_Metadata_No4_RUV$Condition

RUV_filt_counts <- Filt_RMG0_RNA_fc_RUV %>% 
  as.data.frame() %>% 
  dplyr::filter(., row.names(.)%in% filt_gene_list)
dim(RUV_filt_counts)

# saveRDS(RUV_filt_counts, "data/RUV/RUV_filt_counts.RDS")

#add in the annotation files
ind_num <- RNA_Metadata_No4_RUV$Individual
type(ind_num)
length(ind_num)

annot <- as.data.frame(RNA_Metadata_No4_RUV)
type(annot)
is.data.frame(annot)

annot$Timepoint <- factor(annot$Timepoint, levels = c("Day0","Day2","Day5","Day15","Day30"),ordered = TRUE)
annot$Species <- factor(annot$Species,levels = c("H","C"),ordered = TRUE)
# saveRDS(annot,"data/RUV/annot_RUV.RDS")
#same as Metadata


#  counts need to be integer values and in a numeric matrix
# note: the log transformation needs to be accounted for in the isLog argument in RUVs function.
counts <- as.matrix(RUV_filt_counts)

# Create a DataFrame for the phenoData
phenoData <- DataFrame(annot)

set <- SummarizedExperiment(assays = counts, metadata = phenoData)

# saveRDS(set,"data/RUV/SummarizedExperiment.RDS")

scIdx <- RUVSeq::makeGroups(phenoData$Cond)

# saveRDS(scIdx,"data/RUV/scIdx.RDS")

# # Generate a background matrix
# # The column "Cond" holds the comparisons that you actually want to make. DOX_24, DMSO_24,5FU_24, DOX_3,etc.
# Day0 <- c(16,36)
# Day2 <- c(17,37)
# Day5 <- c(18,38)
# Day30 <- c(20,39)
# scIdx <- rbind(Day0,Day2,Day5,Day30)
# rownames(scIdx) <- c("[1,]","[2,]","[3,]","[4,]")
# colnames(scIdx) <- c("[,1]","[,2]")
```



```{r RNA_RUV_Control}
#now I've made all of the data I need for this - they are located in each section for k values

#DO NOT USE THESE COUNTS FOR LINEAR MODELING

#colors for all of the plots
# txtime_col
# ind_col
# time_col
# tx_col
log2cpm <- cpm(counts,log=TRUE)
# before ruv (counts PCA)
prcomp_res_log2 <- prcomp(t(Filt_RMG0_RNA_log2cpm_NoD4), scale=FALSE, center = TRUE)
annot_prcomp_res <- prcomp_res_log2$x %>% cbind(., annot)
# 
# group_2 <- annot$dgelist
# dgelist_col <- annot$dgelist
# individual_list <- annot$Individual
```


```{r RNA_RUV_Control_plot_PC1_2}

#now plot my PCA for filtered counts
####PC1/PC2####
individual_list <- RNA_Metadata_No4_RUV$Individual

ggplot2::autoplot(prcomp_res_log2,
                  data = annot_prcomp_res,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=1,
                  y=2) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RNA log2cpm RMG0")

```

```{r RNA_RUV_Control_plot_PC2_3}
ggplot2::autoplot(prcomp_res_log2,
                  data = annot_prcomp_res,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=2,
                  y=3) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RNA log2cpm RMG0")

```

```{r RNA_RUV_Control_plot_PC3_4}
ggplot2::autoplot(prcomp_res_log2,
                  data = annot_prcomp_res,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=3,
                  y=4) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RNA log2cpm RMG0")

```


```{r RNA_RUV_Control_plot_PC4_5}
ggplot2::autoplot(prcomp_res_log2,
                  data = annot_prcomp_res,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=4,
                  y=5) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RNA log2cpm RMG0")

```

```{r RNA_RUV_k1)}
set1 <- RUVSeq::RUVs(x = counts, k =1, scIdx = scIdx, isLog = FALSE)

# Get the RUV factors (weights) for modeling
RUV_df1 <- set1$W %>% as.data.frame()
RUV_df1$Condition <- rownames(RUV_df1)

RUV_df_rm1 <- RUV_df1[RUV_df1$Condition %in% annot$Condition, ]
View(RUV_df_rm1)
RUV_1 <- RUV_df_rm1$W_1

saveRDS(RUV_df_rm1, "data/QC/RUV_df_rm1.RDS")

saveRDS(RUV_1, "data/QC/RUV_1.RDS")


log2cpm_k1 <- cpm(set1$normalizedCounts, log = TRUE)

prcomp_res_log2_k1 <- prcomp(t(log2cpm_k1), scale=FALSE, center = TRUE)
annot_prcomp_res_k1 <- prcomp_res_log2_k1$x %>% cbind(., RNA_Metadata_No4)

# saveRDS(prcomp_res_log2_k1,"data/RUV/prcomp_res_log2_k1.RDS")
# saveRDS(annot_prcomp_res_k1,"data/RUV/annot_prcomp_res_k1.RDS")

```


```{r RNA_RUV_k1_plot)}
ggplot2::autoplot(prcomp_res_log2_k1,
                  data = annot_prcomp_res_k1,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=1,
                  y=2) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RNA log2cpm RMG0 RUV k=1")


```


```{r RNA_RUV_k2}
set2 <- RUVSeq::RUVs(x = counts, k =2, scIdx = scIdx, isLog = FALSE)

# Get the RUV factors (weights) for modeling
RUV_df2 <- set2$W %>% as.data.frame()
RUV_df2$Condition <- rownames(RUV_df2)

RUV_df_rm2 <- RUV_df2[RUV_df2$Condition %in% annot$Condition, ]
View(RUV_df_rm2)
RUV_2 <- RUV_df_rm2$W_1

log2cpm_k2 <- cpm(set2$normalizedCounts, log = TRUE)

prcomp_res_log2_k2 <- prcomp(t(log2cpm_k2), scale=FALSE, center = TRUE)
annot_prcomp_res_k2 <- prcomp_res_log2_k2$x %>% cbind(., RNA_Metadata_No4)

# saveRDS(prcomp_res_log2_k2, "data/prcomp_res_log2_k2.RDS")
# saveRDS(annot_prcomp_res_k2, "data/annot_prcomp_res_k2.RDS")
```


```{r RNA_RUV_k2_plot}
ggplot2::autoplot(prcomp_res_log2_k2,
                  data = annot_prcomp_res_k2,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=1,
                  y=2) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RNA log2cpm RMG0 RUV k=2")

```

```{r RNA_RUV_k3}
set3 <- RUVSeq::RUVs(x = counts, k =3, scIdx = scIdx, isLog = FALSE)

# Get the RUV factors (weights) for modeling
RUV_df3 <- set3$W %>% as.data.frame()
RUV_df3$Condition <- rownames(RUV_df3)

RUV_df_rm3 <- RUV_df3[RUV_df3$Condition %in% annot$Condition, ]
View(RUV_df_rm3)
RUV_3 <- RUV_df_rm3$W_1

log2cpm_k3 <- cpm(set3$normalizedCounts, log = TRUE)

prcomp_res_log2_k3 <- prcomp(t(log2cpm_k3), scale=FALSE, center = TRUE)
annot_prcomp_res_k3 <- prcomp_res_log2_k3$x %>% cbind(., RNA_Metadata_No4)

# saveRDS(prcomp_res_log2_k3, "data/RUV/prcomp_res_log2_k3.RDS")
# saveRDS(annot_prcomp_res_k3, "data/RUV/annot_prcomp_res_k3.RDS")
```


```{r RNA_RUV_k3_plot}
ggplot2::autoplot(prcomp_res_log2_k3,
                  data = annot_prcomp_res_k3,
                  colour = "Timepoint",
                  shape = "Species",
                  size = 4,
                  x=1,
                  y=2) +
  scale_color_manual(values=ann_colors_No4$timepoint_cor)+
  ggrepel::geom_text_repel(label = individual_list,
                            vjust = -0.5,
                            max.overlaps = 50)+
  ggtitle("RUV Correction k=3 log2cpm")

```


```{r Updating Website, eval = FALSE}

# #git -> commit all changes
# #git -> push
wflow_publish("analysis/RNA_RUV_Corrections.Rmd")

```
